### ISSUE TITLE
Epic: Refactoring of compute_tools

### ISSUE THREAD

**Issue by ololobus** [neondatabase/neon#1070]
Do some housekeeping after #1055:
- [x] Integrate into zenith workspace
- [x] zenithdb/console#487
- [x] ~~Get use of zenith_utils::logging~~ tracing is used instead
- [x] ~~Isolate volatile fields from ComputeState into a separate struct and use only it under lock. [See also](https://github.com/zenithdb/zenith/pull/1055#discussion_r775980288)~~
- [ ] Try to re-use [http server from libs/utils/src/http](https://github.com/neondatabase/neon/blob/9860d59aa2b91c5b30aa841a5496af08782027da/libs/utils/src/http/endpoint.rs)
- [ ] Try to get use of a control_plane::postgresql_conf
- [ ] Solve orphaned postgres issues with `prctl(PR_SET_PDEATHSIG, <SIGNAL>)` or anything else. See https://github.com/zenithdb/zenith/pull/1148#issuecomment-1016503120 for the context
