### ISSUE TITLE
Epic: performance test S3 synchronization

### ISSUE THREAD

**Issue by stepashka** [neondatabase/neon#1291]
- [ ] survive the benchmark tests on staging in terms of S3 upload
- [ ] survive full download of the tenants e.g. when replacing the pageserver
- [ ] make sure we have optics on health of S3 syncs

**Comment by SomeoneToIgnore** [comment]
First issues appeared from an expected place: rust-s3 library we use in both pageserver and safekeeper to deal with s3, requires passing `Vec<u8>` bytes when downloading/uploading a file from S3.

Benchmarks generate plenty of files (numerous GBs) that are attempted to bulk uploaded after one of pageserver's restarts.
Allocating such amount of memory at once results in errors: https://zenith-esr3609.slack.com/archives/C03438W3FLZ/p1648215123333249

One way to mitigate the issue is to use S3 libraries that approach upload/download as byte streaming.
Two alternatives already have branches in our repo: [rusoto-s3](https://github.com/zenithdb/zenith/tree/kb/rusoto-s3) and [aws-sdk-s3](https://github.com/zenithdb/zenith/tree/kb/rusoto-s3)
Both bloat the compilation time and require further testing on the same case to ensure we do the streaming right.

Currently, S3 turned off and waits for https://github.com/zenithdb/zenith/pull/1350 to be merged in, so we could fix all issues for the "right" format once.

**Comment by stepashka** [comment]
synced with @shanyp , closing as done, a bunch of perf testing was done and the next steps, if any, will be logged separately
