### ISSUE TITLE
Epic: set up non-local storage performance tests

### ISSUE THREAD

**Issue by bojanserafimov** [neondatabase/neon#1299]
Definition: A performance objective metric is a (current_result, better_achieveable_result) pair, where both numbers are either fixed, or come from running some test from the repo. We can derive some performance objectives from "postgres does this quickly, we should easily be able to match", but there are other scenarios (mostly around ops) where we have to define our own objective.

Motivation: The primary value of performance objectives is that they make test results interpretable. You don't have to read what the entire test does, and then do some math just to conclude whether our current result is good or bad. The objectives could be used as a metric for prioritization (though at some point Goodhart's Law kicks in)

- [ ] Display objectives for some/all the zenith_with_baseline tests in a grafana panel
- [ ] Allow easily running zenith_with_baseline tests on remote cluster
- [ ] Automatically run against staging (or a dedicated test cluster behind an etcd lock, if needed)
- [ ] Document testing strategy in readme

@stepashka @LizardWizzard @antons-antons @hlinnaka @knizhnik tagging you because you might have opinions. Feel free to unsubscribe if not.

also relevant and inspirational:

https://github.com/ClickHouse/ClickHouse/pull/38217
https://s3.amazonaws.com/clickhouse-test-reports/38217/190d060e09ad54b418c8f69aac6d3c0adbc90b79/performance_comparison_[4/4]/report.html
https://s3.amazonaws.com/clickhouse-test-reports/38217/190d060e09ad54b418c8f69aac6d3c0adbc90b79/performance_comparison_[3/4]/report.html
https://s3.amazonaws.com/clickhouse-test-reports/38217/190d060e09ad54b418c8f69aac6d3c0adbc90b79/performance_comparison_[2/4]/report.html
https://s3.amazonaws.com/clickhouse-test-reports/38217/190d060e09ad54b418c8f69aac6d3c0adbc90b79/performance_comparison_[1/4]/report.html

**Comment by kelvich** [comment]
👍
we also have that thing: https://zenithdb.github.io/zenith-perf-data/reports/staging.html running against staging, so graphs are in grafana/prometheus, but we don't provide links or tenant_id and start/stop time to actually check that graphs.

Also @LizardWizzard was doing some work to show results in grafana panel.

**Comment by kelvich** [comment]
Also relevant https://clickhouse.com/blog/en/2021/performance-test-1/ cc @akuzm

**Comment by kelvich** [comment]
Relevant: https://observer.zenith.tech/d/DGKBm9Jnz/perf-test-results-wip?orgId=1

**Comment by kelvich** [comment]
Split to:
* https://github.com/neondatabase/cloud/issues/2836
* https://github.com/neondatabase/neon/issues/2789
