### ISSUE TITLE
Epic: storage size — define metrics, define and achieve launch objectives

### ISSUE THREAD

**Issue by stepashka** [neondatabase/neon#1465]
To prepare for the work on this epic we need to..
- [x] define and collect the size-related metrics.

These metrics are important because the storage format efficiency affects the overall performance of the system as well as the cost.

Once we start collecting these measurements, we'd set a goal fir the Technical preview.
Below are the ideas on what could help us achieve those goals.

- #753
- [ ] zero pages
- [ ] blank spaces in the middle of pages
- [ ] wal record header data (checksum, pointer previous WAL record, ...)
- [ ] wal record relfilenode
- [ ] simplify format for clog + slru
- #1474

Others:

- [ ] prefix-compression in layer B-trees
- [ ] blob length header, use only one byte for short blobs
- [ ] compression (zstd or similar)

**Comment by stepashka** [comment]
closing this as the work is happening in 2 different teams now and we beeter udnerstand how to plan / achieve this

**Comment by stepashka** [comment]
btw, we're currenlty post launch that the title was referring to :)
