### ISSUE TITLE
Epic: Read Latency — define metrics, define and achieve launch objectives

### ISSUE THREAD

**Issue by stepashka** [neondatabase/neon#1466]
To prepare for the work on this epic we need to..
- [ ] define and collect the Read Latency metrics
- [ ] collect the Read Latency metrics from both zenith and vanilla postgres for comparison and benchmark
- [ ] #1380
- [ ] log span and metrics overhead

Once we start collecting these measurements, we'd set a goal for them for the Technical Preview.
Below are the ideas on what could help us achieve those goals.

Within page server:
- [ ] #1358
- [ ] #1339
- [ ] serde deserialization
- [ ] page cache lookups
- [ ] #733 

Compute / pageserver interface:

- [ ] prefetching, zenithdb/postgres#133
- [ ] bulk reads (for seqscans) zenithdb/postgres#133
- [ ] caching in compute node OR RATHER deploy pageserver in compute node  zenithdb/postgres#117
- [ ] #1362
- [ ] #1537
- [ ] #1522
- [x] #1919
