### ISSUE TITLE
Epic: inbound logical replication (Public Beta)

### ISSUE THREAD

**Issue by stepashka** [neondatabase/neon#1632]
we'd like to enable users for testing Neon against their common workflows
we've created a tutorial to importing a database to Neon, but this doesn't help trying Neon with the real, live apps.
let's create a tutorial explaining how to set up Neon to getting continuous updates from the cusomer's databse
@\kelvich mentioned that we should start with explaining the logical replication setup

```[tasklist]
### Tasks
- [ ] https://github.com/neondatabase/neon/issues/6977
- [x] Check that we do not suspend compute with set up inbound logical replication
- [x] Check that computes cannot subscribe to each other via internal network
- [ ] https://github.com/neondatabase/neon/pull/8669
- [ ] https://github.com/neondatabase/cloud/issues/16146
- [ ] https://github.com/neondatabase/cloud/issues/16700
- [ ] https://github.com/neondatabase/neon/issues/8097
- [ ] https://github.com/neondatabase/neon/issues/8620
```

**Comment by stepashka** [comment]
@kelvich , any additional details that are worth mentioning here?
@alubennikova , could you help with this?

**Comment by lubennikovaav** [comment]
So, we want to describe how to setup logical replication from the customer's PostgreSQL to Neon, right?

To create a subscription, the user must be a superuser. And also it requires some changes in pg_hba.conf.
Is it already implemented?

**Comment by cpursley** [comment]
Any movement on this? I'd love to be able to use [WalEx](https://github.com/cpursley/walex#postgresql-configuration) & [Supabase Realtime](https://github.com/supabase/realtime) with Neon.

**Comment by kelvich** [comment]
Hi! Not really. The rough estimate is Q4.

**Comment by asendia** [comment]
Hi team, any update on this? 😄

**Comment by vadim2404** [comment]
@lubennikovaav to review it

**Comment by save-buffer** [comment]
PR for allowing CREATE SUBSCRIPTION: https://github.com/neondatabase/neon/pull/6484

**Comment by vadim2404** [comment]
hey @johndunderhill, please, ping me (Vadim Kharitonov) in Neon discord.

**Comment by kelvich** [comment]
Sending emails about slot drops to 42 LR users in ap-se-1 (Singapore) and ap-se-2 (Sydney) now.

**Comment by lubennikovaav** [comment]
Enabled, next steps:
- Mention it in release notes
- Test and documentation about RDS->neon replication @kelvich 
- add link to e2e

**Comment by ololobus** [comment]
This week:

- [ ] @kelvich to write Daniel about replication docs
- [ ] Alexey: double check that compute can talk to each other via internal network

**Comment by ololobus** [comment]
This week:
- [ ] Konstantin: continue debugging https://github.com/neondatabase/neon/issues/8097, so far it looks like it could be a real bug

**Comment by ololobus** [comment]
- All PR for `test_subscriber_restart` got merged, so in theory we should see improvements in stats next week

**Comment by ololobus** [comment]
- Recent failure of `test_subscriber_restart` are timeouts, it's still at ~97% of success rate

This week:
- [ ] Konstantin: continue investigation with `test_subscriber_restart`
- [ ] Alexey: https://github.com/neondatabase/cloud/issues/16146, maybe expose number of subscriptions

**Comment by ololobus** [comment]
This week:

- [ ] Heikki: finalize https://github.com/neondatabase/cloud/pull/16704
- [ ]

**Comment by ololobus** [comment]
This week:

- [ ] Rescope and close

**Comment by ololobus** [comment]
Moved the only known problem to https://github.com/neondatabase/cloud/issues/17697 and added this to Q4 planning. Closing
