### ISSUE TITLE
Epic: proxy

### ISSUE THREAD

**Issue by kelvich** [neondatabase/neon#1755]
High priority projects:
- #3551

Unsorted:
- [ ] benchmark latency and throughput https://github.com/neondatabase/neon/issues/2313
- [ ] https://github.com/neondatabase/cloud/issues/2573
- [ ] move to http api in console->proxy comms (#1094)

Done:
- [x] https://github.com/neondatabase/neon/issues/2350
- [x] Support for PROXY protocol (#5028)
- [x] #3548
- [x] #3332
- [x] #3333
- [x] #3334
- [x] #2431
- [x] https://github.com/neondatabase/neon/pull/1918
- [x] #1756
- [x] #1802
- [x] https://github.com/neondatabase/neon/pull/1917
- [x] https://github.com/neondatabase/neon/issues/1309
- [x] https://github.com/neondatabase/neon/issues/1685
- [x] distinguish between 'cluster/project not found' and 'auth error'
- [x] security: add mock secret to prevent timing/probing attacks
- [x] in console: prevent web_access user login
- https://github.com/neondatabase/cloud/issues/2715

**Comment by stepashka** [comment]
a number of items from this list are also logged separately:
https://github.com/orgs/neondatabase/projects/6/views/1?filterQuery=label%3A%22c%2Fcloud%2Fproxy%22


e.g.:
- https://github.com/neondatabase/cloud/issues/1137
- https://github.com/neondatabase/cloud/issues/2715

**Comment by stradig** [comment]
All not closed issues are tracked separately.
