### ISSUE TITLE
Epic: tenant migration between storage versions

### ISSUE THREAD

**Issue by kelvich** [neondatabase/neon#1893]
We've talked about using logical dump/restore to move tenants in case of the storage format change. But that requires compute to be enabled and currently we don't have too much manual control over it. Also, a logical dump is somewhat a crutch, and building some features to support it seems like the wrong idea.

With some brainstorming during on-call handovers we've come up with a plan that seems to be better:
- [x] Implement pg_basebackup-compatible endpoint in the pageserver. Whatever storage version pageserver is running it anyway can decode it to the postgres format. So we can leverage this format as "lingua franca" of our storage formats. Also, we don't care if compute is running or not -- we just talk to the pageserver.
https://github.com/neondatabase/neon/pull/1911 - PR for the old pageserver
https://github.com/neondatabase/neon/pull/1923 - PR for main
- [x] validate data after migration on staging
- [ ] Implement something like per-tenant start_backup/stop_backup in the pageserver. To be able to import physical backup we need to be sure that the safekeeper has the necessary WAL. We can delay sending s3_consistent_lsn from the pageserver to achieve that. start_backup starts that delay, stop_backup stops.
- [x] Backpatch this endpoint to the old pageserver on staging.
- [x] Implement a backup receiver endpoint in the pageserver. Code there should be quite close to `import_local_directory`. As for the wire format, it would be cool to use the same basebackup protocol.
https://github.com/neondatabase/neon/pull/1925

- [x] Implement `push_backup` binary that uploads postgres backup into the pageserver. Again, the iterator over files should be close to the one used in `import_local_directory`.
https://github.com/neondatabase/neon/pull/1925 - This pr implements the following API:
https://github.com/neondatabase/neon/blob/43d1531e66e46768963dbcedd56a7b47314afe0b/pageserver/src/page_service.rs#L933-L934

- [x] #1980

- [x] https://github.com/neondatabase/neon/issues/2020

- [x] https://github.com/neondatabase/cloud/issues/897

- [ ] https://github.com/neondatabase/neon/issues/2097

That seems to be enough to handle relocation manually.

Follow ups:

- Import can be used as an alternative to making `initdb` on the pageserver. If one day we will support custom settings in `initdb` we can make it near compute and feed resulting files into pageserver.
- This epic describes manual relocation, but all that process is quite to S3-based relocation, so I think we can make it to be an option in usual rebalancing, so that tenant movement can be done via S3 or via direct communications between pageservers (and in this case receiving pageserver can call start_backup/stop_backup by himself)
- Create a corresponding operation in the console

**Comment by kelvich** [comment]
> These options are not equal. With "basebackup" solution we lose all the history.

Right. We can make it if we want:

Option 1. Do back up at the oldest possible LSN; load WALs from S3; Pageserver 2 will load that WAL and regenerate history.

Option 2. Just do the backup and wait PITR time before deleting the old pageserver. With that setup we will know that the new pageserver has new data.

**Comment by lubennikovaav** [comment]
>Implement something like per-tenant start_backup/stop_backup in the pageserver. To be able to import physical backup we need to be sure that the safekeeper has the necessary WAL. We can delay sending s3_consistent_lsn from the pageserver to achieve that. start_backup starts that delay, stop_backup stops.

It won't if we take a backup at some moment in the past and the WAL is already offloaded.

@LizardWizzard , is it difficult to implement loading WAL from S3? 
We can even download it directly to pageserver, until it catches up with what safekeepers have.

**Comment by lubennikovaav** [comment]
TODO: clarify API for tenant import

**Comment by LizardWizzard** [comment]
It shouldnt be too hard to create a binary that downloads all the wal from s3. We have needed abstractions in libs/remote_storage. Let me know if you have any questions

**Comment by petuhovskiy** [comment]
IIRC, we still haven't enabled S3 offloading on **production** safekeeepers, so all WAL is stored on the safekeepers disks. That means that we can query something like `START REPLICATION 0/1696B50` on any safekeeper and it will stream WAL from the beginning of the timeline.

And also it's very easy to implement S3 WAL dynamic downloading on safekeepers, so that `START REPLICATION` will always work, even if WAL was offloaded to S3.

**Comment by kelvich** [comment]
With this thing, we can move tenants on staging out of the outdated pageserver. I think it is okay to lose history for this operation. We anyway do not allow branching or cluster reset so it wouldn't have any visible effect.

**Comment by lubennikovaav** [comment]
I am looking at the safekeepers' WAL offloading code (release branch) and I am confused.
https://github.com/neondatabase/neon/blob/f88fe021/safekeeper/src/safekeeper.rs#L937

Why does `oldest_segno` is Lsn::MAX when S3 is disabled?
Was it a bug? I don't see this code in the main branch anymore
