### ISSUE TITLE
Epic: expand branching tests

### ISSUE THREAD

**Issue by stepashka** [neondatabase/neon#1899]
- create test for branching with GC
  + [x] https://github.com/neondatabase/neon/pull/1484
  + [x] branch of branch of branch of (...) tests (https://github.com/neondatabase/neon/pull/1569)
- branch performance tests
  + [x] branch creation performance tests: https://github.com/neondatabase/neon/pull/2101
  + [x] https://github.com/neondatabase/neon/issues/1901
