### ISSUE TITLE
Epic: implement disk size limits per tenant

### ISSUE THREAD

**Issue by stepashka** [neondatabase/neon#1902]
DRAFT

we're already limiting disk size limit per timeline ('branch')
as part of this task we also need to define a global limit on overall tenant (project) size
disk size usage per project (tenant) = sum of disk size usages of all branches inside the project (timelines)

**Comment by kelvich** [comment]
@kelvich to provide proposal about physical sizes

**Comment by aome510** [comment]
> Implementation steps:
> 
> - [x] make timeline_detail endpoint return sum of all file sizes inside timeline directory
> - [x] add a metric with the same value, it can be updated from gc thread for example
> - [x] add tenant physical size to tenant status endpoint
> - [ ] add corresponding metrics
> - [ ] #1218

Copied from the list of action items in the issue desc, 
> add corresponding metrics

I guess this is referred to metric for tenant's physical size, which is the sum of timeline's physical size. We do have a metric for single timeline's physical size: `pageserver_current_physical_size{tenant_id="...",timeline_id="..."} ...`. I think `prometheus` should provide a way to create a metric as a summation of `pageserver_current_physical_size` with a specific `tenant_id`. This way, we don't need to implement a separate metric for tenant's physical size.

Regarding #1218, I'm not so sure about the status of this issue. We do have APIs to report logical size for pageserver and with #2126 and #2173 added, we should also have metrics/APIs to report physical size. Is it safe to mark that issue as completed?

About the next steps, a possible list of action items:
- [ ] update console codes to display the tenant/timeline's physical size
- [ ] determine the tenant's physical size limit and add monitoring to notify users about potential limit excess

cc @kelvich @stepashka @stepashka

**Comment by stepashka** [comment]
@ololobus , i've heard that we have the new APIs now!
can we expose this data in the console admin?

**Comment by ololobus** [comment]
> i've heard that we have the new APIs now!
> can we expose this data in the console admin?

If you mean the timeline physical size, then yes, we can add it on the project page. Feel free to create an issue in the `cloud` repo and put in on me. I can either do it on my own, or wait for someone's else capacity. Also sounds like a good first issue to do

**Comment by stepashka** [comment]
I've added the item:

- [ ] add timeline logical size prometheus metrics

I will create an issue for the console team for adding the size metric there

**Comment by stepashka** [comment]
@kelvich  is going to write up a proposal for tracking some other size-related metrics
among the ideas were

- track the PITR-data size for each timeline
- track the physical size excluding the PITR data for each timeline (how much space would be used if PITR is tuned to 0)

**Comment by stepashka** [comment]
> We do have a metric for single timeline's physical size: `pageserver_current_physical_size{tenant_id="...",timeline_id="..."} ...`. I think `prometheus` should provide a way to create a metric as a summation of `pageserver_current_physical_size` with a specific `tenant_id`. This way, we don't need to implement a separate metric for tenant's physical size.

we can calculate the tenant size outside pageserver IF sizes of all of the existing tenant timelines are reported by the pageserver (or not reported) simultaneously (in the metrics endpoint and pageserver API). are they, @hlinnaka ?
(otherwize the sum will not be representing the actual tenant size at any specific time)

**Comment by hlinnaka** [comment]
>  add corresponding metrics

What does this mean? Can we close this?
