### ISSUE TITLE
Epic: replace etcd with custom grpc based broker

### ISSUE THREAD

**Issue by arssher** [neondatabase/neon#2394]
## Motivation

Custom broker would be much more scalable: https://neondb.slack.com/archives/C036U0GRMRB/p1661011605069469

## DoD

etcd is replaced, all current tests pass.

## Tasks
- [x] [publish the RFC](https://github.com/neondatabase/neon/pull/2466)
- [x] Add routing to the prototype https://github.com/arssher/tonic-bench
- [x] Replace s3 offloader election in safekeepers 
- [x] Add binary https://github.com/neondatabase/neon/pull/2829
- [x] Write helm chart for it https://github.com/neondatabase/helm-charts/pull/15
- [x] Deploy it https://github.com/neondatabase/neon/pull/2922
- [x] Replace etcd in cloud repo tests https://github.com/neondatabase/cloud/pull/3058
- [x] Actually replace https://github.com/neondatabase/neon/pull/2733

**Comment by stepashka** [comment]
https://observer.zenith.tech/d/kcUnPx37z/etcd?orgId=1&refresh=1m — we should provide a replacement for this too :)

**Comment by arssher** [comment]
pr https://github.com/neondatabase/neon/pull/2733
