### ISSUE TITLE
Epic: GC deleted timelines & tenants in S3

### ISSUE THREAD

**Issue by stepashka** [neondatabase/neon#2427]
## Motivation

Currently we do not delete data from s3 when we delete projects

## DoD

Nothing is left in s3 for a deleted project for both safekeepers and pageservers

There shouldnt be lost tenants/timelines that were attempted to be deleted but due to delete failure some part of the data still left in s3. Service restart during delete may lead to such situations

## Implementation ideas

Delete should be retriable after failures. If something went wrong service should be able to perform next attempt and eventually finish the delete operation. This can be achieved in several ways:
* with some tombstone file, e g on delete request we create empty file in timeline or tenant directory called `deleted` if we see such file on restart it means that delete task needs to be scheduled
* Introducing `tenant.json` as described in the [RFC](https://github.com/neondatabase/neon/pull/2239)

```[tasklist]
### Tasks
- [ ] https://github.com/neondatabase/neon/issues/3889
- [ ] https://github.com/neondatabase/neon/issues/6332
```

## Other related tasks and Epics

I'm not sure whether it should be included here or not, we can possibly have weird scenario when `index_part.json` doesnt match actual picture in s3. E g there is a non existing file mentioned in the list. Cleaning this up/alerting can be also called GC but I believe its a different task

```[tasklist]
### Tasks
- [ ] https://github.com/neondatabase/neon/issues/2670
```

**Comment by SomeoneToIgnore** [comment]
There has to be something above pageserver and safekeepers that does the GC: there's at least n * 10^5 projects in S3 that could potentially be removed, because the project is deleted in the console: https://github.com/neondatabase/neon/pull/3623

Due to that, it seems more preferable to avoid any extra S3 removal code to pageservers or safekeepers: this "something above pageserver and safekeepers" could take care of the removal.

Seems like a task for https://github.com/neondatabase/neon/issues/2606 ?
It's not proven, but it might GC files based on https://github.com/neondatabase/neon/issues/2606#issuecomment-1431813066
The consistency checks could take a while, so not entirely clear how scalable the approach is — yet, cold storage might not need a fast cleanup, as long as it eventually happens when required.

**Comment by shanyp** [comment]
@arssher @petuhovskiy 

> Delete safekeeper data from s3 when project is deleted

Is there an issue with it already on your plate?

**Comment by petuhovskiy** [comment]
> Is there an issue with it already on your plate?

No, we don't have a separate issue for that. The best I could find is the last subtask in https://github.com/neondatabase/cloud/issues/1925, but that issue is mostly outdated.

Is S3 GC already implemented for pageserver data? If so, we can look at it, maybe it's possible to just add safekeeper S3 path to the same GC script.

**Comment by shanyp** [comment]
> Is S3 GC already implemented for pageserver data? If so, we can look at it, maybe it's possible to just add safekeeper S3 path to the same GC script.

Yes, we have two methods for it:
* When a timeline/tenant is being deleted (https://github.com/orgs/neondatabase/projects/33)
* S3 Scrubber that can from time to time to make sure we don't leak (https://github.com/neondatabase/s3-scrubber)

I think similar would be needed for safekeeprs

**Comment by LizardWizzard** [comment]
Update:

Mostly done for pageserver part. See https://github.com/orgs/neondatabase/projects/33/views/1. After merging https://github.com/neondatabase/cloud/pull/6369 there are only small follow ups that close remaining gaps

**Comment by shanyp** [comment]
@arssher @petuhovskiy removed the pageserver label as @LizardWizzard finished the major pageserver part

**Comment by petuhovskiy** [comment]
This issue is probably can be closed because https://github.com/neondatabase/neon/issues/6332 is implemented
