### ISSUE TITLE
Epic: Prefetching cleanup

### ISSUE THREAD

**Issue by hlinnaka** [neondatabase/neon#2544]
## Motivation

Since commit f44afbaf62efb2910cefb671457fe60ada9163d5, we have prefetching to speed up sequential scans. It seems to be working pretty well in the benchmarks on captest environment, reducing the pgbench -i time from about 20 mins to 10 mins.

The implementation needs some cleanup, however:

## Tasks

- [x] The new PrefetchBuffer calls done differently than existing PrefetchBuffer calls. The new calls reset the prefetch queue on every call, and issue a whole new set of PrefetchBuffer() calls. Because of that, we do a lot more PrefetchBuffer() calls than needed in those codepaths, and on the other hand, the existing Postgres PrefetchBuffer() calls are not doing prefetching very effectively. For example, in ANALYZE. Let's also add a benchmark for ANALYZE

- [x] The new GUC is called `enable_seqscan_prefetch`. That's a bad name, because all other `enable_*` GUCs affect the planner, while this affects the executor. Should rely on existing `effective_io_concurrency` and `maintenance_io_concurrency` GUCs for the amount of prefetching to do (instead of `seqscan_prefetch_buffers`) and perhaps one extra `neon.seqscan_prefetch` GUC or something like that as a boolean switch to turn it on/off; #2876 

- [ ] Add prefetching to index methods' vacuum tasks to reduce the perceived latency of page requests.

- [ ] Once we're happy with it, enable it by default

**Comment by knizhnik** [comment]
I know that @MMeent is working on this issue.
But as far as I need fast solution of the problem to perform Ketteq
 experiments, I have created PR https://github.com/neondatabase/neon/pull/2634
which solves the problem with redundant calls of `PrefetcBuffer`.

**Comment by vadim2404** [comment]
@MMeent, should it be closed in favor of your merged PR?
