### ISSUE TITLE
Epic: WAL restore checks

### ISSUE THREAD

**Issue by kelvich** [neondatabase/neon#2605]
## Motivation

We store WAL on the S3 but do not check that the restore procedure works properly. There is a test in https://github.com/neondatabase/neon/blob/main/test_runner/regress/test_wal_restore.py, but `initdb` can change its resulting `first_lsn` depending on the environment and minor version.

## DoD

We have automation that periodically checks some timelines in some projects. The exact form of this automation is to be decided when we have scripts to reliably restore a single branch. 

## Implementation ideas

- [ ] Create timeline and import timeline should save the original data directory and upload it to S3
  That should be enough to fight different `start_lsn`'s after initdb

- [ ] k8s job to restore the database from WAL on a single project

  * restore a cluster from WAL on the local disk
  * run pg_dump on it
  * run pg_dump on the read-only node on the same LSN connected to the pageserver (https://github.com/neondatabase/cloud/wiki/Storage-format-migration)
  * dumps should be equal

- [ ] support non-root branches
  
  Branches do start at arbitrary LSN, and the initial part of the first WAL segment in this branch (with LSN < branch_start) is zeroed out. We can glue together first WAL segment with the parent WAL segment in a similar fashion as for `initdb`-restore: https://github.com/neondatabase/neon/blob/main/libs/utils/scripts/restore_from_wal.sh#L20

- [ ] schedule this job on all of the projects
  
  We must consider the number of current in-flight jobs to avoid overloading storage.

- [ ] Truncate old WAL if the previous step was successful
  
  Taking branching into account, it is tricky to say which WAL is safe to delete. I think we can leave this out of the scope and return to it when S3 WAL size would be problematic (and even then could be okay with some partial solutions, e.g. trim only single-branch projects).

## Other related tasks and Epics
- https://github.com/neondatabase/neon/issues/2592

**Comment by kelvich** [comment]
cc @lubennikovaav @hlinnaka @SomeoneToIgnore

**Comment by SomeoneToIgnore** [comment]
We also have a restoration instruction that can be helpful: https://github.com/neondatabase/cloud/wiki/Recovery-from-WAL

**Comment by stepashka** [comment]
@arpad-m , @shanyp , this is an older Epic about something,. i believe the storage team is working on now.
does it make sense to keep this epic? does it capture and work that you have not planned, but is necessary?

let me know, perhaps we close this as dup of the issues you're working on

**Comment by arpad-m** [comment]
@stepashka from my POV it's a follow-up of #5282: that issue is about implementing a mechanism, this issue is about testing that mechanism. We can keep it as two epics.

**Comment by stepashka** [comment]
@arpad-m ok, will keep both!
would the storage team work on this issue or someone else?

cc @shanyp

**Comment by arpad-m** [comment]
I think we are already tracking this internally for the storage team in the OKRs. At least it was part of the proposed list we worked on in the storage offsite. I would say it's assigned to me.

**Comment by jcsp** [comment]
WAL restore has its own tests
