### ISSUE TITLE
Epic: storage consumption tracking

### ISSUE THREAD

**Issue by kelvich** [neondatabase/neon#2941]
## Motivation

Storage part of https://github.com/neondatabase/neon/blob/metering_rfc/docs/rfcs/021-metering.md (comments are also important).

## DoD

Pageserver periodically sends it consumption events to the console. So far we've discussed the following metrics:

* written size
* real tenant size
* s3 tenant size
* number of s3 api calls
* synthetic size

Each of that metrics should have prometheus endpoint as well

## Implementation ideas

Seems that the proposed functionality could be implemented with two background workers (threads / actors / ...) per pageserver.

a) Consumption sender

Periodically (~1min) wakes up and walks over all active tenants to send consumption data to the console. Here it is important to avoid always sending info about all of the tenants. One way to do that is to send info about all tenants on the start, cache values, and then filter out unchanged ones. Other approaches are possible too. For each tenant consumption sender can just take values of corresponding prometheus metrics. All accumulated events about all the tenants can be sent using one query.

b) Synthetic size worker

Synthetic size [*] stands out a bit, as it is expensive to calculate. We can create another background thread which will walk around tenant one by one (potentially with some parallelism) and will update prometheus metric that can be used by the consumption sender. Would be good to skip tenants that did not receive any changes since the last calculation (e.g. if latest_lsn did not change).

[*] https://github.com/neondatabase/neon/pull/2884#discussion_r1029261929

## Tasks
- [x] Implement and deploy consumption sender for the existing metrics (written size, real tenant size, s3 tenant size) https://github.com/neondatabase/neon/pull/3187
- [x] Implement synthetic size worker
https://github.com/neondatabase/neon/pull/3123
- [ ] Add S3 api calls metric
- [x] Write a page in `/docs` about it to standardize naming 
- [ ] https://github.com/neondatabase/neon/issues/2848

**Comment by kelvich** [comment]
@hlinnaka @LizardWizzard @SomeoneToIgnore @koivunej does this plan with background workers sounds reasonable?

**Comment by koivunej** [comment]
Apologies, somehow I have gotten a lot of notifications and am slow to go through them :)

> with background workers

Note that with the tenant size there's already two limiting factors for parallelism and concurrency:
- global setting for how many size calculations can the tenant size run at once: https://github.com/neondatabase/neon/blob/main/pageserver/src/config.rs#L143
- per tenant lock: https://github.com/neondatabase/neon/blob/main/pageserver/src/tenant.rs#L140

> We can create another background thread which will walk around tenant one by one (potentially with some parallelism) and will update prometheus metric that can be used by the consumption sender

The functionality is exposed in [an async function](https://github.com/neondatabase/neon/blob/main/pageserver/src/tenant.rs#L2255), so adding a periodic background task would sound most applicable.

**Comment by antonyc** [comment]
Can we please enable and rollout for both [us-* regions](https://github.com/neondatabase/neon/tree/main/.github/ansible) [same as we did for staging?](https://github.com/neondatabase/neon/pull/3187)

**Comment by lubennikovaav** [comment]
This Epic is finished. Consumption metrics are available on both staging and prod.
Documentation is in [docs/consumption_metrics.md ](https://github.com/neondatabase/neon/blob/main/docs/consumption_metrics.md)

Follow-ups will be done in separate issues.
