### ISSUE TITLE
Epic: User-accessible neon extension metrics

### ISSUE THREAD

**Issue by MMeent** [neondatabase/neon#2994]
## Motivation

We have a lot of data inside the Neon storage system, and quite a lot of metadata too. We should expose these metrics in a user-friendly manner, preferably to PostgreSQL sessions, so that debugging of performance issues is improved.

## DoD

Users can access performance metrics about their session and the connection to Neon Storage.

## Implementation ideas

Expose various benign statistics to the user, such as IO counts, IO timings, prefetch hit rate, LastWrittenLsn data, replication delay, etc.

## Tasks

- [ ] Create a new, trusted extension (`neon_tools` ?)
- [ ] Expose prefetch statistics through this new extension
- [ ] Expose current prefetch buffer metadata
- [ ] Expose LastWrittenLsn state

## Other related tasks and Epics
- https://github.com/neondatabase/neon/pull/2876#discussion_r1032626185

**Comment by knizhnik** [comment]
Ideally prefetch statistic (hits/misses) should be reported by `explain analyze`.
It seems to be non trivial, because prefetch in implemented in Neon extension.
But we can add hook for custom extension of EXPLAIN data.

**Comment by vadim2404** [comment]
It seems that @knizhnik has already extended `explain` with `prefetch` option. 

Someone asked about access to a slow query log in order to be ready to react.
