### ISSUE TITLE
Tenant config file update isn't durable which may result in empty/corrupted state

### ISSUE THREAD

**Issue by shanyp** [neondatabase/neon#3062]
## Steps to reproduce
Create and run a server instance
Update a tenant configuration
Crash the server while it first truncates the tenant configuration file or updates the file

## Expected result
The tenant config file should have the previous configuration

## Actual result
the tenant config file is empty/corrupted

## Logs, links

Suggested fix In persist_tenant_config function:

```[tasklist]
### Tasks
- [ ] create the config file in a config_tmp file
- [ ] flush it
- [ ] rename it to config
- [ ] if all succeeds return OK() 
```

**Comment by koivunej** [comment]
@shanyp renamed this to be about tenant config instead of page server config file, because we don't have AFAIK a way to update pageserver config file via the api.

I did consider fixing this while #3446 but it seemed too large at first, however it's quite trivial. In addition to steps above under:

> In persist_tenant_config function:

I think we'll additionally need:

- require taking a tenant specific, hopefully async mutex in http
- tempfile cleanup as part of tenant load
    - could be left as well, was trying to anticipate review comments

**Comment by LizardWizzard** [comment]
> because we don't have AFAIK a way to update pageserver config file via the api.

Yep, thats correct

> require taking a tenant specific, hopefully async mutex in http

Hmm, I wonder if locking inside fs is enough. E g if two mkdir calls will be racing only one of them should succeed

**Comment by shanyp** [comment]
> tempfile cleanup as part of tenant load
> * could be left as well, was trying to anticipate review comments
Why not leave it in tmpfs and it will be deleted eventually ?

**Comment by jcsp** [comment]
`persist_tenant_config_at` uses `crashsafe_overwrite` in the latest code, so I think this is no longer an issue.
