### ISSUE TITLE
Epic: shmempipe for WAL redo process communication

### ISSUE THREAD

**Issue by hlinnaka** [neondatabase/neon#3184]
## Motivation

Whenever the pageserver needs to replay WAL records, it sends the records to the WAL redo process over a pipe, and the WAL redo process responds over another pipe. The communication over those pipes adds quite a lot of latency. Let's replace the pipes with shared memory, which is faster.

## DoD

WAL redo latency is reduced.

## Implementation

The idea is to mmap() a piece of shared memory between the pageserver process and the WAL redo process. In that shared memory segment, establish queues for the requests and responses. A ring buffer is the usual way to implement such queues.

In addition to the shared memory segment, there is a notification mechanism to notify the other process that there is a request or response waiting in the queue. We can continue using a pipe for that: just send a single byte to wake up the other process. Or eventfd(2) or futex(2), but those are Linux-specific. Perhaps use eventfd(2) with fallback implementation with regular pipe for oher platforms. Inter-process notification over any of those mechanisms adds quite a lot of latency, so it is best to busy-wait for a while, and only go to sleep waiting for the notifcation after that.

Note that it is not safe to use pthread_mutexes or condition variables for the inter-process notification for security reasons. The pageserver cannot assume that the memory holding the mutex has valid contents.

## Requirements

- [ ] Safety: The WAL redo process is untrusted. It can corrupt and write any malicious contents to the shared memory segment. The queue implementation in the pageserver cannot trust the contents of the shared memory.
- [ ] Testability & Reviewability: To convince ourselves that we don't introduce any undefined behaviour or vulnerabilities in the pageserver, the pageserver code that accesses the shared memory should be as small and isolated as possible. A separate crate would be good, with clear, safe interface, and clear invariants inside that can be inspected and tested.
- [ ] Performance: Microbenchmark results with Proof-of-Concept [here](https://github.com/neondatabase/neon/pull/2947#issuecomment-1335344194). Should achieve those latencies.
- [ ] Handle errors gracefully. If the WAL redo process crashes, or writes garbage, or is stuck and never reads requests , the pageserver should notice, kill the process and restart it. 

## Related work

Initial Proof-of-Concept by Konstantin: https://github.com/neondatabase/neon/pull/2947
Current work-in-progress PR: https://github.com/neondatabase/neon/pull/3163
Earlier discussion on WAL redo speed: https://github.com/neondatabase/neon/issues/1339

**Comment by knizhnik** [comment]
The portable alternative to eventfd/futex is just pipe or Unix socket with `select`. Pipe seems to be better solution, because we need not worry about ports. And it is used in Postgres latches implementation. The main difference is that in postgres pipe descriptors are inherited by fork. And here we need to use mechanism to send file descriptor to another process. It is also terrible non-portable, but at least it is supported by Linux, FreeBSD, MacOS  and may be by some other Unix dialects.

If you want, I can try to implement such synchronization primitive.
But as far as we are not going to run Neon on something other than Linux platforms (are we?) then we can use shmem pipe implementation with eventfd for Linux and current stdio pipe implementation for other platforms (like MacOS). But it requires significant code duplication (we will need to maintain two different implementation of communication between pageserver and walredo) and this is why I want to avoid it as much as possible.

**Comment by hlinnaka** [comment]
> The portable alternative to eventfd/futex is just pipe or Unix socket with `select`. Pipe seems to be better solution, because we need not worry about ports. And it is used in Postgres latches implementation. The main difference is that in postgres pipe descriptors are inherited by fork. And here we need to use mechanism to send file descriptor to another process. It is also terrible non-portable, but at least it is supported by Linux, FreeBSD, MacOS and may be by some other Unix dialects.

We can pass down the file descriptor through fork() here as well. In fact I think that would be a better way to pass down the file descriptor for the "shared memory file" too, instead of passing down the filename and re-opening it in the child process. It's a little tricky to get right when forking from a multi-threaded process, but still possible.

> If you want, I can try to implement such synchronization primitive. But as far as we are not going to run Neon on something other than Linux platforms (are we?) then we can use shmem pipe implementation with eventfd for Linux and current stdio pipe implementation for other platforms (like MacOS). But it requires significant code duplication (we will need to maintain two different implementation of communication between pageserver and walredo) and this is why I want to avoid it as much as possible.

I don't think it's a lot of duplication. eventfd and a pipe are very similar: you send() to notify the other process, and read() to wait for the signal. I think you just need a small #ifdef or `#[cfg(target_os = "linux")]` where the file descriptor is created.

**Comment by knizhnik** [comment]
As far as I understand there are 4 channels and this is why 23GB/sec need to be multiplied by 4 which gives 96GB/sec):
https://www.google.com/search?channel=fs&client=ubuntu&q=DDR4+2933+bandwidth
Still seems to be small percent of total time.

I already wrote that the main my argument against this proposal is that walredo process is not using shared buffers: it use local buffer to avoid sync. overhead. It is also not so large - I didn't notice big performance improvement after this optimization. But I am not sure that copying 8kb is significantly less expensive than synchronization cost.

**Comment by knizhnik** [comment]
Such protocol will eliminate (or at least complicate) batching of walredo requests processing which seems to be the most efficient way now to improve performance. Please notice that all this walredo activity started with attempt to break request-response cycle in pageserver-walredo process communication, i.e. make walredo processing more asynchronous.
I want to point to Slack conversation: https://neondb.slack.com/archives/C04BLQ4LW7K/p1668784750319719
Please notice that replaying walredo from file (maximal possible async level) takes about 1 second for Q1. And with shmempipe current record is 11.5 seconds. So memory bandwidth is really seems to be not a bottleneck.

**Comment by knizhnik** [comment]
> Why would that be the case? You can have up to N=number-of-buffers WAL redo requests in the pipeline. It won't be much more complicated than the current multiple-producer single-consumer pipeline.

walredoproc.c:174:

```
	/*
	 * WAL redo does not need a large number of buffers. And speed of
	 * DropRelFileNodeAllLocalBuffers() is proportional to the number of
	 * buffers. So let's keep it small (default value is 1024)
	 */
	num_temp_buffers = 4;
```

Yes, it can be increased. But why?

> How does that "replaying WALRedo from file" work? Do you have a reference? Because my earlier calculation shows that 0.55s of those 1s could potentially be attributed to memory copies, which is fairly significant. That does indeed mean that there are still 10.5 seconds of other overhead, but reducing those 0.5 should not be ignored just because it isn't the biggest and most obvious contributor to time spent.

It was discusses in Slack thread. I just dump in the file al walredo requests which was sent to walredo process by pageserver during Q1 execution. And then just put this file as stdin for walredo process.

I do not think that we should optimize something which has no significant impact on performance.
It is really bd practice. Complication of code leads to errors. We have much more complex prefetch mechanism now. And we still have SIGSEGVs caused by prefetch. Fortunately that no of our users faced with this problem yet. Now you are rewriting last written LSN cache and it will become also several times more complex. And once again - there seems to be no advantages in performance, may be even some slowdown  caused by more expensive eviction algorithm. "Sharing" page cache between pageserver and walredo process also significantly  complicate pageserver-walredo communication. And take in account that walredo process is not trusted, so it is can perform any invalid operation and try to crash pageserver... Even with shmempipe we faced with a lot of issues. And here I expect even more pit falls...

**Comment by koivunej** [comment]
Proposing a path for #3163 to become ready and open questions in this message. Apologies on the use of footnotes :)

### Current state of #3163

<details><summary>Non-brief description of the current state in #3163.</summary>

Current implementation works similar to #2947 but assuming not every reader is familiar with either, I'll recap it here. The two processes share a region of memory. I call the pageserver side "owner" and the `pgxn/walredo/walredoproc.c` the "worker". The shared memory replaces standard input and output (stdin for requests, stdout for responses).

Single thread requesting and worker responding looks like:

1. owner writes the full request to the first SPSC lockless queue (see docs.rs/ringbuf)
2. owner wakes up the worker using the first eventfd semaphore (see `man eventfd`)
3. worker reads the full request, begins processing it message by message
4. owner sleeps on second eventfd semaphore
5. worker writes the full response to the second SPSC lockless queue
6. worker wakes up the owner using the second eventfd semaphore
7. owner reads the response, and is complete

For OLAP[^oltp_and_olap] situations the implementation supports owner side pipelining the requests, and each requesting *thread*  waiting it's turn to read the response. Threads are parked and woken up in order or by being lucky and not having to park at all.

Both lockless queues are guarded by `std::sync::Mutex` on the *owner* side. The `ringbuf` crate handles sufficient atomic operations to ensure visibility between the processes.
</details>

### Proposed path forward

0. OLTP[^oltp_and_olap] performance
    - this has been a major source of frustration for me since all of the solutions seem slower than #2947, however this is balanced by the fact that there is less spinning, so most likely this is now well balanced
8. clean up all pthread primitives and unused code
    - atomics will most likely be enough unless I forget something
9. get miri tests working again
    - miri reports if there are any known illegal rust things done
    - will require shimming for eventfd usage in single process
10. "vendor" the ringbuffer crate
    - with upstreamable `try_` operations which only do checked operations
    - kill child on miscalculated head/tail
11. cleanup pageserver/src/walredo.rs
    - switch to tokio task waiting for the sub process to die while pumping the `stderr` messages
12. implement the "restart on child death" for the `OwnedRequester::request_response`
    - process exit and any miscalculated head/tail will need to trigger this
    - all phases of writing request, parking, reading response need to be "restartable"
    - all threads calling `OwnedRequester::request_response` will need to agree on the restart before anyone can actually restart
    - process needs to be restarted as well

Later on, on following PRs:

13. asyncify the `OwnedRequester::request_response` by making the eventfd, thread parking, locking async
    - the "restart on child death" will be semi-tricky to implement with cancellable futures
    - to support `std::mem::forget` futures it will be very difficult [^forgetful]

Open questions:
- how to do non-linux eventfd? Alternatives I can see:
  - instead of one fd, have two pipes reading and writing one byte at time
  - keeping the old poll based implementation around for macos

[^oltp_and_olap]: There are `pageserver/bench/bench_walredo.rs` where `short/short/1` and `medium/medium/1` are assumed to show the OLTP case and the OLAP case is shown by `/N` where `N > 1`. The number `N` signifies how many threads are concurrently redoing a page. The benchmarks go as high up as N=16, which hasn't been observed in the wild.

[^forgetful]: Supporting forgettable futures will be very difficult and might come down to _if_ we want to support them or not. Downside of "not supporting" will be the lingering possibility of facing a very mysterious rare debugging case once someone introduces a code path which might leak a rare walredo future.
   The problem of forgotten futures is that we will have no knowledge of the forgetting taking place, so when it's time to read the response, nothing will happen when a wakeup is sent for the task whose turn it is to read the response, so we will deadlock.
   The only design I can see supporting `std::mem::forget` the futures is #2875, which might become more viable as we continue to asyncify the core #3228.

**Comment by hlinnaka** [comment]
> ### Proposed path forward

+1 on this plan

>     0. OLTP[1](#user-content-fn-oltp_and_olap-4559541959f73e1e04d35288acdae97f) performance
>        
>        * this has been a major source of frustration for me since all of the solutions seem slower than [Shmem pipe #2947](https://github.com/neondatabase/neon/pull/2947), however this is balanced by the fact that there is less spinning, so most likely this is now well balanced

Right, it's always a tradeoff to decide how long to busy-wait. If you busy-wait for too long, you waste a lot of resources spinning, but without busy-waiting, it takes a few microseconds for notification to come through eventfd.

I spent some time digging into virtualization, qemu, kvm, and virtio a few weeks back. They have the same problem: the guest VM and host VM communicate over a queue in shared memory, but after adding some work to the queue, you need a mechanism to notify the other side. You can use a "vmexit" from the guest VM, which uses eventfd to notify the process in the host that there is something in the queue. Or you can busy-poll. See https://vmsplice.net/~stefan/stefanha-kvm-forum-2017.pdf for a presentation on this. The core idea is that after processing some work, you busy-wait for a few microseconds in case that more work arrives quickly enough, and then sleep.

> Later on, on following PRs:
> 
>     13. asyncify the `OwnedRequester::request_response` by making the eventfd, thread parking, locking async
>         
>         * the "restart on child death" will be semi-tricky to implement with cancellable futures
>         * to support `std::mem::forget` futures it will be very difficult [2](#user-content-fn-forgetful-4559541959f73e1e04d35288acdae97f)

You could do this work on top of https://github.com/neondatabase/neon/pull/3228. It's still under review and will surely change somewhat before merging, but the core change of `TimelineGet::get` to be async is there and shouldn't change much.

**Comment by knizhnik** [comment]
> Right, it's always a tradeoff to decide how long to busy-wait. If you busy-wait for too long, you waste a lot of resources spinning, but without busy-waiting, it takes a few microseconds for notification to come through eventfd.

Atomics and busy wait are efficient if we have some number of requests which can be combined.
This is why shmpipe shows best results for OLAP requests where prefetch or parallel workers can issue multiple requests to walredo. It should be also efficient if there are multiple concurrent OLTP requests.
But if there is only one client issuing OLTP requests (which is expected to be most common case for free tier clients),
then all this ataomics and busy loop can not reduce number of syscalls, because we in any case have to send request to walredo process and wait for it't result. Page reconstruction is not so trivial task (at least copying 8kb in both direction), so that waiting its completion in busy loop may be not so good idea, having negative impact on overall pageserver performance.

**Comment by koivunej** [comment]
Closing the shmempipe_rs (#3163) efforts in favor of a simpler #3368.
