### ISSUE TITLE
Epic: Credential and addresses cache in proxy

### ISSUE THREAD

**Issue by vadim2404** [neondatabase/neon#3332]
- [x] (Top priority) https://github.com/neondatabase/neon/pull/3331
- [x] See if the cache works as intended ([discussion + measurements](https://neondb.slack.com/archives/C04JRCGV8F2/p1675264989906909)), perform additional analysis
- [ ] (Postponed) Implement LRU cache for credentials
