### ISSUE TITLE
Revive code coverage usage in neon repo

### ISSUE THREAD

**Issue by shanyp** [neondatabase/neon#3543]
```[tasklist]
### Tasks
- [x] Add coverage comment to the top of PR (based on the current solution or use  https://github.com/apps/barecheck )
- [x] Coverage upload to some TTL-based storage (S3/..) https://github.com/neondatabase/neon/pull/4256
- [ ] Add to review template to ensure the reviewer tends to coverage as well
- [ ] Enforcement of some level if needed (minimal threshold)
```

**Comment by bayandin** [comment]
> The report isn't pretty (I like them colorized) but that's a separate issue :)
> 
> I think it would be helpful to include the report link in the 'allure' comment. That way, it's in front of dev eyes => people will look at it.
> 
> If it can't be in the same comment, then post a separate comment for coverage, that is auto-updated just like the allure report.
> 
> Once we get the 'coverage change by this PR' reporting that @shanyp asked for above, we can get rid of that comment again.

From https://github.com/neondatabase/neon/pull/4256#pullrequestreview-1430207402
