### ISSUE TITLE
Epic: missing things in the proxy's pg protocol implementation

### ISSUE THREAD

**Issue by funbringer** [neondatabase/neon#3551]
## Motivation

Proxy should support most (if not all) features of postgres' protocol (libpq).

## DoD

- [ ] Pass the test suite https://github.com/jackc/pgx

## Tasks
- [x] https://github.com/neondatabase/neon/issues/1287
- [x] https://github.com/neondatabase/neon/issues/2752

**Comment by funbringer** [comment]
This is nothing new, but the structure of this epic makes more sense.

**Comment by vadim2404** [comment]
Do we have the list of these features?

**Comment by funbringer** [comment]
I'd say this epic is the list. For the time being we have 2 tasks (per bug reports) and a DoD. Should we notice another protocol-related complaint, it ought to end up here.
