### ISSUE TITLE
Epic: reduce storage footprint of walredo process

### ISSUE THREAD

**Issue by LizardWizzard** [neondatabase/neon#3687]
## Motivation

Pageservers can have several thousands of tenants. If each of them has a walredo directory it adds up to several hundreds of gigabytes.

## DoD

We're done with low hanging fruit in this area. Space usage should be reduced.

## Tasks
- [ ] Shutdown walredo process after X minutes of inactivity
- [ ] Removal walredo directory from disk when walredo process is not active
- [ ] Avoid initdb run for walredo process. (See linked thread for more context)  

## Other related tasks and Epics
- https://neondb.slack.com/archives/C033RQ5SPDH/p1677018554516479

**Comment by koivunej** [comment]
Related: #3620

**Comment by LizardWizzard** [comment]
We can upscale this one to include memory usage as well

**Comment by koivunej** [comment]
Maybe keep them separate since #3703 handles most of the space issues (pgdatadir, less allocations), however the ideas on #3620 are perhaps still separate.

**Comment by koivunej** [comment]
Might not need to shutdown walredo process, this is otherwise done by. TODO: link stas pr and close.
