### ISSUE TITLE
Epic: Support `dblink` and `postgres_fdw` extensions

### ISSUE THREAD

**Issue by vadim2404** [neondatabase/neon#3720]
## Motivation

`dblink` and `postgres_fdw` extensions are quite popular in analytical, migration, and sharding use cases. Therefore we need to install them.

## DoD

As a user, I can install these two extensions and use them.

## Tasks
- [x] Ensure that computes use JWT token while communicating with SKs and PSs
- [x] #4704
- [x] Enable network policies that allow traffic only for selected pageserver, safekeepers, proxy, and internet traffic
- [x] Check that you cannot connect to localhost as superuser
- [x] Enable these extensions

## Other related tasks and Epics
- neondatabase/cloud#5745
- https://github.com/neondatabase/neon/issues/5631

**Comment by vmatt** [comment]
Hey, when this can be expected?

**Comment by clarkbw** [comment]
The `postgres_fdw` extension is expected to release this quarter, Q4 2024

**Comment by acervantes23** [comment]
@vadim2404 what is the target ship date for this?

**Comment by vadim2404** [comment]
I'll forward this question to @ololobus

**Comment by ololobus** [comment]
[It's currently set to the Mid-Nov here](https://docs.google.com/spreadsheets/d/1VoeChMSUVkAdWhVmq-BzC9lSJS3vLoPiRjiVKXT9bws/edit?pli=1&gid=0#gid=0), but not sure it's gonna happen. Early Dec is more realistic

**Comment by acervantes23** [comment]
can we keep GH up to date? my assumption is to check issues/epics for the target ship date and no spreadhsheets

**Comment by ololobus** [comment]
This week:

- [ ] @myrrc is working on https://github.com/neondatabase/neon/issues/4704, target opening a PR this week and write/run tests (autoscaling repo?)

**Comment by tristan957** [comment]
I've started working on refactoring the HTTP server in compute_ctl to use Axum as preparatory work for my JWT authentication for said HTTP server.

**Comment by ololobus** [comment]
This week:

- [ ] @myrrc test and pass review on https://github.com/neondatabase/autoscaling/pull/1153
- [ ] Build and test dblink and postgres_fdw extensions

**Comment by myrrc** [comment]
Runner merged, waiting for deployment

**Comment by ololobus** [comment]
This week:

- [ ] @myrrc enable traffic metering on staging
- [ ] @myrrc test dblink and enable

**Comment by acervantes23** [comment]
hey @ololobus will we enable this week?

**Comment by ololobus** [comment]
> hey @ololobus will we enable this week?

Def, not this week because it's Fri evening :) I think that we may target merging the PR next week

**Comment by ololobus** [comment]
This week:

- [ ] @myrrc targets to merge dblink support

**Comment by ololobus** [comment]
Question from @MMeent 

> Re: DBLink:
> Do we have enough protections for that?
> IIRC, we had a local:trust policy (i.e. no password), which is kinda bad when someone tries to connect to localhost with a neon_superuser dbname using e.g. dblink or postgres_fdw.

I.e. how we restrict users from connecting as `cloud_admin`. Heikki, exts should have a protection from that

@myrrc to double-check

**Comment by acervantes23** [comment]
Hows this one looking @ololobus  ?

**Comment by ololobus** [comment]
> Hows this one looking @ololobus ?

We merged traffic metering. @myrrc is testing/investigating some security implications of enabling these extensions. He is now OOO, so I'd expect it within the first 2 weeks of Jan now

**Comment by myrrc** [comment]
This week:
finished dblink test, tweaking fdw test (permissions issue for some fdw functions)

**Comment by myrrc** [comment]
FDW integration has some issues with tests https://github.com/neondatabase/neon/pull/10426#issuecomment-2602831271

**Comment by myrrc** [comment]
Changes addressed, plan to merge fdw without possibility for users to interact with it unless grants given via support
EST today or early tomorrow.

**Comment by myrrc** [comment]
FDW merged
