### ISSUE TITLE
Epic: Support custom extensions

### ISSUE THREAD

**Issue by lubennikovaav** [neondatabase/neon#4269]
## Motivation

There are many extensions in the PostgreSQL ecosystem, and not all extensions are of a quality that we can confidently support them. Additionally, our current extension inclusion mechanism has several problems because we build all extensions into the primary Compute image: We build the extensions every time we build the compute image regardless of whether we actually need to rebuild the image, and the inclusion of these extensions in the image adds a hard dependency on all supported extensions - thus increasing the image size, and with it the time it takes to download that image - increasing first start latency.

## DoD

Users can upload and use custom extensions in neon.

## Tasks
- [x] Extension loading RFC https://github.com/neondatabase/neon/pull/4158
- [x] #4419
- [x] #4493
- [x] #4420
- [x] performance optimization of extensions loading (cold starts)
- [x] add srcript to upload extensions https://github.com/neondatabase/build-custom-extensions

- [x] https://github.com/neondatabase/neon/issues/5019

- [x] INFRA: Allow connections from compute to s3 bucket (was restricted by PR https://github.com/neondatabase/cloud/pull/5890)

- [ ]  Write e2e test for remote extensions https://github.com/neondatabase/cloud/pull/6308

- [x] #5082

## Other related tasks and Epics
-
