### ISSUE TITLE
Epic: Efficient Compaction

### ISSUE THREAD

**Issue by skyzh** [neondatabase/neon#4359]
## Motivation

Compaction can reorganize data and effectively balance the read/write/space amplification. It is hard to do compaction over the current page server engine implementation for multiple reasons:

* no manifest locally. The compaction process will need to automatically remove/add set of files to the engine. It will also need to record some data (i.e., levels, start/end keys) in the manifest. We currently scan the directory to reconstruct the storage engine state, which would cause duplicated layers issue when restarted.
* locks. The storage state is scattered in multiple lock-protected structures whereas there is not single state / snapshot for the engine.
* compaction strategy. The current compaction strategy trades large space amplification for materialized page caching, and once delta layers are flushed from L0 to L1, the data are not reorganized to reduce read amplification. We need to think of a compaction strategy (i.e., leveled compaction) to reduce space amplification for data outside of PiTR and collect delta records of the same page to a single block so as to reduce read amplification. 

## Tasks
- [ ] refactor storage engine to have a single snapshot for the storage state
- [ ] add manifest locally and reconstruct the storage state from manifest
- [ ] implement one compaction strategy and evaluate its effectiveness

## Other related tasks and Epics
-

**Comment by hlinnaka** [comment]
> Compaction can reorganize data and effectively balance the read/write/space amplification. It is hard to do compaction over the current page server engine implementation for multiple reasons:
> 
> * no manifest locally. The compaction process will need to automatically remove/add set of files to the engine. It will also need to record some data (i.e., levels, start/end keys) in the manifest. We currently scan the directory to reconstruct the storage engine state, which would cause duplicated layers issue when restarted.

Hmm, we have the layer map in memory, where we keep track of the files that exist. And we have the index_part.json in S3. I believe we already have all the information you need to make compaction decisions. Or do you need to persist some extra state?

It's a nice property of the current design that it's kind of stateless: the compaction and GC decisions is made based on what files exist, and there is no other persistent state. That gives us flexibility to change the compaction algorithm. It's also quite forgiving if we ever need to manually add or remove files in some disaster recovery scenario, for example.

So I would think twice before adding more persistent state. If we can easily rebuild the state from the set of files that exist, that's a good property.

Another consideration is that in the future, we might have two pageservers digesting the same WAL, and producing layers files that contain the same data. But the files might not be 100% identical, because the flushing and compaction decisions are not fully deterministic. We've talked about this with cross-region replication. You would have a separate pageserver and an S3 bucket on two regions, serving computes on each region. One pageserver would be probably the primary, and would be ultimately responsible for ensuring that all the data is durable, and control compaction and GC. But the other one also needs to have up-to-date data, so it also needs to receive the same WAL stream, and produce layer files on its own. It would not need to have all data available locally, it could also fetch files from the S3 bucket of the other region if needed. But to respond to GetPage requests with a recent LSN, it needs to receive the WAL stream, because the recent data is not available in S3 yet.

That's all still just rough ideas. But the point is that it's good to not rely on having a single persistent state of the engine as whole. If we can deal with overlapping layers files, extra layer files appearing from other pageservers, etc, that's a good property.

> * locks. The storage state is scattered in multiple lock-protected structures whereas there is not single state / snapshot for the engine.

Yeah, this is pretty messy.. The team is experimenting with an actor model for the Timeline. The goal of that is to eliminate much of the locking and make the transitions between timeline states more clear.

Does it matter for compaction in particular?

> * compaction strategy. The current compaction strategy trades large space amplification for materialized page caching, and once delta layers are flushed from L0 to L1, the data are not reorganized to reduce read amplification. We need to think of a compaction strategy (i.e., leveled compaction) to reduce space amplification for data outside of PiTR

+1

> and collect delta records of the same page to a single block so as to reduce read amplification.

I'm not sure I understood this. Do you mean that the delta records should be replayed, to produce one materialized page image to replace the delta records? +1 for that

**Comment by skyzh** [comment]
> we might have two pageservers digesting the same WAL, and producing layers files that contain the same data

> One pageserver would be probably the primary, and would be ultimately responsible for ensuring that all the data is durable, and control compaction and GC

Maintaining LSM tree of the same data in two places is generally unnecessary and costly. My initial thought is that, we can share the LSM state in some kind of meta service. The primary will do the compaction decision and upload everything to S3. The replica node serves as a local cache for the LSM tree, whereas it does not do any compaction, and when there is a read request, it simply download data from S3 to its local cache and serves the data.

The meta service should record the latest LSN that the LSM tree contains. The replica node should read everything in WAL which is > LSMLSN, and everything in LSM that <= LSMLSN.

**Comment by skyzh** [comment]
> Why is it a concern for leveled compaction?

Consider the case where we compact layer 1, 2, 3 to layer 4, 5, 6:

```
Level 2 -- Layer 1
Level 3 -- Layer 2, Layer 3

Level 3 -- Layer 4, Layer 5, Layer 6
```

If the compaction process is not atomic, we might end up with the following LSM structure:

```
Level 2 -- Layer 1
Level 3 -- Layer 2, Layer 3, Layer 4, Layer 5
```

One key constraint of leveled compaction is that levels >= 1 do not have overlapping keys. In this case, level 3 might have overlapping keys (as layer 4 includes part of layer 1, layer 2, and probably layer 3). And we cannot know which file to remove in this case, if we do not record the compaction operation somewhere.

> If one page has millions of WAL records on it, it probably makes sense to generate a few materialize pages of it at different LSNs, even if they would all fall into the same file.

This sounds reasonable. Probably the image creation criteria will be (1) we reach level 3/6 (2) more than x delta records found for the same page during the compaction.

> Another idea is that the compute could write some extra full-page images to the WAL, based on some heuristic

This also makes sense, for example, we can record access history in the materialized page cache and write something back to the LSM tree in some cases.

> I don't think we need a new metadata service. We already have the index_part.json file in S3, which lists all the files, and the latest LSN that is durable in S3. I believe that's all the metadata we need.

Yes I agree.

**Comment by jcsp** [comment]
Ongoing compaction worked is tracked in:
- https://github.com/neondatabase/neon/issues/6768
