### ISSUE TITLE
Epic: wait for the endpoint to be available in proxy

### ISSUE THREAD

**Issue by kelvich** [neondatabase/neon#4598]
## Motivation

During the compute wake-up, the control plane returns a compute address that is not always immediately available for connection. We attempted to rectify this by conducting more connectivity checks on the control plane side. However, both NodePort and ClusterIP are just rules in local iptables, which are maintained by the node-local kube-proxy. So even when the control plane can reach the compute through sni_proxy, there's no guarantee that a user connection through the proxy will be able to reach the compute. This is due to the fact that sni_proxy and proxy could be on different k8s nodes, and an iptables rule could be available on one and not on the other node. Moreover, with ClusterIP, we use a DNS name to connect to compute immediately after pod creation, and sometimes the domain name resolution fails for a few seconds.

## Implementation Ideas

As a mitigation, we might accept the fact that k8s networking is eventually consistent and retry connection attempts in the proxy. We already retry the connection once in case we have stale destination host information in the cache. It still makes sense to retry right after a failed connection attempt, but after that, we might retry connection attempts every 100ms. We need to be cautious about which connection errors we retry and which we don't. For example, we should not retry wrong passwords, etc. I believe we should have an explicit list of errors that we retry, such as: couldn't connect, time out, DNS resolution error.

With this change, we'll shift some of the waiting logic to the proxy side. Therefore, we should measure and log the end-to-end connection wait time. The user-proxy geographical distance will influence this, so it makes sense to track how long it takes for the client to send a reply during authentication to get a sense of ping time, and subtract ping_time * N from the total latency (we can do this as a follow-up so as not to block the initial roll-out).

## Tasks
- [x] Implement and merge the waiting logic
- [ ] #6923
- [ ] Conduct a load / wake-up test on staging
- [ ] Implement and merge ping and latency measurement logic
- [ ] #6924

**Comment by kelvich** [comment]
Dashboard with errors: https://neonprod.grafana.net/d/fefbf47f-a8a6-4201-8472-98765f1654de/proxy-error-classification

**Comment by stradig** [comment]
Discussed this and it is done. Create some followup tasks.
