### ISSUE TITLE
Epic: 100ms start-up time

### ISSUE THREAD

**Issue by vadim2404** [neondatabase/neon#4695]
## Motivation
We need to reduce compute start-up time. It frustrates our customers when they need to wait

## Tasks
- [ ] Decrease Postgres start-up time to 20-50ms
- [ ] Decrease sync-safekeepers time from 60ms to 0
- [ ] Compress basebackup size from 16Mb to 20Kb

## Other related tasks and Epics
-

**Comment by bojanserafimov** [comment]
https://github.com/neondatabase/cloud/issues/5315 exists
