### ISSUE TITLE
Epic: convert remaining IO stack for `Timeline::get` to `async fn`

### ISSUE THREAD

**Issue by problame** [neondatabase/neon#4743]
# Background

The async `value_get_reconstruct_data` project ([GH project](https://github.com/orgs/neondatabase/projects/38/views/1), final [commit with good summary](https://github.com/neondatabase/neon/pull/4498)) converted more of the pageserver code base to `async fn`s.

We had to revert that final commit due to performance considerations.
The current hypothesis is that most of the `spawn_blocking`'ed calls were completely CPU-bound and too short-lived (single-digit microsecond range).

(More details: https://www.notion.so/neondatabase/Why-we-needed-to-revert-my-async-get_value_reconstruct_data-patch-or-what-I-learned-about-spawn_b-91f28c48b7314765bdeed6e8cb38fdce?pvs=4 )

# Goals

This epic sets out to convert the remaining IO stack, i.e., all that was `spawn_blocking`ed to `async fn`s.

We'll then use the work in

* #4744 

to read data from the filesystem using `async` Rust in an efficient manner.

If #4744 can't deliver, we'll evaluate doing `O_DIRECT` + large pageserver-internal page cache for reads.

If that doesn't work out, we've still made progress with the async conversion.

# DoD

All code up to the point where we issue the system call to read from Image or Delta layer files is `async`.
The system call itself remains synchronous, it is _not_ converted to `tokio::fs`.
This allows merging the work in this PR without performance regressions caused by `tokio::fs`, thereby isolating any potential performance regressions to any refactoring changes required.

```[tasklist]
### Tasks
- [ ] https://github.com/neondatabase/neon/pull/4773
- [ ] https://github.com/neondatabase/neon/pull/4805
- [ ] https://github.com/neondatabase/neon/pull/4836
- [ ] https://github.com/neondatabase/neon/pull/4838
- [ ] https://github.com/neondatabase/neon/pull/4839
- [ ] https://github.com/neondatabase/neon/pull/4883
- [ ] https://github.com/neondatabase/neon/pull/4884
- [ ] https://github.com/neondatabase/neon/pull/4905
- [ ] https://github.com/neondatabase/neon/pull/4963
- [ ] https://github.com/neondatabase/neon/pull/4982
- [ ] https://github.com/neondatabase/neon/pull/5015
- [x] https://github.com/neondatabase/neon/pull/4994 by @problame
- [ ] https://github.com/neondatabase/neon/pull/5023
- [ ] https://github.com/neondatabase/neon/pull/5056
- [ ] https://github.com/neondatabase/neon/pull/5111
- [x] https://github.com/neondatabase/neon/pull/5129 by @problame
- [x] https://github.com/neondatabase/neon/pull/5181 by @problame
- [x] https://github.com/neondatabase/neon/pull/5186 by  @problame
- [ ] https://github.com/neondatabase/neon/pull/5121
- [ ] https://github.com/neondatabase/neon/pull/5189
- [ ] https://github.com/neondatabase/neon/pull/5190
- [x] https://github.com/neondatabase/neon/pull/5191 by @problame
- [ ] https://github.com/neondatabase/neon/pull/5195
- [ ] https://github.com/neondatabase/neon/pull/5203
- [ ] https://github.com/neondatabase/neon/pull/5224
- [ ] https://github.com/neondatabase/neon/pull/5247
- [ ] #5280
- [ ] https://github.com/neondatabase/neon/issues/5365
- [ ] https://github.com/neondatabase/neon/issues/5479
```

**Comment by problame** [comment]
I overlooked the VirtualFile when scoping out this epic.
It will require more work.

Remaining work needed (exploration work done in https://github.com/neondatabase/neon/pull/5158 )


- [ ] special-purpose api for write-once files, to be used in `save_metadata` and `persist_tenant_conf`
- [ ] extract the append-only-ness-on-top-of-VirtualFile that's implemented in EphemeralFile into a "superclass"
- [ ] use this superclass for the delta & image layer writers
- [ ] switch the `Summary::ser_into(&summary, &mut file)?` and `write_all` usage in the layer writers to directly call async functions on VirtualFile. This is the same as in #5121 , but for the write path. Possibly park #5121 until we get to this item, then resume work there.
- [ ] At this point, there are no sync users of VirtualFile and we can explore what it takes to convert the file descriptor cache to use tokio::sync::RwLock

**Comment by arpad-m** [comment]
With today's merging of #5247 and #5280, I think the last steps have been completed to enable us to switch to `async fn` for the `VirtualFile` operations, and therefore I think this issue can be closed, concluding this epic.

For immediate followup work, PR #5191 is still unmerged and marked as a draft, and the comments on #5186 are also outstanding. Getting latter merged quickly allowed me to build on top of it and finish the asyncification work for `VirtualFile`. Also, if we switch to tokio's `fs::File` APIs, we need to do something about the `read_at` operation that is [not supported by tokio](https://github.com/tokio-rs/tokio/issues/1529), either via extension trait, or some other means.

**Comment by arpad-m** [comment]
As followup, there is also the comment from #5224:

> We switch towards not using VirtualFile in the par_fsync module, hopefully this is only temporary until we can actually do fully async I/O in VirtualFile. This might cause us to exhaust fd limits in the tests, but it should only be an issue for the local developer as we have high ulimits in prod.

the module exposes both a sync and async fn API, and it seemed weird to me to change this module to use the "fake" async of VirtualFile. Once we have real async in there, we can switch that module.

**Comment by arpad-m** [comment]
The remaining todo item would be reverting #5291 once #5319 has been merged.

List of followups:

- [ ] https://github.com/neondatabase/neon/issues/5365
- [ ] https://github.com/neondatabase/neon/issues/5366
- [ ] Do async fsync in the par_fsync module: https://github.com/neondatabase/neon/issues/4743#issuecomment-1733775002

**Comment by stepashka** [comment]
notes from 6th of Nov storage team planning:
this is blocked ATM
