### ISSUE TITLE
Epic: reduce space amplification

### ISSUE THREAD

**Issue by shanyp** [neondatabase/neon#4754]
## Implementation ideas

```[tasklist]
### Tasks
- [ ] #4377
- [ ] #4376
- [ ] #4400
- [ ] #1380
- [ ] https://github.com/neondatabase/neon/issues/1359
- [ ] https://github.com/neondatabase/neon/issues/4349
- [ ] https://github.com/neondatabase/neon/issues/4348
- [ ] https://github.com/neondatabase/neon/issues/4418
- [ ] https://github.com/neondatabase/neon/issues/4509
- [ ] https://github.com/neondatabase/neon/issues/4553
- [ ] https://github.com/neondatabase/neon/issues/4580
- [ ] https://github.com/neondatabase/neon/issues/4373
```

## Other related tasks and Epics
-
