### ISSUE TITLE
Epic: safekeepers dynamic membership change (Phase 1)

### ISSUE THREAD

**Issue by arssher** [neondatabase/neon#4782]
We need to be able to move tenants between safekeepers:
1. To migrate all tenants on one safekeeper if it dies.
2. To migrate one tenant if we find that load balancing needs it.

Eventually a proper dynamic membership change two step algorithm should be implemented (), which works correctly regardless of old safekeeper(s) state. However this is complicated, so let's do it in following large steps:

```[tasklist]
### Tasks
- [ ] #4783
- [ ] https://github.com/neondatabase/neon/issues/6340
- [x] Migration script https://github.com/neondatabase/cloud/pull/15227
- [ ] https://github.com/neondatabase/cloud/issues/7931 required for migration without endpoint restart
- [ ] https://github.com/neondatabase/neon/issues/8700
```

**Comment by stepashka** [comment]
we aim to work on this this year

**Comment by arssher** [comment]
Migration script is at https://github.com/neondatabase/cloud/pull/15227

**Comment by arssher** [comment]
done
