### ISSUE TITLE
Support custom extensions (control plane)

### ISSUE THREAD

**Issue by lubennikovaav** [neondatabase/neon#5018]
- [ ] #5019

- [ ] Allow connections from compute to s3 bucket (was restricted by PR https://github.com/neondatabase/cloud/pull/5890)

- [ ] Write e2e test for remote extensions

- [ ]  Pass ext_index.json that we generate in storage CI to control plane and store it in the database to use as RemoteExtensions spec.

**Comment by lubennikovaav** [comment]
duplicates 
https://github.com/neondatabase/neon/issues/4269
