### ISSUE TITLE
Epic: split brain protection & multi-attach safety for pageserver

### ISSUE THREAD

**Issue by jcsp** [neondatabase/neon#5050]
## Motivation

This is a prerequisite to safely live-migrating tenants, and safely re-attaching tenants to another pageserver when their original pageserver is unresponsive but might still be alive.

## DoD

A strong guarantee that even if two pageservers have the same tenant attached at the same time, user data will not be lost, and the latest attached pageserver will be able to ingest WAL and serve reads.

## Implementation ideas

Remote storage generation numbers: https://github.com/neondatabase/neon/pull/4919

```[tasklist]
### Tasks
- [x] https://github.com/neondatabase/neon/issues/5135
- [x] https://github.com/neondatabase/neon/issues/5136
- [x] https://github.com/neondatabase/neon/issues/5137
- [x] https://github.com/neondatabase/neon/issues/5139
- [x] https://github.com/neondatabase/neon/issues/5381
- [ ] https://github.com/neondatabase/neon/issues/5138
- [ ] Ensure control plane backups don't include generation numbers (it is unsafe to roll them back)

```

## Other related tasks and Epics
- https://github.com/neondatabase/cloud/issues/6600
