### ISSUE TITLE
Epic: crash-consistent layer map through index_part.json

### ISSUE THREAD

**Issue by problame** [neondatabase/neon#5172]
## Motivation

See

- #5086

> This RFC describes a simple scheme to make layer map updates crash
> consistent by leveraging the index_part.json in remote storage. Without
> such a mechanism, crashes can induce certain edge cases in which broadly
> held assumptions about system invariants don't hold.

## DoD

- The core proposal in the RFC is implemented, thereby
  - fixing the crash consistency problems with `L0=>L1 compaction` that are outlined in the RFC
  - establishing the commonly-assumed invariant that we never overwrite / overPUT layer files.
- The mitigations to avoid loss of work in case of crash / SIGKILL are out of scope of this epic https://github.com/neondatabase/neon/pull/5086/files#diff-20449837bb824b5c1bb90c475fd60ae662d4447031c447a5bbed9ba27a02287dR168-R176 

## Other related tasks and Epics

This epic is required for #4938 because the alternative there is to work around the crash consistency problems with `L0=>L1 compaction` in a hacky and time-expensive way.
See https://github.com/neondatabase/neon/pull/5086#pullrequestreview-1604364258 and preceding comments by @koivunej .

Also copy-pasting the list of related issues from the RFC:

- https://github.com/neondatabase/neon/issues/4749
- https://github.com/neondatabase/neon/issues/4418
  - https://github.com/neondatabase/neon/pull/4422
- https://github.com/neondatabase/neon/issues/5077
- https://github.com/neondatabase/neon/issues/4088
  - (re)resolutions:
    - https://github.com/neondatabase/neon/pull/4696
    - https://github.com/neondatabase/neon/pull/4094
      - https://neondb.slack.com/archives/C033QLM5P7D/p1682519017949719

## Tasks

Implementation plan (will convert this into an Epic once I get more approvals for this RFC)

```[tasklist]
### Tasks
- [x] Add localfs remote storage to all Rust tests => https://github.com/neondatabase/neon/pull/5164; Pain point will be tests that assume local state is ahead of remote state.
- [ ] Implement the changes described in the RFC. @koivunej and I scoped it out, it's quite trivial.
- [ ] https://github.com/neondatabase/neon/pull/5243
- [ ] https://github.com/neondatabase/neon/pull/5402
- [ ] https://github.com/neondatabase/neon/pull/5412
- [ ] #5484
- [ ] https://github.com/neondatabase/neon/pull/5198
- [ ] Disallow pageserver without remote storage
- [ ] Stop writing local metadata file, only create a marker file if necessary
```

**Comment by koivunej** [comment]
I am surprised the NOOP causes this error as well.

**Comment by koivunej** [comment]
The refactorings are now in which will pave a way for a default remote storage for pageserver.

While looking around, I noticed that benchmarks currently do not use a remote storage.

Earlier I've found that making it required in the `PageserverConf` might also be detrimental because PageserverConf is required to do pretty much everything.

In the ongoing #5198 I've implemented:
- the rfc for the `Timeline::{load_layer_map,merge_local_and_remote_metadata}`, no interesting test failures

**Comment by koivunej** [comment]
Discussed on https://neondb.slack.com/archives/C033RQ5SPDH/p1695818222198339: we currently might not deny branching from a timeline which is yet to reach remote storage. Might need to do this before the remaining in the ongoing #5198.

**Comment by koivunej** [comment]
With #5198 I think this matter is becoming resolved. What is left not done could be considered out of scope for this epic:
- removal of `remote_storage = None` support #4099
- removal of local metadata file updates (reflected in the task list)

I was not able to squeeze these in before my vacation because I think there's still a lot of refactoring needing to be done even after implementing #4099, namely the `Timeline::scan_and_sort_timelines_dir`. I made a false start with it before realizing:
- the function can delete files or directories which have already been listed, but just not iterated over yet -- so the many exists checks are needed
- TimelineId::from_str does in fact fail if there are trailing characters
- the function processes marker files and actual timeline directories "simultaneously" in "whatever order"

It might make sense to try similar to #5074 with this, since the reasons to delete timelines have now grown by one and will be later than the `spawn_blocking` initial directory walk; then all loads/deletion resumption/cleanup as temporary executions could happen in one place, with multiple incoming "state arrows".

My initial false start had me collecing a `HashMap<TimelineId, State>` where:

```rust
struct State {
    uninit_markers: Vec<String>,
    delete_markers: Vec<String>,
    found_actual: bool,
    temps: Vec<String>,
}
```

The fields need to be `Vec<String>` where the item is file name. Due to how we recognize different kind of suffix marker files (`str::ends_with`) we could have many of those, and I suppose the current version would had supported that.

However the decision to act on a `State` (as above) is not so clear cut: old implementation just acted on **any** state in the order of listing the directory. If we want to delay that to when we've observed that an `index_part.json` is missing, then we will need to understand what the current code is doing really closely. Of course, having a prequel of simplifying how the marker files operate or how timeline creation could work happen within a strict `${timeline_id}.tmp` directory would greatly simplify this.
