### ISSUE TITLE
Epic: seamless tenant migration between pageservers

### ISSUE THREAD

**Issue by jcsp** [neondatabase/neon#5199]
## Motivation

This follows on from https://github.com/neondatabase/neon/issues/5050.  Whereas #5050 makes it safe to attach a tenant to a new pageserver without detaching the old one, this epic will make a tenant migration seamless from postgres's point of view.

See RFC: https://github.com/neondatabase/neon/pull/5029

This ticket is the pageserver side of the work: control plane changes are described elsewhere:
- https://github.com/neondatabase/cloud/issues/7992

## DoD

For failover (i.e. unplanned migration), only most recent LSNs become unavailable for reads.  They become available again in a time bounded by the time taken for the new pageserver to download the writes since the remote_consistent_lsn on the old pageserver.

For planned migrations, postgres experiences no loss of read availability whatsoever.

```[tasklist]
### Tasks
- [x] Compute: live reconfiguration of pageserver https://github.com/neondatabase/neon/issues/4578
- [x] Improved concurrency for TenantsMap updates (#5378)
- [x] Pageserver: implement flush & AttachedStale notification API, AttachedMulti mode ( https://github.com/neondatabase/neon/issues/5379)
- [x] #5842  Pageserver: create automated tests that demonstrate the migration process
- [ ] https://github.com/neondatabase/neon/pull/5745
- [x] Deploy more pageservers to accommodate secondary locations
- [x] Carry out drill of whole node evacution in staging
- [ ] https://github.com/neondatabase/neon/issues/5388
- [ ] https://github.com/neondatabase/neon/pull/7946
- [ ] https://github.com/neondatabase/neon/issues/5396
```

**Comment by koivunej** [comment]
Before we can enable generation usage and these, we will need to have a way to restrict `consumption_metrics.rs` from a pageserver with previous generation number.

**Comment by jcsp** [comment]
This is on pause to avoid merging more code until we can deploy existing changes, which will require https://github.com/neondatabase/cloud/issues/6600

**Comment by NanoBjorn** [comment]
@jcsp do you have an issue somewhere on re-attach and maybe validate modifications? As far as I understood from the RFC, we should return `mode` in `/re-attach` response, but generation number there should also become optional for the secondaries then.

**Comment by jcsp** [comment]
I just responded to the similar ping on https://github.com/neondatabase/cloud/issues/9614#issuecomment-1911064489 . There's no change to validate.

Including attachment states and/or secondary tenants in /re-attach responses is not essential for correctness here -- that's more of an optimization to enable tenants omitted in /re-attach to smoothly transition to secondary rather than detaching.
