### ISSUE TITLE
Epic: Per Process / Backend Resource Utilization View

### ISSUE THREAD

**Issue by brendan-stephens** [neondatabase/neon#5321]
## Motivation
Expose view(s) that can be used with pg_stat_activity that allow users to get a better grip on per-query or backend system resource utilization:

- % CPU
- % Mem / Mem
- Work Files Count
- Work Files Disk Utilization

## DoD
- [ ] view providing per query resource utilization (pg_stat_query, pg_backend_activity?)

```
neon=# select procpid,usename,application_name, get_pid_cpu_mem(procpid).cpu_perc,get_pid_cpu_mem(procpid).mem_perc,current_query from pg_stat_activity;
-[ RECORD 1 ]----+--------------------------------------------------------------------------------------------------------------------------------------------------
procpid          | 12991
usename          | neonadmin
application_name | psql
cpu_perc         | 0
mem_perc         | 0.6
disk_spill       | 0 kb
current_query    | select procpid,usename,application_name, get_pid_cpu_mem(procpid).cpu_perc,get_pid_cpu_mem(procpid).mem_perc,current_query from pg_stat_activity;
```

## Implementation ideas
- [ ] pg_proctab
- [ ] pg_top
- [ ] neon_utils

## Tasks
- [ ] pg_temp has per process / operation information that can be leveraged
- [ ] pg_proctab and pg_top can be leveraged for some additional information or 
- [ ] neon_utils could provide an interface for pg backend activity
