### ISSUE TITLE
pageserver: migration testing tracker

### ISSUE THREAD

**Issue by jcsp** [neondatabase/neon#5396]
This issue is a reminder of particular test cases we want to cover for HA/migration changes.

- [ ] A secondary location on a node with disk pressure: expect to see layers evicted, but then re-downloaded if the attached tenant's heatmap bumps their access time.
- [ ] Compactions & GC on a location in AttachedMulti state -- they should not delete anything.  An AttachedStale peer should be able to read everything.
- [ ] Write new data with a location in AttachedStale state: they should not be uploading anything to S3.
- [ ] Disk pressure on a location in AttachedStale state: once they see a request to evict a layer, they should start uploading things and doing compactions, even if it ultimately leaks objects.

**Comment by jcsp** [comment]
Related: https://github.com/neondatabase/neon/pull/5397
