### ISSUE TITLE
revert "revert recent VirtualFile asyncification changes #5291"

### ISSUE THREAD

**Issue by problame** [neondatabase/neon#5479]
This is the last hold-out for #4743 
and a blocker for #4744 

```[tasklist]
### Tasks
- [ ] https://github.com/neondatabase/neon/issues/5481
- [ ] fix it
- [ ] https://github.com/neondatabase/neon/pull/5480
- [ ] https://github.com/neondatabase/neon/pull/5482
- [ ] https://github.com/neondatabase/neon/pull/5578
- [ ] https://github.com/neondatabase/neon/pull/5493
- [ ] https://github.com/neondatabase/neon/pull/5483
- [ ] https://github.com/neondatabase/neon/pull/5955
- [ ] https://github.com/neondatabase/neon/pull/6000
- [ ] https://github.com/neondatabase/neon/issues/5993
- [ ] https://github.com/neondatabase/neon/issues/6062
- [ ] with the revert applied...
- [x] ensure it doesn't repro anymore during startup, above changes should have fixed that
- [x] right-size page cache & virtual-file cache to avoid thrashing
- [ ] https://github.com/neondatabase/cloud/issues/8351
- [x] determine relevance of #5962 for this issue => https://github.com/neondatabase/neon/issues/5962#issuecomment-1877246627
- [ ] https://github.com/neondatabase/neon/pull/6324
- [x] ensure we can uphold at current peak getpage/second => use #5771
- [ ] https://github.com/neondatabase/neon/pull/6309
- [x] observe in staging
- [x] ship it to prod
```
```[tasklist]
### Follow-Ups
- [ ] https://github.com/neondatabase/neon/issues/6065
```

**Comment by problame** [comment]
Not done until shipped

**Comment by problame** [comment]
Staging showed no meaningful differences: https://neondb.slack.com/archives/C033RQ5SPDH/p1704912242795849

**Comment by problame** [comment]
Staging showed no meaningful differences: https://neondb.slack.com/archives/C033RQ5SPDH/p1704912242795849

**Comment by problame** [comment]
This is shipping to prod this week:  https://github.com/neondatabase/neon/commit/93450f11f5f34a1e7435d9e73727f38036b92457
