### ISSUE TITLE
Epic: pageserver support for sharding phase 1

### ISSUE THREAD

**Issue by jcsp** [neondatabase/neon#5507]
This epic describes the pageserver changes required to enable sharding phase 1.

Phase 1 does not include splitting: tenants will be created with a set number of shards.

### Part 1: establish APIs

**Milestone**: control plane code that expects sharding-aware APIs can talk to the pageserver, and compute will work when using a ShardMap to talk to multiple pageservers.

```[tasklist]
### Tasks
- [ ] https://github.com/neondatabase/neon/issues/5505 (https://github.com/neondatabase/neon/pull/5432)
- [x] https://github.com/neondatabase/neon/issues/5787 Adjust TenantsMap to use a tuple of (TenantId, shard) as its key, so that one pageserver can accomodate multiple shards from the same tenant.
- [x] https://github.com/neondatabase/neon/issues/5788  Let tenant APIs accept a shard identity
```

### Part 2: make sharding work

**Milestone**: the shards  within a tenant will store different data: we can demonstrate hosting a 1TiB tenant where each pageserver only holds 1/nth data.

```[tasklist]
### Tasks
- [ ] https://github.com/neondatabase/neon/issues/5924
- [ ] https://github.com/neondatabase/neon/issues/6026
- [ ] https://github.com/neondatabase/neon/issues/6025
```

### Part 3: Loose ends

Outstanding loose ends items moved into https://github.com/neondatabase/neon/issues/6288

```[tasklist]
### Tasks
- [ ] Compaction: figure out if gap detection needs to be made stripe-aware to avoid spuriously splitting layers
- [ ] https://github.com/neondatabase/neon/issues/5953
- [ ] initdb uploads: these are written in a shard-naive path.  That's fine as long as our deletion still deletes the entire tenant prefix at some point, need to validate + write tests to ensure that is the case.
- [ ] TenantHarness should use a sharding-enabled state by default for unit tests
- [ ] neon_fixtures.py should use explicitly-set shard by default, even for default unsharded scenario.
- [ ] https://github.com/neondatabase/neon/issues/5929
- [ ] Make a plan for optimizing the way page_service requests might end  up looking up tenant shard on every getpage (see "note to reviewers" on https://github.com/neondatabase/neon/pull/5980)
- [ ] https://github.com/neondatabase/neon/issues/6038
- [ ] https://github.com/neondatabase/neon/issues/6072
```

**Comment by jcsp** [comment]
Loose ends moved into https://github.com/neondatabase/neon/issues/6288
