### ISSUE TITLE
Epic: compute support for sharding phase 1

### ISSUE THREAD

**Issue by jcsp** [neondatabase/neon#5508]
See https://github.com/neondatabase/neon/issues/5507 for the related pageserver work.

RFC in progress here: https://github.com/neondatabase/neon/pull/5432

## Tasks

- [ ] Update configuration to accept a list of pageserver connection strings, and metadata on stripe size & shard count, i.e. the ShardMap described in the RFC.
- [ ] For getpage requests, calculate the key and calculate the corresponding shard, then dispatch the RPC to the pageserver holding that shard, including error handling (e.g. if the pageserver denies ownership of the shard, backoff-retry in expectation of the control plane supplying updated configuration)
- [ ] If necessary, adjust prefetch code to clamp prefetched ranges to the boundaries of a stripe, to avoid issuing requests that cover pages belonging to multiple pageservers.

**Comment by vadim2404** [comment]
PR: #5837

**Comment by vadim2404** [comment]
@hlinnaka , waiting for your final review

**Comment by vadim2404** [comment]
to merge it this week
