### ISSUE TITLE
Epic: proxy. Connectivity errors

### ISSUE THREAD

**Issue by vadim2404** [neondatabase/neon#5509]
We have to resolve connection errors that our users see

```[tasklist]
### Tasks
- [ ] https://github.com/neondatabase/neon/issues/5510
- [ ] https://github.com/neondatabase/neon/issues/5511
- [ ] https://github.com/neondatabase/neon/issues/5568
- [ ] https://github.com/neondatabase/neon/issues/5569
- [ ] https://github.com/neondatabase/neon/issues/5654
- [ ] https://github.com/neondatabase/neon/issues/5570
- [ ] https://github.com/neondatabase/neon/issues/5800
- [ ] https://github.com/neondatabase/neon/issues/5801
- [ ] https://github.com/neondatabase/neon/issues/6291
- [ ] https://github.com/neondatabase/neon/issues/6292
- [ ] https://github.com/neondatabase/neon/issues/6293
```

**Comment by stradig** [comment]
Implementation work is done. What is left is documentation and is tracked in a separate issue.
