### ISSUE TITLE
Epic: Compute SLOs

### ISSUE THREAD

**Issue by vadim2404** [neondatabase/neon#5512]
## Motivation
To track and guarantee the compute health

## DoD
As a result, we should have a dashboard with SLOs

## Tasks
- [x] get requirements from stakeholders (support team) 
- [x] expose metrics from Postgres to Grafana (postgres exporter). to validate what we have and what we can use
- [ ] handle OOM errors
- [ ] sort postgres errors by severity (by error code)
- [ ] set up alerts
- [ ] sort compute errors by source of origin (postgres, safekeepers, pageserver, compute_ctl, proxy)
- [ ] build SLO dashboard per endpoint / overall
- [ ] clean up existing error messages

## Other related tasks and Epics
-

**Comment by vadim2404** [comment]
@lubennikovaav , to update

**Comment by vadim2404** [comment]
closed this one in favour of https://github.com/neondatabase/cloud/issues/8674
