### ISSUE TITLE
Epic: [Azure] production ready Azure blob storage support

### ISSUE THREAD

**Issue by arpad-m** [neondatabase/neon#5567]
PR #5546 has added a preview-level azure blob storage support but left some key areas in a state that could see improvements.
This epic tracks the follow-up work needed to make azure blob storage support production ready.

```[tasklist]
### Tasks
- [ ] #5563
- [x] see if we can share more between S3's test and azure's test files: #6146
- [ ] should we panic [upon receiving a malformed key](https://github.com/neondatabase/neon/pull/5546#discussion_r1360702859)?
- [ ] #5590
- [x] #5566
- [x] #5565
- [ ] maybe more CI work on top of that? End to end tests in azure?
- [ ] #5571
- [x] #5575
- [x] https://github.com/neondatabase/neon/pull/5636
- [ ] https://github.com/neondatabase/neon/pull/6103
- [ ] https://github.com/neondatabase/neon/pull/6362
- [ ] https://github.com/neondatabase/neon/pull/7597
- [ ] https://github.com/neondatabase/neon/pull/7964
- [ ] https://github.com/neondatabase/neon/issues/7547
- [ ] #7546
- [ ] https://github.com/neondatabase/cloud/issues/12627
```

**Comment by stepashka** [comment]
@arpad-m , does this replace https://github.com/neondatabase/cloud/issues/7204 ?

**Comment by arpad-m** [comment]
@stepashka there is also https://github.com/neondatabase/neon/issues/5562 which is soon to be closed. I think with that in combination with this issue, we can say https://github.com/neondatabase/cloud/issues/7204 is replaced. Sorry I've not seen it!

**Comment by arpad-m** [comment]
closing in favour of the follow-up in https://github.com/neondatabase/cloud/issues/12627 . The existing azure blob implementation is production-ready, the missing parts are in maintenance tooling outside of the main pageserver binary.
