### ISSUE TITLE
Epic: cancellation in long running pageserver tasks

### ISSUE THREAD

**Issue by jcsp** [neondatabase/neon#5585]
This is an umbrella ticket for all the places may not be properly respecting cancellation in long running tasks

```[tasklist]
### Tasks
- [ ] Drop out of waiting for semaphore for remote storage
- [ ] Any loops inside GC/compaction
- [ ] https://github.com/neondatabase/neon/issues/5066
- [ ] Automated test that stresses tenant detach/deletion while background work is going on, asserting that operations complete promptly even if background work is slow.
- [ ] https://github.com/neondatabase/neon/issues/6096
```

**Comment by koivunej** [comment]
Related investigation: https://app.incident.io/neondb/incidents/73

**Comment by koivunej** [comment]
Lots of cancellation token checks have been thrown around, now our problem is not so much the cancellation, but the bad errors.

**Comment by jcsp** [comment]
What's next for this issue?  Let's make it specific enough to take action on, or close it.
