### ISSUE TITLE
Epic: Credentials caching in proxy

### ISSUE THREAD

**Issue by conradludgate** [neondatabase/neon#5704]
## Motivation

Every database request requires a `get_auth_info` lookup in control-plane. Currently this adds quite a bit of latency and reliance on control plane, it would be good to cache this information.

We currently do a small bit of caching as part of the HTTP connection pool, but it could be much better.

## Implementation ideas

https://github.com/neondatabase/neon/pull/4285

With control-plane moving to a regional model, I'm not sure if a redis cache will be worth the complexity cost it brings. Perhaps an in-memory LRU cache is sufficient.

## Tasks
- [ ] management API to invalidate cache entries
- [ ] in memory LRU cache for auth info
- [ ] add it for HTTP endpoints

**Comment by vadim2404** [comment]
Goal: to implement invalidation through Redis

**Comment by vadim2404** [comment]
@conradludgate to review proxy PR
@khanova to find someone from control plane to review corresponding PR in cloud repo

**Comment by vadim2404** [comment]
@khanova to update the description with the algorithm and to pass the review this week.

**Comment by conradludgate** [comment]
There now exists a role cache in all regions in production, along with a redis notification channel to invalidate role secrets as they change.
