### ISSUE TITLE
proxy: reduce repeated calls to wake_compute

### ISSUE THREAD

**Issue by conradludgate** [neondatabase/neon#5705]
## Motivation

Many of our clients run an in-app connection pool. This might create 10 new database connections at the same time using the same credentials. Currently, this will trigger 10 calls to wake_compute. If those retry because of "endpoint_in_transition" errors, then this will be amplified.

## Implementation ideas

Implement a mechanism to lock the node cache while waking up that node. Add a watch channel in order to notify the waiting connections of the cached node info once we have it.

## Tasks
- [x] lock the cached node info per endpoint while calling wake_compute
- [x] enable the locking during e2e tests and staging
- [ ] rollout to production

**Comment by conradludgate** [comment]
Enabled on staging

**Comment by vadim2404** [comment]
@conradludgate will start enabling it soon on production (will enable it this week in a couple of regions)

**Comment by conradludgate** [comment]
Enabled in Isreal and Asia Pacific regions

**Comment by conradludgate** [comment]
proceeding to enable globally https://github.com/neondatabase/aws/pull/843

**Comment by vadim2404** [comment]
there is a PR that opens it globally
