### ISSUE TITLE
Epic: Logical replication

### ISSUE THREAD

**Issue by vadim2404** [neondatabase/neon#5748]
## Motivation
To allow our users creating publications

## DoD
As a user, I can execute `create publication` in Neon and subscribe to this publication outside Neon

## Tasks
- [x] https://github.com/neondatabase/neon/pull/5271
- [x] https://github.com/neondatabase/neon/pull/5657
- [x] https://github.com/neondatabase/neon/pull/5660
- [x] #5749

## Other related tasks and Epics
- https://github.com/neondatabase/company_projects/issues/111

**Comment by leonard-henriquez** [comment]
@vadim2404 is there documentation on how to use Logical Replication?
Can I use it with Airbyte to copy data to another location ?
