### ISSUE TITLE
Epic: move outbound logical replication out of Beta

### ISSUE THREAD

**Issue by stepashka** [neondatabase/neon#6213]
## DoD
logical replication is not in beta on neon anymore and wal_level = logical can be enabled by default on all project on neon platform

```[tasklist]
### Tasks & bugs to fix
- [ ] https://github.com/neondatabase/neon/issues/6370
- [ ] https://github.com/neondatabase/neon/issues/6371
- [ ] https://github.com/neondatabase/neon/pull/6221
- [ ] https://github.com/neondatabase/neon/issues/6182
- [ ] https://github.com/neondatabase/neon/issues/6229
- [ ] https://github.com/neondatabase/cloud/pull/9015
- [ ] https://github.com/neondatabase/neon/issues/6257
- [ ] https://github.com/neondatabase/neon/issues/7593
- [x] Check that AUX v2 is default for all new tenants on pageserver
- [ ] https://github.com/neondatabase/neon/issues/8349
- [ ] https://github.com/neondatabase/cloud/issues/15226
- [ ] https://github.com/neondatabase/neon/issues/6626
- [x] Figure out observability of lagging publisher (slot retaining a lot of WAL)
- [ ] https://github.com/neondatabase/neon/issues/5885
- [x] Logical slots are copied to the replica and prevent WAL truncation, see https://github.com/neondatabase/neon/pull/9425#discussion_r1804820659
- [ ] https://github.com/neondatabase/neon/issues/8931
- [ ] https://github.com/neondatabase/neon/issues/8619
- [ ] https://github.com/neondatabase/neon/pull/9976
- [ ] https://github.com/neondatabase/cloud/issues/17261
- [ ] https://github.com/neondatabase/neon/issues/10037
```

Follow-ups (out of scope):
- https://github.com/neondatabase/neon/issues/6258
- https://github.com/neondatabase/cloud/issues/9985

## Other related tasks and Epics
- https://github.com/neondatabase/cloud/issues/8892

https://neondb.slack.com/archives/C04DGM6SMTM/p1703091242312799

**Comment by vadim2404** [comment]
@arssher , will your fixes help with first two items?

**Comment by arssher** [comment]
> slot may disappear on restart (hard to reproduce., only occured once)

I still don't know what was that. Stas tested manually and observed this once. There is known path by which slot might be lost, but this is highly unlikely (endpoint killed before logical message is committed to safekeepers), Stas case wasn't like that. Need more testing and reproduction.

> in one case replication wasn't able to read WAL (hard to reproduce)

The more proper description would be 'if slot is lagging, on compute start replication might fail until the whole tail is downloaded'. We merged cap on max allowed lagging, but to really fix it we need to bring on demand WAL download from safekeepers to logical walsenders. We recently merged core patch:
https://github.com/neondatabase/neon/pull/5948
but using it in logical walsenders is separate step. Shouldn't be hard, but I haven't started on that.

**Comment by vadim2404** [comment]
@arssher will you work on on-demand WAL download in walsenders? Is it a part of this epic [will it block announcing GA for logical replication]?

@kelvich 
> slot may disappear on restart (hard to reproduce., only occured once)
I think nobody has been able to reproduce it so far. Reasonable question: is it a part of the epic's scope?

**Comment by andreasscherbaum** [comment]
Renamed to "outbound" logical replication. When this Epic was started, it was "only" logical replication, but now it's two different types of replication.

**Comment by andreasscherbaum** [comment]
Discussion with Stas: improve pageserver performance first

**Comment by ololobus** [comment]
Test:

- [ ] Sasha: Finish the aux v2 rollout (last batch tomorrow morning)

**Comment by ololobus** [comment]
This week:
- [ ] Waiting for the new compute image rollout

**Comment by ololobus** [comment]
This week:

- [ ] Tristan: look at AUX files monitoring and limiting

**Comment by skyzh** [comment]
@tristan957 there is already monitoring on the storage side for aux v2

https://github.com/neondatabase/neon/blob/6949b45e1795816507f5025a474e15d718e07456/pageserver/src/metrics.rs#L588-L595

there is total aux size metrics per timeline

**Comment by ololobus** [comment]
This week:

- [ ] Alexey: Expose snap files count metric and add to dashboards

**Comment by ololobus** [comment]
This week:

- [ ] Look at LR test failures (Tristan said that he will have a look on Thu)

**Comment by ololobus** [comment]
This week:
- Konstantin: try to write a repro script
- Tristan: https://github.com/neondatabase/cloud/issues/17261

**Comment by ololobus** [comment]
> https://github.com/neondatabase/cloud/issues/17261 failed due ENOSPACE, smth else is going there. Nikita helps there.

@tristan957 any progress with this?

So the original problem was that test was passing at first, and then regressed and started failing with ENOSPACE. [That was known in the beginning of Sept already](https://neondb.slack.com/archives/C0756AKBMU0/p1725260093124019)

The plan we discussed was

1. Repro this failure on staging (just manually rerun test)
2. Watch disk usage and figure out what is eating the disk space
3. Is it valid disk usage? Then we have two options
3.1. It's something we want to fix -> investigate further and discuss/propose the fix
3.2. Yes, it's OK -> bump the compute size and add fixed sized compute flag
4. Start running the test again

What was the item we gut stuck at? Or do I miss something and we got some additional context here?

**Comment by tristan957** [comment]
> So the original problem was that test was passing at first, and then regressed and started failing with ENOSPACE. [That was known in the beginning of Sept already](https://neondb.slack.com/archives/C0756AKBMU0/p1725260093124019)

I think there was some miscommunication between Stas and myself here. The current problem is that the publisher endpoint will not even start at the moment, which is different from the ENOSPC issue we were previously running into.

> @tristan957 any progress with this?

Last week, I was talking to Nikita K. about what is going on here because the endpoint was seemingly stuck. He and I came to the conclusion that the compute was failing to retrieve the basebackup from the pageserver due to some AUX files issues. After talking to the storage team, we determined that we should wait for Chi to come back from vacation to get his thoughts.

**Comment by ololobus** [comment]
This week:

- [ ] @knizhnik and @MMeent review and finalize https://github.com/neondatabase/neon/pull/9007
- [ ] @tristan957 get https://github.com/neondatabase/cloud/issues/17261 done, support storage team if needed

**Comment by ololobus** [comment]
This week:

- [ ] @knizhnik and @MMeent review and finalize https://github.com/neondatabase/neon/pull/9007
- [ ] @tristan957 follow up with @skyzh re https://github.com/neondatabase/cloud/issues/17261
- [ ] @tristan957 just increase start timeout for LR bench project?
- [ ] @tristan957 finalize and get review https://github.com/neondatabase/neon/pull/9467

**Comment by ololobus** [comment]
This week:

- [ ] @knizhnik and @MMeent review and finalize https://github.com/neondatabase/neon/pull/9007
- [ ] @tristan957 https://github.com/neondatabase/cloud/issues/17261, there were issues with bumping the timeout in cplane. Ping Muhammet starting Wed
- [ ] @tristan957 finalize and get review https://github.com/neondatabase/neon/pull/9467
- [ ] @tristan957 list of Postgres metrics in Notion

**Comment by tristan957** [comment]
- [ ] @tristan957 https://github.com/neondatabase/cloud/issues/17261: Continuing to try to understand the issue after many rounds of testing
- [ ] @ololobus have a look on https://github.com/neondatabase/neon/pull/9467 reviews received and approved

**Comment by ololobus** [comment]
This week:

- [ ] @tristan957 Write docs for https://github.com/neondatabase/cloud/issues/17261 and close
- [ ] @tristan957 add a panel for the snap files size to https://neonprod.grafana.net/d/edr9erae8dipse/compute-replication-overview?orgId=1&refresh=1m and close https://github.com/neondatabase/neon/issues/8619

**Comment by tristan957** [comment]
Docs for LR benchmarks: https://github.com/neondatabase/docs/pull/263
PR for logical snapshots size: https://github.com/neondatabase/neon/pull/9887

Looks like tests are failing, so I'll check those out today.

**Comment by ololobus** [comment]
@tristan957 finalize the default for https://github.com/neondatabase/neon/issues/8619. 300 snap files looks like a small number.

Why do we have 10-20k files in prod if the limit is 300? https://neonprod.grafana.net/d/edr9erae8dipse/compute-replication-overview?orgId=1&refresh=1m

**Comment by tristan957** [comment]
PR to bump default value to 10k: https://github.com/neondatabase/neon/pull/9896.

**Comment by ololobus** [comment]
This weeks:

- [ ] @knizhnik finalzie and merge https://github.com/neondatabase/neon/pull/9976
- [ ] @tristan957 wait for https://github.com/neondatabase/cloud/pull/20794, then look at LR failures

**Comment by ololobus** [comment]
This weeks:

- [ ] @knizhnik finalize and merge https://github.com/neondatabase/neon/pull/9976 (@hlinnaka to review)

**Comment by ololobus** [comment]
This weeks:

- [ ] @knizhnik finalize and merge https://github.com/neondatabase/neon/pull/9976 (@hlinnaka to review)
