### ISSUE TITLE
Epic: evict inactive timelines on safekeepers to s3

### ISSUE THREAD

**Issue by arssher** [neondatabase/neon#6220]
```[tasklist]
### Tasks
- [ ] https://github.com/neondatabase/neon/issues/6336
- [ ] https://github.com/neondatabase/neon/issues/7751
- [ ] https://github.com/neondatabase/neon/issues/6337
- [ ] https://github.com/neondatabase/neon/issues/8542
- [ ] https://github.com/neondatabase/neon/issues/6338
- [ ] https://github.com/neondatabase/neon/issues/8758
- [ ] https://github.com/neondatabase/neon/issues/8759
- [ ] https://github.com/neondatabase/neon/issues/8833
- [x] add metrics on total evicted timelines
- [x] ensure that eviction is retried
```

**Comment by problame** [comment]
Progress on #6337 planned this week, but, multi-week project.

**Comment by problame** [comment]
This week:
* monitor release of PR that was merged last week (TODO: link)
* impl & create PR for https://github.com/neondatabase/neon/issues/6337

**Comment by koivunej** [comment]
This week:
- an unlinked (please link) bug related to eviction
- then this issue should be ready

**Comment by petuhovskiy** [comment]
Last week:
- eviction PR was merged to staging, but not enabled anywhere
- then I discovered a bunch of issues and merged some fixes
- verified that no critical issues are left on staging

This week:
- waiting for production deploy to ensure nothing break with DISABLED eviction
- after that, we can enable eviction in staging and look for new issues

Next week:
- if everything will be good in staging, we should enable eviction in prod

Later:
- enable file deletion gradually in all regions (first staging, then prod)

**Comment by jcsp** [comment]
Status: https://github.com/neondatabase/neon/issues/6338 is blocked on https://github.com/neondatabase/neon/issues/8542

**Comment by jcsp** [comment]
Modified assignee to Arseny, who is managing the rollout

**Comment by jcsp** [comment]
Modified assignee to Arseny, who is managing the rollout
