### ISSUE TITLE
Epic: pageserver shard splitting

### ISSUE THREAD

**Issue by jcsp** [neondatabase/neon#6278]
Working on at https://github.com/neondatabase/neon/issues/6278

RFC at https://github.com/neondatabase/neon/pull/6358

```[tasklist]
### Tasks
- [x] Basic functionality: able to increase shard count on a tenant via sharding service API (#6278)
- [x] Optimization: hard linking layers into child shards
- [x] Handle secondary locations
- [ ] https://github.com/neondatabase/neon/issues/6676
- [ ] https://github.com/neondatabase/neon/issues/7044
- [ ] https://github.com/neondatabase/neon/issues/7504
```

**Comment by jcsp** [comment]
Update 2023-01-29:
- The basics of shard splitting are in good shape in #6278 -- it probably makes sense to merge that before the feature is fully implemented, to enable creating some sharded tenants in staging ASAP.
- I'll tie up loose ends in the RFC this week and seek review.  The main open question is under what circumstances we will do pro-active compaction of child shards to reduce their size footprint: this is a hard question because it's likely to be some kind of heuristic tradeoff, unless we accept the I/O cost of just always doing it.
-

**Comment by jcsp** [comment]
Update 2023-03-11:
- Aim to land #6676 this week, at which point shard splitting will be fully safe to use.
