### ISSUE TITLE
Epic: pageserver sharding tech debt

### ISSUE THREAD

**Issue by jcsp** [neondatabase/neon#6288]
```[tasklist]
### Tasks
- [ ] https://github.com/neondatabase/neon/issues/7043
- [ ] neon_fixtures.py should use explicitly-set shard by default, even for default unsharded scenario.
- [ ] TenantHarness should use a sharding-enabled state by default for unit tests
- [x] Compaction: figure out if gap detection needs to be made stripe-aware to avoid spuriously splitting layers
- [ ] https://github.com/neondatabase/neon/issues/5953
- [x] initdb uploads: these are written in a shard-naive path.  Make sure we have a sharded deletion test that checks they're cleaned up.
- [ ] https://github.com/neondatabase/neon/pull/6037
- [ ] https://github.com/neondatabase/neon/pull/6280
- [ ] https://github.com/neondatabase/neon/issues/6307
- [x] Ensure that safekeeper is only getting logical size feedback from shard 0
- [ ] https://github.com/neondatabase/neon/issues/6649
- [ ] https://github.com/neondatabase/neon/issues/6072
- [ ] https://github.com/neondatabase/neon/issues/11175
- [ ] https://github.com/neondatabase/neon/issues/11340
- [ ] https://github.com/neondatabase/neon/issues/11534
```
