### ISSUE TITLE
calculate proxy port limits

### ISSUE THREAD

**Issue by conradludgate** [neondatabase/neon#6427]
We need to properly calculate the limitations of outgoing connections a single proxy pod can sustain. 

This is so we can tune HTTP connection pool size, or perhaps fail health checks when too many connections are in proxy-pass.
```[tasklist]
### Tasks
- [ ] https://github.com/neondatabase/helm-charts/pull/62
- [ ] Setup alerts for too many connections per instance
- [ ] https://github.com/neondatabase/helm-charts/pull/63
```

**Comment by conradludgate** [comment]
```
kubectl exec -ti neon-proxy-scram -- /bin/bash

$ cat /proc/sys/net/ipv4/ip_local_port_range
32768	60999
```
Seems like 28232 ports are available per pod.

Can we increase this to the full 1024..=65535 range?

**Comment by stradig** [comment]
This is done.
