### ISSUE TITLE
test failures with `test_pageserver_max_throughput_getpage_at_latest_lsn[100-13-30]`

### ISSUE THREAD

**Issue by problame** [neondatabase/neon#6473]
https://neondb.slack.com/archives/C06750CD9U5/p1706190798216269
```[tasklist]
### Tasks
- [ ] https://github.com/neondatabase/neon/pull/6477
- [ ] https://github.com/neondatabase/neon/pull/6474
- [ ] https://github.com/neondatabase/neon/pull/6475
- [ ] root cause why pidfile claim is so slow
- [ ] https://github.com/neondatabase/neon/pull/6483
- [ ] see whether we can re-enable n_tenants=100 on merge-to-main, it didn't add that much additional runtime
```

**Comment by problame** [comment]
obsolete, this got fixed / worked around / made irrelevant as part of @Bodobolero 's efforts to run pagebench on ec2 in https://github.com/neondatabase/neon/issues/6297
