### ISSUE TITLE
test suite: eliminate bug class "stray processes after test exits"

### ISSUE THREAD

**Issue by problame** [neondatabase/neon#6485]
# Problem

Some tests leave stay processes behind after they exit.

This is the potential root cause for failed coverage-report generation, as well as other flakiness.

# DoD

The Python test suite ensures that after each test function exit, there are no stray subprocesses left.

If there are any, the processes' argv are listed at WARNING level and the test fails, preventing the PR from being merged.

# Related Issues

# Work

```[tasklist]
### Implementation
- [ ] https://github.com/neondatabase/neon/pull/6270#issuecomment-1878842496
- [ ] https://github.com/neondatabase/neon/pull/6497
- [ ] https://github.com/neondatabase/neon/pull/6470
- [ ] https://github.com/neondatabase/neon/issues/6487
- [ ] https://github.com/neondatabase/neon/issues/6486
- [ ] https://github.com/neondatabase/neon/issues/6489
```

**Comment by jcsp** [comment]
Update:
- The cgroup approach bumped up against securiy concerns.
- Putting on pause.

**Comment by problame** [comment]
Paused until https://neondb.slack.com/archives/C059ZC138NR/p1707229781663129?thread_ts=1706265241.134019&cid=C059ZC138NR is resolved

**Comment by koivunej** [comment]
With #8742 it would appear that for a single run, we would no longer leak processes, possibly affected by #8714.

**Comment by jcsp** [comment]
(spring cleaning the storage board)

@bayandin is this ticket useful?  I'm happy to close it if this is something we're unlikely to work on in the near future.
