### ISSUE TITLE
Epic: Run extensions tests  

### ISSUE THREAD

**Issue by bayandin** [neondatabase/neon#6650]
## Motivation

Postgres extensions might not play well with Neon [[0]]. To minimise such chances, we can run an extensions test suite. 

## DoD

- We have an infrastructure for running extensions tests with Neon Postgres
- For some extension we run tests (my proposal is `pgvector`, `plv8` written in C, and `pg_graphql`, `pgx_ulid` written in Rust), it would be nice also to cover `postgis`
- We run such tests only if an extension or Postgres-related code (in `vendor/` or `pgxn/`) got changed.

<!--
## Implementation ideas

The default way of running tests for Postgres extensions is `make installcheck` and `make prove_installcheck`. Extension developers can use any other tools (worth checking their README.md/CONTRIBUTING.md files and CI pipelines).

Also, Postgres extensions can be written in Rust (and use `pgrx`[[1]]). The default way of running such tests is `cargo pgrx test`. Note that `pgrx` is a pretty clever tool, and it tends to do a lot of things under the hood, for example, it can download and build Postgreses to run tests on, so need to double-check that Neon is used. 

```[tasklist]
### Tasks
- [x] understand how extension work and how they are integrated
- [ ] Create the respective folder structure
- [ ] Get first c  test working with MAKEFILE
- [ ] Get second c test working with MAKEFILE
- [ ] Added a new target extension-regression-test . Update the root MAKEFILE to get the test working
- [ ] CI/CD integration : run test after regression test in same way regression test run
```

## Other related tasks and Epics
N/A

[0]: https://github.com/neondatabase/neon/pull/6599
[1]: https://github.com/pgcentralfoundation/pgrx

**Comment by abhigets** [comment]
## Notes 

1. We currently have 3 ways in which extensions exist 
       a. Our own that exists in neon/pgnx
       b. default on in vendor/contrib
       c. 3rd party extensions
2.  above a & b have their test and they run as a part of CI/CD
3. Whereas c i.e. 3rd party extensions are directly integrated by fetching the source code in our docker file and copied   in /usr/local/pgsql/<extension-src> their test and make file exist there. something that we can leverage from

**Comment by abhigets** [comment]
## Proposed MVP : Following is the way Makefile at the root of _extension_regression_ folder will operate
Target Date 15th 
1. Manually copy all the test file and MAKEFILE/ CARGO files in respective folder
2. Manually Identify the type of test rust/c  i.e figure out the way test are ran
3. hardcode the command in Makefile under a target

## Phase1 : Auto-detect the type of project and run respective make/cargo command 
1. Recursively iterate through the _extensions/_ folder 
2. identify the type of project rust/c and then run the test accordingly

## Phase3 : Dynamically fetch the test folder 
1. Approach 1: Either get the test folder from Dockerfile.compute-node and populate the folder structure above
2. Approach 2: Download the source from the respective url and populate the folder structure above for extensions that don't have a test then execute the test present by default using the Phase1 strategy

## Phase4: Based on learning update the folder structure
1. investigate  if the test within _extension_regression/extensions/<extension>_ can be removed and move sub folders one directory up
2. Rename the _extension_regression/extensions/<extension>_  to _extension_regression/extensions/<extension>_test_ 
3. Update MAKEFILE accordingly

## Phase5: Add extensive coverage for the remaining extensions
1. List all the extensions in Dockerfile.compute-node and add their respective tests
2. Identify missing test for the extension and add them to the regression suit


## CI/CD integration is part of MVP : 
Target Date 15th 
##TODO

**Comment by abhigets** [comment]
> * Where are we going to have `extension_regression` directory? In `neon` repo? In a separate project?

I still have to figure that out. Which is the best place for it? From the leaning of first test implementation i will update the proposal

**Comment by abhigets** [comment]
> * Are we going to use Neon components that we build in `build-neon` job or docker images with them?

i will first try to implement the first test and then later once i know how to run it it will be easy to decide what is the right place.

**Comment by abhigets** [comment]
> * Are we going to integrate it with the test framework that we have in `test_runner/`?

Currently, the probability of this is very low. But like before comments once i know how the integration works i will be able to figure out this

**Comment by bayandin** [comment]
Ok, let's try to run the first test and figure out the approach afterwards

**Comment by bayandin** [comment]
Last week:
- Created an image with extensions tests
- Found issues with wal2json extension
- Some issues with pgvector 0.7.0
- Resolved an issues with pganon and python dependency

This week:
- Fix some issues with pgvector 0.7.0
- Integrate with CI (check how long does it take to run all tests, and to decide how often do we want to run it)

**Comment by kelvich** [comment]
would be also good to add ketteq extensions to tests: https://github.com/ketteq-neon/postgres-exts

**Comment by bayandin** [comment]
Last week:
- additional tests for pganon, timescaledb, pgcron, pghintplan

This week:
- Review whatever works now and merge it
- Create issues for the troubled extensions

**Comment by bayandin** [comment]
Last week:
- Review fixes

This week:
- Review from @bayandin

**Comment by bayandin** [comment]
The first iteration with the set of extensions is done.
The remaining part:
- the rest of extensions (including rust extensions)
- run tests as non-superuser

**Comment by bayandin** [comment]
Previously:
- Enabled tests on Postgres 17 in a PR

This Week:
- Try to figure out the issues with Anastasiya

**Comment by a-masterov** [comment]
Previously:
* implemented nightly test runs
* discovered and fixed errors
This week:
* merge https://github.com/neondatabase/neon/pull/10826

**Comment by bayandin** [comment]
- https://github.com/neondatabase/neon/pull/11164 is merged
