### ISSUE TITLE
`test_pageserver_max_throughput_getpage_at_latest_lsn`: fails after ~1s with status 101

### ISSUE THREAD

**Issue by problame** [neondatabase/neon#6724]
Reported by @Bodobolero 

https://neondb.slack.com/archives/C033RQ5SPDH/p1707723367544629

https://neon-github-public-dev.s3.amazonaws.com/reports/main/7846373696/index.html#suites/e26265675583c610f99af77084ae58f1/39a10f32853edb40/

```
test_pageserver_max_throughput_getpage_at_latest_lsn[1-13-30]
```

```
2024-02-09 22:52:24.330 INFO [util.py:29] ready
2024-02-09 22:52:24.330 INFO [test_pageserver_max_throughput_getpage_at_latest_lsn.py:101] command: /tmp/neon/bin/pagebench get-page-latest-lsn --mgmt-api-endpoint http://localhost:15046 --page-service-connstring host=localhost port=15045 user=cloud_admin options='-cstatement_timeout=120s ' --runtime 30s
2024-02-09 22:52:24.331 INFO [neon_fixtures.py:2443] Running command '/tmp/neon/bin/pagebench get-page-latest-lsn --mgmt-api-endpoint http://localhost:15046 --page-service-connstring host=localhost port=15045 user=cloud_admin options='-cstatement_timeout=120s ' --runtime 30s'
2024-02-09 22:52:24.331 INFO [utils.py:117] Capturing stdout to "pagebench_43.stdout" and stderr to "pagebench_43.stderr"
```

from `pagebench_43.stderr`

```
2024-02-09T22:52:24.346577Z  INFO timelines:
[TenantTimelineId { tenant_id: be8c7c43a5d38341c74db54fba26fa4e, timeline_id: 414ca6c7aa388aec2e760a18db8170fb }]
2024-02-09T22:52:24.346601Z  INFO number of timelines:
1
2024-02-09T22:52:24.374749Z  INFO filter duration: 0.000672071
2024-02-09T22:52:24.374771Z  INFO waiting for everything to become ready
2024-02-09T22:52:24.375514Z  INFO work started
2024-02-09T22:52:25.273573Z ERROR panic{thread=tokio-runtime-worker location=/__w/neon/neon/pageserver/client/src/page_service.rs:44:29}: called `Result::unwrap()` on an `Err` value: Error { kind: Closed, cause: None }

...

2024-02-09T22:52:25.317187Z ERROR client:panic{thread=tokio-runtime-worker location=pageserver/pagebench/src/cmd/getpage_latest_lsn.rs:440:18}: called `Result::unwrap()` on an `Err` value: getpage for be8c7c43a5d38341c74db54fba26fa4e/414ca6c7aa388aec2e760a18db8170fb

Caused by:
    connection closed

...

2024-02-09T22:52:25.319174Z ERROR panic{thread=tokio-runtime-worker location=pageserver/pagebench/src/cmd/getpage_latest_lsn.rs:309:25}: client has gone away unexpectedly

...

2024-02-09T22:52:25.376628Z  INFO RPS: 2290
2024-02-09T22:52:26.378031Z  INFO RPS: 0
2024-02-09T22:52:27.379518Z  INFO RPS: 0

```

Pageserver logs

```
2024-02-09T22:52:24.375886Z  INFO page_service_conn_main{peer_addr=127.0.0.1:49066}:process_query{tenant_id=be8c7c43a5d38341c74db54fba26fa4e timeline_id=414ca6c7aa388aec2e760a18db8170fb}:handle_pagerequests:handle_get_page_at_lsn_request{rel=1663/12972/16396 blkno=18771 req_lsn=0/1AFFF100}:handle_get_page_at_lsn_request{shard_id=0000 shard_id=0000}: launched walredo process duration_ms=0 pid=4081
2024-02-09T22:52:25.273331Z  INFO request{method=PUT path=/v1/tenant/be8c7c43a5d38341c74db54fba26fa4e/location_config request_id=4db28a62-3980-44e1-bec2-41fd09e005eb}: Handling request
2024-02-09T22:52:25.273412Z  INFO request{method=PUT path=/v1/tenant/be8c7c43a5d38341c74db54fba26fa4e/location_config request_id=4db28a62-3980-44e1-bec2-41fd09e005eb}:upsert_location{tenant_id=be8c7c43a5d38341c74db54fba26fa4e shard_id=0000}: configuring tenant location to state Attached Single, gen=00000003
2024-02-09T22:52:25.273426Z  INFO request{method=PUT path=/v1/tenant/be8c7c43a5d38341c74db54fba26fa4e/location_config request_id=4db28a62-3980-44e1-bec2-41fd09e005eb}:upsert_location{tenant_id=be8c7c43a5d38341c74db54fba26fa4e shard_id=0000}: Shutting down attached tenant
2024-02-09T22:52:25.273438Z  INFO request{method=PUT path=/v1/tenant/be8c7c43a5d38341c74db54fba26fa4e/location_config request_id=4db28a62-3980-44e1-bec2-41fd09e005eb}:upsert_location{tenant_id=be8c7c43a5d38341c74db54fba26fa4e shard_id=0000}: Waiting for timelines...
2024-02-09T22:52:25.273454Z  INFO page_service_conn_main{peer_addr=127.0.0.1:49066}:process_query{tenant_id=be8c7c43a5d38341c74db54fba26fa4e timeline_id=414ca6c7aa388aec2e760a18db8170fb}:handle_pagerequests:handle_get_page_at_lsn_request{rel=1663/12972/16404 blkno=3114 req_lsn=0/1AFFF100}: dropping connection due to shutdown
```

# Assessment

We're getting a `/location_config` request for the tenant after the python test has observed the tenant as active.

That causes cancellation of the connection handler.

That makes the benchmark fail.

# Fix Ideas

 

```[tasklist]
### Tasks

- [ ] Understand why attachment_service sends that `/location_config` request
- [ ] Somehow work around this
- [ ] re-enable the test https://github.com/neondatabase/neon/pull/6785
```

**Comment by jcsp** [comment]
This week: investigate, delegate if it's a storage controller issue.

**Comment by VladLazar** [comment]
> Should we reenable the test on the CI / change the message then @VladLazar?
> 
> https://github.com/neondatabase/neon/blob/c3a40a06f3b35058acfa63490052c21309b9f745/test_runner/performance/pageserver/pagebench/test_pageserver_max_throughput_getpage_at_latest_lsn.py#L37-L40

Nope. The test is still flaky, but the failure mode is different (see issue https://github.com/neondatabase/neon/issues/6925). I'll bring it up in the next storage bug triage meeting.
