### ISSUE TITLE
per-timeline metric for on-demand download count & volume

### ISSUE THREAD

**Issue by problame** [neondatabase/neon#6737]
# Problem

Layer file on-demand downloads aren't measured per tenant_id.

This prevents definitive root cause analysis of latency spikes

Context: https://neondb.slack.com/archives/C033RQ5SPDH/p1707809037868189

# Workaround

Crawl logs for

```
{neon_service="pageserver"} |= `downloading on-demand` |= `$tenant_id`
```

# Fix

`call_begin()` only keeps track of `tenant_id,timeline_id` in

- REMOTE_TIMELINE_CLIENT_CALLS_UNFINISHED_GAUGE
- REMOTE_TIMELINE_CLIENT_BYTES_STARTED_COUNTER

The gauge isn't helpful unless the download takes > sampling interval.

And for on-demand downloads, we don't request bytes metric, probably because in the past there was another metrics already covering it, but I can't find that metric:

https://github.com/neondatabase/neon/blob/1bb9abebf2cc380fa5ef0b876280afd2d120c257/pageserver/src/tenant/remote_timeline_client.rs#L553-L573

```[tasklist]
### Tasks
- [ ] https://github.com/neondatabase/neon/pull/6834
- [x] fix dashboards broken by the PR
- [ ] https://github.com/neondatabase/neon/pull/6893
```

**Comment by jcsp** [comment]
Currently we have some per-timeline histograms of dubious value (could be replaced with e.g. just sum+count).

Get rid of one of more of those, then this can be added.

**Comment by jcsp** [comment]
Deploying this week
