### ISSUE TITLE
Epic: import compaction framework & tiered compaction code, default-off

### ISSUE THREAD

**Issue by arpad-m** [neondatabase/neon#6768]
## Motivation

The algorithms in the pageserver's compaction component aren't perfect and can be improved.

## DoD

We have implemented pluggable compaction support, see #5234. We also have implemented some (default off) algorithms and done some initial experiments with them, but commitment to rolling out any larger algorithm changes is optional, not required. The goal is to have the pluggable support merged before we go GA.

## Components

- [x] #5234
- [x] https://github.com/neondatabase/neon/pull/6830

- [x] https://github.com/neondatabase/neon/pull/7020
- [x] https://github.com/neondatabase/neon/pull/7026
- [x] https://github.com/neondatabase/neon/issues/7244 -> https://github.com/neondatabase/neon/pull/7282
- [x] https://github.com/neondatabase/neon/pull/7257

## Future Work / Punted into Q2 #7554 

- [ ] many updates for a single key ([link](https://github.com/neondatabase/neon/commit/045bc6af8bae53305cf30771faa2d8478299868b#diff-48a2345acf6708a7cc3dc3b7b6cbf0b3f921c54a20e4631c6ecadb43286a7c48R520), [link](https://github.com/neondatabase/neon/commit/045bc6af8bae53305cf30771faa2d8478299868b#diff-00d0f529cfb6da1b30e7adbb32a4b90db4b7dc2a7615769e15806eb7f8b4f5d4R4), [link](https://github.com/neondatabase/neon/pull/5234#discussion_r1333986725)), [issue](https://github.com/neondatabase/neon/issues/7243)
- [ ] #7287
- [ ] #7296
- [ ] getting test suite to pass with new compaction enabled ([first check](https://github.com/neondatabase/neon/pull/6964), [second](https://github.com/neondatabase/neon/pull/7283))

## Other related tasks and Epics
- Earlier PR #4539

**Comment by jcsp** [comment]
This week:
 - Get the existing PR green for merge.

**Comment by arpad-m** [comment]
Last week: got PR rebased, polished, reviewed, and addressed reviews. This week: merge the PR, work on analyzing the current setup, reading the literature, and work on followups.

**Comment by problame** [comment]
* read more literature
* follow-ups
  * PR this week, need to confer with Heikki about some aspects of the code

**Comment by jcsp** [comment]
This week:
- Compare old/new on gc_feedback (staircasing) test case.
- Fix the edge case where too many deltas on one key can result in oversized layer files.

Deferring work to make all the tests work with new style compaction (as far as we know these are test assumption issues rather than issues with new compaction) -- the near term goal is to reach "no known issues" status with new compaction.

**Comment by problame** [comment]
Redefined this issue as the work that has been done in Q1:

> ~~Epic: improved compaction and compaction algorithms framework~~
> Epic: import compaction framework & tiered compaction code

And moved the uncompleted items into section

> Future Work / Punted into Q2 https://github.com/neondatabase/neon/issues/7554
