### ISSUE TITLE
pageserver: `sync` on startup (eliminate bug class of unclear durability after `abort()`)

### ISSUE THREAD

**Issue by problame** [neondatabase/neon#6989]
If we abort() because of some filesystem error, systemd restarts the pageserver.
We might then read data from the file system and make decisions based on those reads, incorrectly assuming the data is durable, "because we just read it". 

A simple mechanism to prevent this mistake is to `sync()` the `/storage` partition during pageserver startup, before we read from it.

If the `sync()` fails, we `abort()` (again).

Note that this issue generally doesn't matter that much nowadays because we treat remote storage as the absolute authority (#5198).
Note again however, that fsync() between writes to the same file are still important, because we only rely on file length instead of content checksums.

# Tasks

```[tasklist]
### Tasks
- [ ] https://github.com/neondatabase/neon/pull/8835
- [ ] wait for rollout
- [ ] observe log output
```

**Comment by jcsp** [comment]
- Calling sync before cleaning up ephemeral layers is somewhat wasteful
- However, ephemeral layer cleanup happens relatively late in startup, after loading timeline metadata.
- This should only be a problem if linux was leaving really large amounts of data in page cache, without draining to disk in the background, which is atypical.
- We will syncfs() on startup and log how long the sync took, so that we have visibility if it's slow.

**Comment by problame** [comment]
Query

```
sum_over_time({neon_service="pageserver"} |= `made tenant directory contents durable` | regexp `elapsed_ms=(?P<elapsed_ms>\d+)` |unwrap elapsed_ms [7d])
```

executed today 18:00 UTC, after all regions have been deployed with this week's release

Top 3: 251ms, 161ms, 95ms

[Full query for posterity](https://neonprod.grafana.net/explore?schemaVersion=1&panes=%7B%226r6%22:%7B%22datasource%22:%22grafanacloud-logs%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22sum_over_time%28%7Bneon_service%3D%5C%22pageserver%5C%22%7D%20%7C%3D%20%60made%20tenant%20directory%20contents%20durable%60%20%7C%20regexp%20%60elapsed_ms%3D%28%3FP%3Celapsed_ms%3E%5C%5Cd%2B%29%60%20%7Cunwrap%20elapsed_ms%20%5B7d%5D%29%22,%22queryType%22:%22instant%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22grafanacloud-logs%22%7D,%22editorMode%22:%22code%22%7D%5D,%22range%22:%7B%22to%22:%221725530488306%22,%22from%22:%221725526888306%22%7D%7D%7D)
