### ISSUE TITLE
Epic: HTTP drivers galore

### ISSUE THREAD

**Issue by conradludgate** [neondatabase/neon#7032]
## Motivation

The serverless JS driver over HTTP has been a hit. Perfect for edge services which need to perform a few low-latency SQL queries.

## DoD

Agree on an ecosystem-wide standard for this (which might differ from our current implementation!) and implement a driver for a few more languages. Eventually, let the community do the rest.

## Features

```[tasklist]
- [x] Single query support with parameters
- [x] Non-interactive batch query support
- [ ] https://github.com/neondatabase/neon/issues/7035
- [ ] https://github.com/neondatabase/neon/issues/7034
- [ ] https://github.com/neondatabase/neon/issues/7033
```

## Languages

Rust and Python allow us to write two differing implementations and test them properly against proxy in our automatic testing.

```[tasklist]
- [x] JS
- [ ] Rust
- [ ] Python
- [ ] Java JDBC
```
