### ISSUE TITLE
pageserver: clean up ancestral layers after split, old index_part objects

### ISSUE THREAD

**Issue by jcsp** [neondatabase/neon#7043]
Per the "Cleaning up parent-shard layers" section in #6358 -- currently after a shard split, layers from the parent shards are not deleted until the whole tenant is eventually deleted.

We should implement an occasional online scrub routine that checks which of these are referenced by children, and cleans them up.

It likely makes sense to combine this work with cleaning up old-generation index_part.json objects, as these older objects will likely reference parent shard layers -- we should first define the criteria for cleaning up old indices, and then use the still-alive indices as the source of references for cleaning up parent layers.

```[tasklist]
### Tasks
- [ ] https://github.com/neondatabase/neon/pull/7925
- [ ] https://github.com/neondatabase/neon/pull/8196
- [ ] https://github.com/neondatabase/cloud/issues/14024
```

**Comment by jcsp** [comment]
This will be enabled in staging here: https://github.com/neondatabase/aws/pull/1654

Then we'll let it soak for at least a week before proceeding to prod.
