### ISSUE TITLE
Timeline::shutdown can leave a dangling `handle_walreceiver_connection` tokio task

### ISSUE THREAD

**Issue by problame** [neondatabase/neon#7062]
# Problem

```
diff --git a/pageserver/src/tenant/timeline/walreceiver.rs b/pageserver/src/tenant/timeline/walreceiver.rs
index 2fab6722b..2a2f9ab04 100644
--- a/pageserver/src/tenant/timeline/walreceiver.rs
+++ b/pageserver/src/tenant/timeline/walreceiver.rs
@@ -236,6 +236,10 @@ impl<E: Clone> TaskHandle<E> {
     async fn shutdown(self) {
         if let Some(jh) = self.join_handle {
             self.cancellation.cancel();
+            // we can stop being polled before the jh completes.
+            // it can happen because connection_manager_loop_step is in a tokio::select!() statement together with task_mgr cancellation:
+            // https://github.com/neondatabase/neon/blob/fb518aea0db046817987a463b1556ad950e97f09/pageserver/src/tenant/timeline/walreceiver.rs#L84-L104
+            // the consequence of that will be that we leave a tokio task that executes handle_walreceiver_connection running
             match jh.await {
                 Ok(Ok(())) => debug!("Shutdown success"),
                 Ok(Err(e)) => error!("Shutdown task error: {e:?}"),
```

Found together with @koivunej  while investigating https://github.com/neondatabase/neon/pull/7051

i.e., rapid `/location_config` that transition a tenant from Single to Multi and back with changing generation numbers, so, the code takes the slow path.

Consequence of this:

- the dangling task can continue to ingest WAL
- that means it can continue to try to
  - `put` / `finish_write` into the Timeline
    - which in turn can cause layers to be frozen & flushed
  - trigger on-demand downloads

We audited the codebase to ensure that, as of #7051 , none of the above will succeed after `Timeline::shutdown` returns.

# Solution Proposal

Don't cancel-by-drop the `connection_manager_loop_step`.
Use `shutdown_token()` instead and make code responsive to it.

# Impl

```[tasklist]
### Tasks
- [ ] https://github.com/neondatabase/neon/pull/7234
- [ ] https://github.com/neondatabase/neon/pull/7235
- [ ] https://github.com/neondatabase/neon/pull/7260
- [ ] https://github.com/neondatabase/neon/pull/7233
```

**Comment by problame** [comment]
Update:

* Small preliminary refactoring & fix is merged
* Given I had the walreceiver code loaded into my head, it was opportune to refactor walreceiver such that it no longer uses task_mgr, because we want to do that for GA.
* Opened PR #7260  for that, tracked in tasklist of this issue.
  * There's disagreement about the need/design around walreceiver early shutdown.
* Also opened further refactoring PR #7233 which is stacked atop #7260 
  * It might fix #7221, which @jcsp has been working on
