### ISSUE TITLE
tokio-epoll-uring: panic in prod due to tokio-epoll-uring creation failure

### ISSUE THREAD

**Issue by problame** [neondatabase/neon#7136]
https://neondb.slack.com/archives/C033RQ5SPDH/p1710490501672359
```[tasklist]
### Tasks
- [x] ~~investigate why no sentry message to slack channel~~ decided not to pursue this
- [ ] https://github.com/neondatabase/neon/pull/7141
- [ ] https://github.com/neondatabase/neon/pull/7160
- [ ] https://github.com/neondatabase/neon/pull/7164
- [x] alert on launch failures
```

**Comment by jcsp** [comment]
- It was an old kernel
- We eliminated the code paths that use spawn_blocking + handle block_on
- CHange last week: retry on out of locked memory instead of panicking.

Todo this week: create alert that uses new metrics
