### ISSUE TITLE
pageserver: stuck detach operation

### ISSUE THREAD

**Issue by problame** [neondatabase/neon#7427]
Stuck /location_config operation while transitioning from attached to secondary (i.e. Tenant::shutdown), clearly a bug in pageserver. We mitigated by restarting pageserver, but, we should debug this.

https://neondb.slack.com/archives/C03H1K0PGKH/p1713453288707669?thread_ts=1713444234.032949&cid=C03H1K0PGKH

This occurred during a /location_config call transitioning a pageserver from attached to secondary.

# Root Cause Analysis

https://github.com/neondatabase/neon/issues/7427#issuecomment-2220523013

tl;dr: no direct smoking gun, but, symptoms so far point to page_service keeping gate open for too long.

# Fixing It

Refactor page_service so that gate guard lifetime is easy to understand and obviously bounded to the requests that are ongoing at time of timeline shutdown.

Sketch: https://github.com/neondatabase/neon/pull/8286

```[tasklist]
### Tasks
- [ ] https://github.com/neondatabase/neon/pull/8224
- [ ] https://github.com/neondatabase/neon/pull/8227
- [ ] fix dashboards that used pageserver_live_connections
- [ ] https://github.com/neondatabase/neon/pull/8296
- [ ] https://github.com/neondatabase/neon/pull/8295
- [ ] https://github.com/neondatabase/neon/pull/8292
- [ ] https://github.com/neondatabase/neon/pull/8338
- [ ] https://github.com/neondatabase/neon/pull/8244
- [ ] https://github.com/neondatabase/neon/pull/8372
- [ ] https://github.com/neondatabase/neon/pull/8449
- [ ] https://github.com/neondatabase/neon/pull/8339
- [x] rollout to staging
- [x] monitor cancellation behvior / number of live connections in staging
- [x] rollout to prod
- [ ] https://github.com/neondatabase/neon/pull/8650
- [ ] https://github.com/neondatabase/neon/pull/8632
- [ ] larger scale testing of migrations to ensure it's truly fixed
- [ ] https://github.com/neondatabase/helm-charts/pull/96
- [ ] https://github.com/neondatabase/infra/pull/1746
- [x] deploy chaosInterval to staging https://neondb.slack.com/archives/C059ZC138NR/p1724079789211089
- [x] announce larger-scale testing to team https://neondb.slack.com/archives/C033A2WE6BZ/p1724080458246829
- [ ] give it a few days, analzye logs https://neondb.slack.com/archives/C033RQ5SPDH/p1724142868137099
```

```[tasklist]
### Follow-Ups
- [ ] https://github.com/neondatabase/neon/pull/8462
```

**Comment by problame** [comment]
Happened [again](https://neonprod.grafana.net/explore?schemaVersion=1&panes=%7B%22eoe%22:%7B%22datasource%22:%22grafanacloud-logs%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bunit%3D%5C%22pageserver.service%5C%22,hostname%3D%5C%22pageserver-7.us-east-2.aws.neon.tech%5C%22%7D%20%7C%3D%20%60cebe21e8c0b2e7449eab58f0c196dd39%60%20%20%21%3D%20%60downloading%20on-demand%20%60%20%7C%3D%20%60request%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22grafanacloud-logs%22%7D,%22editorMode%22:%22code%22%7D%5D,%22range%22:%7B%22from%22:%221713463642772%22,%22to%22:%221713464017220%22%7D%7D%7D&orgId=1) during that migration.

**Comment by jcsp** [comment]
Suspected regression from changes around shutdown recently: https://github.com/neondatabase/neon/pull/7233

**Comment by jcsp** [comment]
Next steps: look carefully at timeline shutdown code.

**Comment by jcsp** [comment]
We have plenty of examples of `kept the gate from closing` messages in the field.

We see them in `handle_get_page_at_lsn_request`, and `initial_size_calculation{...}:logical_size_calculation_task:get_or_maybe_download`

**Comment by jcsp** [comment]
Let's invest some time next week in looking for issues that might have been introduced in https://github.com/neondatabase/neon/pull/7233 -- I think a couple of hours of quality time staring at the code might yield results.

This week I spent some time writing a test (https://github.com/neondatabase/neon/tree/jcsp/shutdown-under-load-test) to try and reproduce shutdown hangs, without any success: this isn't completely surprising, because in the field we see one hang out of every ~10,000 migrations, so it's clearly something pretty niche.

**Comment by problame** [comment]
After lengthy investigation, I have no definitive smoking gun, but the hottest lead based on log message correlation is that `HandlerTimeline` holds the `Timeline::gate` open.

More details here (internal doc): https://www.notion.so/neondatabase/2024-07-01-stuck-detach-investigation-f0d4ae0247b347ab9bff95355fce1b25?pvs=4#c93179d978bc41d1a47f4b3821b12b81

**Comment by problame** [comment]
Also, the check for the first (as in `ShardSelector::First`) tenant in `handle_pagerequests` is insufficient if a pageserver hosts multiple tenant shards. For example, if we're hosting shard 1 and shard 2, and `::First` resolved to shard 1, but we want to detach shard 2, then we're sensitive to the wrong cancellation token.

**Comment by problame** [comment]
This week: finish preliminary refactorings & call for reviews of https://github.com/neondatabase/neon/pull/8339

**Comment by problame** [comment]
This week:

* PR got reviewed and merged on Wednesday
* => observe staging, watch out for growing connection count metrics / slow detach / deletions

Next week:

* PR will roll into prod.
* Should be safe to revert.

Week after:

* Once we know we won't need to revert, ship https://github.com/neondatabase/neon/pull/8462

**Comment by problame** [comment]
Status update:
* chaos injection has been running in staging 
* analysis / discussion thread: https://neondb.slack.com/archives/C033RQ5SPDH/p1724142868137099

**Comment by problame** [comment]
Calling victory on this, there were some minor issues exposed by the `chaosInterval` enablement, but none related to slow detaches.
