### ISSUE TITLE
Epic: Aux file store v2

### ISSUE THREAD

**Issue by skyzh** [neondatabase/neon#7462]
## Motivation

To store aux file efficiently, we use one key for each of the aux file. To workaround the fixed-size key constraint, we hash the file name into the key. As the chance of hash collision is low, it is likely that we can get one aux file stored in one key.

## Tasks

- PoC PR https://github.com/neondatabase/neon/pull/7375
- [x] missing key error improve https://github.com/neondatabase/neon/pull/7393
- [x] key encoding https://github.com/neondatabase/neon/pull/7401 https://github.com/neondatabase/neon/pull/7502
- [x] feature flag https://github.com/neondatabase/neon/pull/7424 https://github.com/neondatabase/neon/pull/7505
- [x] read path, using vectored get to do range scan - https://github.com/neondatabase/neon/pull/7503 https://github.com/neondatabase/neon/pull/7468
- [x] write path + basebackup read path https://github.com/neondatabase/neon/pull/7491 https://github.com/neondatabase/neon/pull/7517
- [x] grab user data and see how the new approach can improve the bloat situation

^--- likely done in the week of Apr 22 - Apr 26

- [x] merge PRs from previous weeks (1 left)
- [x] ~~separate scan interface to avoid maintaining untouched keyspaces~~
- [x] ~~decide migration method and write migration code~~
- [x] sparse keyspace support when creating image layers https://github.com/neondatabase/neon/pull/7567

^--- likely done in the week of Apr 29 - May 3

- [x] guide on enable
- [x] metrics https://github.com/neondatabase/neon/issues/7443 https://github.com/neondatabase/neon/pull/7623
- [x] persist the aux file flag https://github.com/neondatabase/neon/pull/7663 https://github.com/neondatabase/neon/pull/7668
- [x] https://github.com/neondatabase/neon/pull/7644 https://github.com/neondatabase/neon/pull/7742

^--- likely done in the week of May 6 - May 10

- [x] merge/refactor pull requests from last week
- [x] testing and benchmark https://github.com/neondatabase/neon/pull/7746
- [x] ensure scan does not go pass image layers https://github.com/neondatabase/neon/pull/7773

^--- likely done in the week of May 13 - May 17

- [ ] handle deletion tombstones in v2 https://github.com/neondatabase/neon/issues/7800
- [ ] measure memory consumption of scanning and warn if it gets too large https://github.com/neondatabase/neon/issues/7821

## Follow-up Works

- [ ] https://github.com/neondatabase/neon/issues/7563
- [ ] initial logical size computation for aux files https://github.com/neondatabase/neon/issues/7822
- [ ] remove the aux file v2 flag, migrate everyone to v2 (region by region?), remove v1 data
- [ ] prod?
- [ ] larger than 4GB image layer https://github.com/neondatabase/neon/issues/7796

## Other related tasks and Epics

The parent epic: https://github.com/neondatabase/neon/issues/7290. We will discuss further tasks like storing pg_stats and storing logical size in the new metadata key space in that epic issue.

**Comment by problame** [comment]
This week: after https://github.com/neondatabase/neon/pull/7517 is merged, testing & benchmarking on staging.

Improve on known perf bottlenecks:
* memory consumption for scans is currently not limited
  * fundamental limitation with using vectored scan

**Comment by skyzh** [comment]
All major works are done and closing this epic issue for now. I have created issues for all follow-up tasks. Might need one extra day at some point to implement the migration path when we decide how to roll this out to all users.
