### ISSUE TITLE
Epic: Support Azure Blob storage in the scrubber

### ISSUE THREAD

**Issue by arpad-m** [neondatabase/neon#7547]
## Motivation

We want to run the same tools on Azure Blob storage that we run on S3.

## DoD

The scrubber supports Azure Blob storage as well as S3.

## Implementation ideas

I'd implement this via extending the `remote_storage` crate to cover the use cases of the scrubber and porting the scrubber to it.

This doesn't have to happen in one go, but can go command-by-command. For the transition period, the scrubber could create both S3 and `remote_storage` contexts and then have each command use whatever it supports.

## Tasks

-  [x] `PurgeGarbage`: #7932
- [x] https://github.com/neondatabase/neon/pull/8013
- [x] https://github.com/neondatabase/neon/issues/8457
- [x] `FindGarbage`:  #8548
- [x] `ScanMetadata`: #8595 / #8673
- [ ] `TenantSnapshot`: #8673 for the download part
- [x] `PageserverPhysicalGc`: #8673
- [x] `FindLargeObjects`: #8541
- [x] https://github.com/neondatabase/neon/pull/8761

## Other related tasks and Epics
- #5567
- https://github.com/neondatabase/neon/issues/7667

**Comment by arpad-m** [comment]
This week:

* https://github.com/neondatabase/neon/issues/8457
* Maybe another PR that migrates some subcommands
