### ISSUE TITLE
Epic: Support read-only replicas following the primary

### ISSUE THREAD

**Issue by hlinnaka** [neondatabase/neon#769]
DoD:
The user can ship the replica instance for their workload

Compute_ctl:
- [ ] pass the parameters to compute_ctl
- [ ] be able to tweak the replication lag setting
- [ ] expose replication lag metric

Neon local: 
- [ ] #3714 

Python tests:
- [ ] be able to test replica instance

Postgres / Neon Extension:
- [ ] change the filter that accepts the WAL (take into account LSN cache and file_cache implementation)
- [ ] update WAL sender in order not to send WAL when the compute is a replica

Safekeepers (?)
Control plane

**Comment by MMeent** [comment]
A follow-up issue should consider the following: 

We can have a race condition in WAL replay:

1. Page A is not in our buffers
2. WAL redo thread starts replay of record X with start_lsn @ Y, end_lsn @ Z, which modifies page A.
3. WAL redo thread determines A is not in buffers, thus ignoring changes
4. Normal thread requests page A @ lsn, lsn = latest applied = Y
5. WAL redo thread completes redoing record X, updating the latest applied LSN to Z
6. Buffer for page A is now in an incorrect state.

With my implementation, I don't ignore changes to pages that are not in buffers, and thus this race condition is not an issue, but it does cause more traffic.

We could fix this issue by allocating and pinning buffers for all recorded pages, and dropping the pins after replaying (whilst also unregistering buffers that were not populated), but I don't think this is strictly necessary right now.

**Comment by hlinnaka** [comment]
Would this be fixed if in step 4, in the GetPage request, we used the LSN of the record we're currently replaying instead of the last applied LSN? I.e `XLogCtl->replayEndRecPtr`

**Comment by mikecaat** [comment]
Hi, thanks for developing the hot standby feature.
I'm interested in the feature to promote the standby. Do you have any plan to realize it?

**Comment by vadim2404** [comment]
Hey @mikecaat. For us, it's pretty straightforward to restart the primary compute.

**Comment by mikecaat** [comment]
Thanks for your response!

Yes, but I concerned about significant performance degradation until the cache warms up because getting data from pageserver is not so fast.

Amazon Aurora supports fail over, and I think it is a necessary feature for cases that require high availability in terms of maintaining high performance at all times.

Just out of curiosity, don't  your clients care? Is the cases not an appropriate use case for neon in the future as well? I assumed the priority of the feature is not just high because there is other high priority feature (ex. pageserver sharding, pageserver replica and so on?)

**Comment by vadim2404** [comment]
Your statement about shared_buffers is correct.

However, Aurora doesn't guarantee that the state in shared_buffers will be equal. If you don't send any read queries to the replica, you'll have in shared_buffers the latest inserted data. And some performance degradation you might notice as well.

Our compute instances don't fetch the whole data from pageservers. They do it on demand. If you do not query some data, it won't be present on compute instance.

Usually, our clients' databases are terminated to reduce money burn because no queries were sent in 5 minutes. There are different use cases.

Frankly saying, it's not our top priority at the moment, but I do believe that we will pick this item up when it'll be the right time.

**Comment by mikecaat** [comment]
> Your statement about shared_buffers is correct.
> 
> However, Aurora doesn't guarantee that the state in shared_buffers will be equal. If you don't send any read queries to the replica, you'll have in shared_buffers the latest inserted data. And some performance degradation you might notice as well.
> 
> Our compute instances don't fetch the whole data from pageservers. They do it on demand. If you do not query some data, it won't be present on compute instance.

Yes, I know. But, the penalty is quite large compared to aurora.

> Usually, our clients' databases are terminated to reduce money burn because no queries were sent in 5 minutes. There are different use cases.

Thank! It's interesting for me. Your customers use neon as serverless database and to optimize the costs is very important.

> Frankly saying, it's not our top priority at the moment, but I do believe that we will pick this item up when it'll be the right time.

Ok, I understand from your target usecase.  I hope that one day that time will come.


Thank you very much for telling your thought about the feature and priority. Anyway, I look forward to continuing the journey of neon!
