### ISSUE TITLE
upstream svg_fmt patches for draw-timeline-dir

### ISSUE THREAD

**Issue by problame** [neondatabase/neon#7763]
We needed some customizations to the `svg_fmt` crate for `pagectl draw-timeline-dir`.

```[tasklist]
### Tasks
- [x] Upstream PR: https://github.com/nical/rust_debug/pull/4
- [ ] https://github.com/neondatabase/neon/pull/7764
- [x] wait for them to release a version that contains the merged code instead of pointing to a Git revision
- [ ] https://github.com/nical/rust_debug/issues/5
- [ ] https://github.com/neondatabase/neon/pull/8930
```
