### ISSUE TITLE
GC parts of layers that are no longer needed (Legacy-Enhanced Compaction)

### ISSUE THREAD

**Issue by problame** [neondatabase/neon#8002]
Child of 2024Q2 compaction work: https://github.com/neondatabase/neon/issues/8001 

This epic tracks the efforts to work around legacy compaction's deficiencies in the area of GC.

The problem: legacy compaction can produce layer pattern where we can't GC layers beyond PITR window (staircase issue).

Solution (high-level): algorithm sketched in https://github.com/neondatabase/neon/pull/7948 

RFC: https://github.com/neondatabase/neon/pull/8425

Step 1: make the algorithm work + some necessary tests

- [x] skeleton https://github.com/neondatabase/neon/pull/7948
- [x] mock WAL record https://github.com/neondatabase/neon/pull/8015
- [x] unit tests with delta records https://github.com/neondatabase/neon/pull/8078
- [x] ensure it works on gc_feedback https://github.com/neondatabase/neon/pull/8103

Step 2: make the algorithm able to handle large jobs (i.e., 10-20GB, multiply by shard num it's ~100GB total DB size)

- [x] image iterator https://github.com/neondatabase/neon/pull/8006
- [x] delta iterator https://github.com/neondatabase/neon/pull/8064
- [x] k-merge https://github.com/neondatabase/neon/pull/8053
- [x] integrate k-merge with comapaction https://github.com/neondatabase/neon/pull/8415
- [ ] #8920
- [x] layer split https://github.com/neondatabase/neon/pull/8574 https://github.com/neondatabase/neon/pull/8599 https://github.com/neondatabase/neon/pull/8608
- [x] image-delta mixed merge iterator test https://github.com/neondatabase/neon/pull/8404
- [x] multi delta with the same LSN test
- [ ] #8921

Step 3: integrate with the rest of the system

- [ ] correct context for the read path
- [x] retain_lsn in gc-compaction (= branches) https://github.com/neondatabase/neon/pull/8328
- [x] handle images on child branches https://github.com/neondatabase/neon/pull/8519
- [x] manual trigger https://github.com/neondatabase/neon/pull/8103
- [ ] clean up resources of unfinished compactions (decide not to make the compaction resumable across page server restarts for now) https://github.com/neondatabase/neon/pull/8841

Misc

- [ ] handle will_init flag in wal redo mock record
- [x] a test case for branching https://github.com/neondatabase/neon/pull/8474
- [x] better split strategy for delta layers produced throughout the process https://github.com/neondatabase/neon/pull/8608
- [ ] https://github.com/neondatabase/neon/issues/8165
- [ ] revisit error return type (not using anyhow)
- [ ] avoid getting ancestor branch if we don't need the history in child branch
- [x] fix L0 condition https://github.com/neondatabase/neon/issues/8579 ?
- [x] #8838
- [ ] #8836
- [ ] #8837
- [ ] https://github.com/neondatabase/neon/pull/8884
- [ ] https://github.com/neondatabase/neon/issues/8861

Testing

- [x] https://github.com/neondatabase/neon/pull/8474
- [x] https://github.com/neondatabase/neon/pull/8557
- [ ] cancel force compaction

What's next: latest image layer compaction

**Comment by problame** [comment]
This week (and part of next week likely):
* Coding work: items in Step 1
* Design meeting to figure out how branching will work (@skyzh , @problame , @arpad-m  , John or product person)

**Comment by skyzh** [comment]
Last week: iterator APIs almost done, mock WAL record.
This week: test with test_gc_feedback, resolve PR comments.

**Comment by skyzh** [comment]
Updated plan this week: improve the streaming read interface, test with `test_gc_feedback`.

**Comment by skyzh** [comment]
Last week: B-tree iterator (but inefficient), fixed some bugs, passed test_gc_feedback.
This week: continue with the plan and merge iterator-related pull requests.

**Comment by skyzh** [comment]
Last week: merged iterator-related pull requests, brainstorm + design doc on branch compaction https://www.notion.so/neondatabase/Bottom-Most-Compaction-and-Garbage-Collection-9474c713ddee4b6586c264a6df1e044b
This week: implement retain LSN PoC, merge k-merge iterator pull request

**Comment by skyzh** [comment]
This week: retain_lsn PoC ready, oncall so not planning anything this week. Probably will add more tests on k-merge + branching to test the case we have mixed delta+image on the same LSN.

**Comment by skyzh** [comment]
going to resolve the comments + merge https://github.com/neondatabase/neon/pull/8608 and run dry-run mode testing in staging this week

**Comment by skyzh** [comment]
running in staging, will try larger tenents. goal for Sep: run on production tenants. secondary goal: collect aux v1 garbage.

**Comment by skyzh** [comment]
the implementation mostly complete and I'm closing it in favor of https://github.com/neondatabase/neon/issues/9114
