### ISSUE TITLE
Epic: Pageserver Timeline Archival

### ISSUE THREAD

**Issue by jcsp** [neondatabase/neon#8088]
## Purpose

Enable users to create branches fearlessly, without worrying about hitting branch count limits & without having to worry about cleaning up old branches unless they want to.

## Background

Currently, all timelines have significant physical overhead on the pageserver, even if they haven't been used for days/weeks/months:
- scanning timeline's remote storage path on tenant startup & load their index
- pinning some of the timeline's layers into local storage for logical size calculations
- running a wal receiver for the timeline

## Changes

This section isn't an authoritative design, but calls out functional areas that will need work.

- We'll need some manifest in remote storage that the tenant can read on startup to learn which timelines should be loaded in an active state, vs. which timelines are hibernated.  Keeping this properly up to date with timeline create/delete operations will be a key correctness point.
- Persist enough information about hibernated timelines that we can know their logical size (& any other key stats) without having to load them fully.  It probably makes sense to inline this into the per-tenant object that lists the timelines.
- Our runtime state in `Tenant` will need to only store active timelines in `Tenant::timelines`, and have some other map of hibernated timelines.
- APIs that list timelines will need either to change their semantics to only report active timelines, to avoid unreasonably large responses when users have many thousands of branches -- or paginated/queryable.  Bu
- An external API to enable the control plane to tell us when a timeline should be hibernated or awoken.  We could also choose to auto-hibernate after some period of inactivity, but that might be duplicative wrt the externally driven mechanism.`.
- A cache-warming routine that loads enough layers to serve reads at the tip of the branch, so that when we activate a timeline, the user doesn't encounter a long slow period while data is promoted to local storage.

```[tasklist]
### Milestone: archived branches are cheap locally -- (no index load on startup, no layers on disk, no Timeline at runtime)
- [ ] https://github.com/neondatabase/neon/issues/8218
- [ ] https://github.com/neondatabase/neon/pull/8131
- [ ] https://github.com/neondatabase/neon/pull/8414
- [ ] https://github.com/neondatabase/neon/pull/8458
- [x] https://github.com/neondatabase/neon/issues/8459 / https://github.com/neondatabase/neon/pull/8479
- [x] pageserver: implement visible layer housekeeping, for use in warm-ups
- [ ] https://github.com/neondatabase/neon/pull/8824
- [x] controller: add pass-through for `archival_config` API: #8680
- [ ] https://github.com/neondatabase/neon/pull/9122
- [ ] https://github.com/neondatabase/neon/pull/8907
- [ ] #9289
- [ ] https://github.com/neondatabase/neon/pull/9308
- [ ] https://github.com/neondatabase/neon/pull/9399
- [ ] https://github.com/neondatabase/neon/issues/9384
- [ ] #9421
- [ ] https://github.com/neondatabase/neon/issues/9386
- [ ] #9461
- [ ] #9489
- [ ] https://github.com/neondatabase/neon/pull/9519
- [ ] https://github.com/neondatabase/neon/pull/9525
- [ ] https://github.com/neondatabase/neon/pull/9539
- [ ] https://github.com/neondatabase/neon/pull/9578
- [ ] https://github.com/neondatabase/neon/pull/9582
- [ ] https://github.com/neondatabase/neon/pull/9583
- [ ] https://github.com/neondatabase/neon/pull/9598
- [ ] https://github.com/neondatabase/neon/pull/9599
- [x] pageserver: expose billing metrics for active size vs. archived size (decided to use logical size in the end, stop sending it after offload)
- [ ] #9646
- [ ] https://github.com/neondatabase/neon/pull/9760
- [ ] #9791
- [x] offloaded timeline query API
- [ ] https://github.com/neondatabase/neon/issues/9543
- [ ] #9790
```

```[tasklist]
### Misc lower priority changes
- [ ] https://github.com/neondatabase/neon/pull/10007
- [x] controller: ensure that timeline passthrough operations (incl. archival) land on shards with the latest generation (check generation is still current after they ack)
- [ ] https://github.com/neondatabase/neon/issues/9548
- [ ] test for many timelines depending on each other
- [ ] test that offloaded timelines are excluded from heatmaps and never downloaded to secondaries
- [ ] pytest for archival/unarchival together with storage controller and old generations
- [ ] resume deletion instead of logging warning [upon unoffloading](https://github.com/neondatabase/neon/pull/9444#discussion_r1809523471)
- [ ] make scrubber check that a timeline that is archived must have all of its children archived as well
- [ ] unified lock for offloaded/timelines/loading timelines: eliminates some race conditions and inconsistent states
- [ ] test: offload but pageserver crashes somewhere in delete_local_timeline_directory: can the pageserver deal with remnants after a restart?
- [ ] support deletion while offload is running (right now deletions return conflict http error)
```
### Milestone: archived branches are cheap in remote storage -- eventually written as compressed image layers at a single LSN

Moved to dedicated epic: #10336

**Comment by arpad-m** [comment]
This week:

* https://github.com/neondatabase/neon/issues/8459
* https://github.com/neondatabase/neon/issues/8460

**Comment by arpad-m** [comment]
This week:

* get #8907 merged (almost there)
* get #9289 merged.
* make PR for "still regard ancestor_lsn of non-flattened offloaded timelines as retain_lsn"
* make PR for "Synthetic size should exclude archived timelines"
* maybe also PR for "persistence for offloaded state"

**Comment by arpad-m** [comment]
This week:

* get #9308 merged (almost there)
* get #9289 merged (got a review last week, no time for getting it merge worthy yet)
* see if there needs to be more changes to synthetic size calculation beyond #9308.
* make PR for persistence for offloaded state

**Comment by arpad-m** [comment]
This week:

* merge #9444
* merge #9461
* enable offloading on staging (after merge of 9444)
* PR for synthetic size calculation (or finding that no PR is needed)
* test for deletion of offloaded timeline
* test for `retain_lsn` functionality for offloaded branches

**Comment by arpad-m** [comment]
Last week:

* merged https://github.com/neondatabase/neon/pull/9444
* merged https://github.com/neondatabase/neon/pull/9461
* filed and merged https://github.com/neondatabase/neon/pull/9489
* filed and merged https://github.com/neondatabase/neon/pull/9497
* filed and merged #9525
* filed #9519
* went over all locations where timelines are listed, identified some locations where offloaded should be listed too.

This week:

* after 9519 merges, enable offloading on staging
* test for `retain_lsn` functionality of offloaded branches
* return error if trying to detach ancestor of archived or offloaded timeline, demanding all children to be unarchived first.
* make deletion code check that the timeline also has no offloaded children in addition to no non-offloaded ones

**Comment by arpad-m** [comment]
Last week I made and merged a lot of pull requests. Although some of them are quite small, they fix a lot of possible misuses/edge cases that can lead to corruption:

* merged: https://github.com/neondatabase/neon/pull/9519
* enabled offloading on staging: https://github.com/neondatabase/infra/pull/2205
* filed and merged https://github.com/neondatabase/neon/pull/9525
* filed and merged https://github.com/neondatabase/neon/pull/9539
* filed and merged https://github.com/neondatabase/neon/pull/9578
* filed and merged https://github.com/neondatabase/neon/pull/9582
* filed and merged https://github.com/neondatabase/neon/pull/9583
* filed https://github.com/neondatabase/neon/pull/9598
* filed https://github.com/neondatabase/neon/pull/9599 <--- this one took me a long time of debugging, but it was worth the time, it's important to ensure that everything is correct.

There has also been work by John for https://github.com/neondatabase/neon/issues/9386, to make manifests more robust/generation ready:

* https://github.com/neondatabase/neon/pull/9545
* https://github.com/neondatabase/neon/pull/9555
* https://github.com/neondatabase/neon/pull/9557
* https://github.com/neondatabase/neon/pull/9609

This week:

* merge the two open PRs to add a test and make it possible to enable offloading for single tenants
* scrubber changes for https://github.com/neondatabase/neon/issues/9386, also to delete old generations of manifest
* monitor staging and see if there is corruptions

So it's going really well, and work is mostly complete. Now the main task is to ensure it rolls out safely, with us reducing the impact of any possible issue by doing a staged rollout.

**Comment by arpad-m** [comment]
Last week:

* filed and merged https://github.com/neondatabase/infra/pull/2391
* filed and merged #9760 (main time sink here was making the python tests reproduce the issue). also analyzed the corrupted tenants in staging together with Chi.
* filed and mergedhttps://github.com/neondatabase/infra/pull/2412

This week:

* Maybe getting #9646 into mergeable state
* a stab at #9790, if I get time for it (probably going to be next week's task)

**Comment by arpad-m** [comment]
Last week:

* merged https://github.com/neondatabase/neon/pull/9646
* merged https://github.com/neondatabase/neon/pull/9791

This week:

* test that offloaded timelines are excluded from heatmaps and never downloaded to secondaries
* test for many timelines depending on each other
* test: offload but pageserver crashes somewhere in delete_local_timeline_directory: can the pageserver deal with remnants after a restart?

**Comment by arpad-m** [comment]
This week I have:

* filed https://github.com/neondatabase/neon/pull/9942
* analyzed "could not find data for key" errors found in staging -> could see that the errors were different issues.
* identified three prod tenants to try offloading on them, applied config on them

Next week:

* get [#9942](https://github.com/neondatabase/neon/pull/9942) through review

**Comment by arpad-m** [comment]
This week I have:

* merged https://github.com/neondatabase/neon/pull/9942 
* filed https://github.com/neondatabase/neon/pull/10007
* prepared offloading for a prod region in the next week's release.
* filed issue for the rollout to prod: https://github.com/neondatabase/cloud/issues/21353

Next week:

* get https://github.com/neondatabase/neon/pull/10007 merged
* Christian wanted code to be nicer, so I'll probably do a refactor PR after the PR linked above
* monitor prod tenants and the newly rolled out prod region.

I think the issue has progressed enough that weekly updates are no longer neccessary from now on.

**Comment by arpad-m** [comment]
Closing in favour of #10336 and https://github.com/neondatabase/cloud/issues/21353 . Not giving the "misc lower priority changes" milestone its own epic. Stuff inside it can still be worked at, but not sure if tracking via epic makes sense.
