### ISSUE TITLE
pageserver: direct I/O

### ISSUE THREAD

**Issue by jcsp** [neondatabase/neon#8130]
- Project Slack: [#proj-pageserver-direct-io](https://neondb.slack.com/archives/C07BZ38E6SD)
- Initial proposal: https://github.com/neondatabase/neon/pull/8240
- Retroactive RFC: https://github.com/neondatabase/neon/pull/11788

Responsible:

- Yuchen Liang @yliang412 
- Christian Schwarz @problame 

---

Currently, we do buffered reads of data pages.  Direct reads would be a better fit, because:
- Pageserver data pages have an extremely low temporal locality on reads, because any repeatedly accessed pages are cached inside postgres.  This makes it largely a waste of memory, which we could be using for other things.
- The kernel page cache gives deceptively fast read performance on lightly loaded pageservers, making performance less consistent as pageservers are packed with larger numbers of tenants.

---

### Phase 1 Impl
- [x] https://github.com/neondatabase/neon/pull/8622
- [x] https://github.com/neondatabase/neon/issues/8719
- [x] https://github.com/neondatabase/neon/pull/8720
- [x] https://github.com/neondatabase/neon/pull/8942
- [x] https://github.com/neondatabase/neon/pull/8730
- [x] https://github.com/neondatabase/neon/pull/9175
- [x] Setup a manually managed testbench in EC2
- [x] Reminder to check for fork + direct I/O https://neondb.slack.com/archives/C07BZ38E6SD/p1723657162079879
- [x] Add aligned io buffer marker trait `IoBufAligned` and `IoBufAlignedMut`
- [x] TODO: check getpage latency

### Phase 2 Impl
- [x] Find and fix unaligned IOs for read
- [x] https://github.com/neondatabase/neon/pull/9326
- [x] https://github.com/neondatabase/infra/pull/2150
- [x] https://github.com/neondatabase/tokio-epoll-uring/issues/57
- [x] https://github.com/neondatabase/neon/issues/9387

### Rollout Read Path
- [x] rollout delta & image reads + in-memory layer rw to prod (with superscalar read path changes)

### Finish Write Path & Roll Out
- [ ] https://github.com/neondatabase/neon/issues/9868
- [ ] https://github.com/neondatabase/neon/pull/11868

### Retroactive RFC

- https://github.com/neondatabase/neon/pull/11788

### Punted

(make sure to check the retroactive RFC's "Future Work" section!)

- https://github.com/neondatabase/neon/issues/9713
- https://github.com/neondatabase/neon/issues/8803
- https://github.com/neondatabase/neon/issues/10092
- https://github.com/neondatabase/neon/issues/10101
- https://github.com/neondatabase/neon/issues/10129
- https://github.com/neondatabase/neon/issues/9288
- https://github.com/neondatabase/neon/issues/11890

**Comment by problame** [comment]
The direct IO RFC covers both read & write path. Renamed this epic to include reads and writes. (I don't think it's significantly more work).

**Comment by yliang412** [comment]
Last week:
- Drafted PS Config for Direct I/O
- Setup managed testbench on EC2

This week:
- Finish Simulation Mode + alignment check
- Use aligned buffers on read path

**Comment by problame** [comment]
sync meeting:
 
- VirtualFile wrapper
- primitive for aligned buffer (can we continue to use BytesMut but with an allocation that we provide?)
- vectored read planner refacot

**Comment by yliang412** [comment]
Last week:
- Worked on a couple versions of #8730.
- Ext4 kernel code inspection on no extra memcpy.
- Started working on #8719.

This week:
- Finish #8719.

**Comment by yliang412** [comment]
Last week:

- Opened https://github.com/neondatabase/neon/pull/8763
- Benchmarked chunked vectored blob read: https://www.notion.so/neondatabase/Benchmark-chunked-vectored-read-2024-08-26-0d8db0097df34e3797acad2b3804bcf6?pvs=4

**Comment by yliang412** [comment]
Last week:

- Merged and perf validated #8763 (on preprod), decided to go with `io_buffer_alignnment=512`.

This week:

- Polish https://github.com/neondatabase/neon/pull/8730 with a WIP stacked on top to show usage
- Rethink vectored_blob_io buffer interaction (where to do decompression + where to deserialize value?)

**Comment by problame** [comment]
Sync meeting:

* ship 4c0a61da2b8f328e61ca7c47f9cc98fc99357b7b as a preliminary PR, to land in prod as part of next week's release
  * retain `.freeze()` and `.slice()` for uncompressed buffers
  * additional allocation for compressed buffers is ok
  * review from @problame  and @arpad-m 
* continue https://github.com/neondatabase/neon/pull/8730
  * actually do O_DIRECT (quick and dirty)
  * see if it works functionally (local test bench, regression test suite run)
  * some basic `pagebench getpage-at-latest-lsn` benchmarking
    * 100% PS pagecache hit rate, resize like prod config, or resize further and take a note
    * 100% virtualfile fd cache hit rate, resize like prod config
  * fix until not failures
  * => this demonstrates we can do O_DIRECT on the read path without errors, and we have a performance ballpark

Next steps after that:

* InMemoryLayer direct IO for read of tail end
  * develop separately
  * then cherry-pick into https://github.com/neondatabase/neon/pull/8730
* slice up https://github.com/neondatabase/neon/pull/8730 and ship it to prod in a way that allows safe rollout

**Comment by yliang412** [comment]
Last week:
- deployed https://github.com/neondatabase/infra/pull/1927
This week:
- Ship https://github.com/neondatabase/neon/pull/8942 (a few final touches).
- Continue https://github.com/neondatabase/neon/pull/8730 with `O_DIRECT` enabled, make sure it works functionally.

**Comment by yliang412** [comment]
Sync Meeting: 
- Continue https://github.com/neondatabase/neon/pull/8730 with O_DIRECT enabled, make sure it works functionally.
- Should start to increase page cache size, targeting 100% PS pagecache hit rate.

**Comment by yliang412** [comment]
Last week:

- Worked on https://github.com/neondatabase/neon/pull/9169 with O_DIRECT enabled for delta + image layers. Passed all tests.
- Setup new testbench.

This week:
- Doubling pagecache size, to be deployed as part of this week's release: https://github.com/neondatabase/infra/pull/1961
- Running pagebench on ec2-testbench with prodlike pageserver config. Compare that to buffered io.
- Plan and if needed implement pagecache working set estimation
  - estimate what its last-N-minutes memory would need  to be for a 100% page cache hit rate.
  - [Slack Discussion](https://neondb.slack.com/archives/C07BZ38E6SD/p1727701264236269)

**Comment by yliang412** [comment]
Sync Meeting:

**Read Path Direct IO Deployment** Plan:**
- Ship VirtualFile changes that allows us to use direct IO for reads but still use buffered IO for writes https://github.com/neondatabase/neon/pull/9214.
- Get rid of `io_buffer_alignment` config, always use 512 for alignment and chunk size.
- Finish switching in-memory layer to use direct IO. Ship the direct IO read path.

**Page cache**
- Double page cache size again in next week's release.
- Implement Rolling HyperLogLog next week. 
  - think through compaction
- Watch page cache hit rate and relationship with getpage@lsn latency

**Comment by yliang412** [comment]
Last week:

- Finished implementing Direct IO for image / delta layer read path, opened https://github.com/neondatabase/neon/pull/9326
- Benchmarked using Direct IO for InMemoryLayer: https://www.notion.so/neondatabase/Benchmark-using-Direct-IO-for-InMemoryLayer-2024-10-10-11bf189e00478008aa12c912ff7b8506?pvs=4
  - Performance impact on ingestion is primarily on large values if buffered writer is given a bigger buffer.
  - `BufferedWriter` has some tech debt: flushing is done inline, blocking the next write.

This week:
- Merge https://github.com/neondatabase/neon/pull/9326, separate adhoc deployment to preprod nightly prodlike cloudebench run.
- Better `BufferedWriter` implementation with double buffering, then ship Direct IO for inmemory layer R/W and download layer (write code path that uses BufferedWriter)

**Comment by yliang412** [comment]
Last week:

- For  https://github.com/neondatabase/neon/pull/9326, There was always a few pg17 debug tests that does pass for both buffered and direct IO. showing `pageserver has not started yet...` Investigate if it is just flake.
- https://github.com/neondatabase/tokio-epoll-uring/pull/56
  - future: Possibly use [thread_local](https://docs.rs/thread_local/latest/thread_local/) crate? Benefit: have a nice iterator of `thread_local` values.
- Prototyped a double channel based buffered writer. 


This week:
- Merge https://github.com/neondatabase/neon/pull/9326
- turn the prototyped buffered writer into a PR.

**Comment by yliang412** [comment]
Last week:
- test and benchmark double-buffered writer
  - performance improved for small values.
  - performance regressed for large values, likely due to being CPU bound + disk write latency.
    - not as simple as turning on fsync for benchmarks. We don't fsync for in-memory layers in prod.

This week:
- Merge https://github.com/neondatabase/neon/pull/9693, without turning on `O_DIRECT`.
- Start working on https://github.com/neondatabase/neon/issues/9868.

**Comment by yliang412** [comment]
Last week:

- Running more benchmarks using Erik's bulk insertion benchmark: [test_ingest_insert_bulk](https://github.com/neondatabase/neon/pull/9812), [Result](https://www.notion.so/Benchmarking-New-BufferedWriter-11-20-2024-143f189e0047805ba99acda89f984d51?pvs=4#14af189e004780f5902de5d520b3e9ec)
  - Absolute throughput are faster on hetzner box (I feel this is expected)
  - Buffered writer with buffered IO always improves performance.
  - Buffered writer with direct IO shows performance improvement on hetzner box, but regression with im4gn.2xlarge

This week:

- Do more verification and at least deploy buffered writer with buffered io:  https://github.com/neondatabase/neon/pull/9693
- https://github.com/neondatabase/neon/issues/9868: 
  - refactor blob writer, separate disk write logic from compression logic.

**Comment by yliang412** [comment]
Last week:
- Merged https://github.com/neondatabase/neon/pull/9693, following double-buffering / direct io rollout plan in [Notion](https://www.notion.so/neondatabase/2024-12-04-double-buffering-direct-io-rollout-152f189e0047808f9449dc03224f7c79?pvs=4)
- image/delta layer writes O_DIRECT implementation work on https://github.com/neondatabase/neon/tree/yuchen/direct-io-delta-image-layer-write

This week:
- Discuss direct io rollout plan again
- Finish as much of https://github.com/neondatabase/neon/issues/9868 as possible.
- Document and knowledge transfer.

**Comment by yliang412** [comment]
- https://github.com/neondatabase/neon/pull/10063 functionalities should be done, Needs a bench_ingest like benchmark for image writes.
  - See https://github.com/neondatabase/neon/pull/10063#pullrequestreview-2497263855
- Created follow-up at https://github.com/neondatabase/neon/issues/8130#follow-ups

**Comment by problame** [comment]
Closing this as complete, rollout of direct IO on the write path to remaining prod regions is  being tracked in https://github.com/neondatabase/neon/issues/9868
