### ISSUE TITLE
bypass PageCache for `InMemoryLayer::get_values_reconstruct_data`

### ISSUE THREAD

**Issue by problame** [neondatabase/neon#8183]
part of epic https://github.com/neondatabase/neon/issues/7386

bit of prior discussion in https://neondb.slack.com/archives/C033RQ5SPDH/p1719411245662839

---

`InMemoryLayer::get_values_reconstruct_data` uses `read_blob`, which internally uses the PageCache for block access.

Switch it to vectored reads that bypass the PageCache.

However, we want to deliver equivalent performance compared to the current code in the case where the current code, in one call, reads multiple blobs from the same 8kb EphemeralFile page.

Strategy for this (planned together with @VladLazar ):

1. store the blob lengths in the in-memory btree
  - avoid consuming more memory space by using u32 instead of u64 for offset. u32 is enough if we cap EphemeralFile to 4GiB, which is way larger than we want it to go anyways 3. 
2. Get rid of the whole blob_io business for InMemoryLayer, we don't need it if we store offset and length in the in-memory index.
3. For `get_values_reconstruct_data`, feed the `(offset, length)` pairs directly into the `VectoredReadBuilder` (after sorting them in offset order, so the builder can merge adjacent blob reads as needed)

```[tasklist]
### Tasks
- [ ] https://github.com/neondatabase/neon/pull/8717
- [ ] https://github.com/neondatabase/neon/pull/8537
- [x] extraordinary rollout to pre-prod  & observe benchmark results
- [ ] rollout to prod & observe page cache dashboard
```

**Comment by problame** [comment]
This week:

* last touches on https://github.com/neondatabase/neon/pull/8537
* second review from John
* merge by Wednesday morning
* soak in staging until next week 

Next week:

* perf qualification in pre-prod
  * Can we do this earlier, e.g., by deploying a `main` build to pre-prod during this week?
* global rollout

**Comment by koivunej** [comment]
Additional extraordinary deploy to eu-west-1 before global rollout.

**Comment by problame** [comment]
Results from pre-prod:

* extraordinary deploy to eu-west-1 happened on Friday Aug 30 ~18:00 UTC, right before the prod-like cloudbench start
* => [no WARN or ERR in the logs](https://neonprod.grafana.net/explore?schemaVersion=1&panes=%7B%22hnx%22:%7B%22datasource%22:%22xHHYY0dVz%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bunit%3D%5C%22pageserver.service%5C%22,neon_region%3D%5C%22eu-west-1%5C%22%7D%20%7C~%20%60WARN%7CERR%60%20%21%3D%20%60running%20disk%20usage%20based%20eviction%60%20%21%3D%20%60Failed%20to%20list%20S3%20prefixes%60%20%21%3D%20%60:%20Cancelled%60%20%21%3D%20%60:%20cancelled%60%20%21%3D%20%60disk_usage_eviction_task:iteration%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22xHHYY0dVz%22%7D,%22editorMode%22:%22code%22%7D%5D,%22range%22:%7B%22from%22:%221725024398073%22,%22to%22:%221725276220609%22%7D%7D%7D&orgId=1)
* => [getpage latencies unchanged](https://neonprod.grafana.net/d/d061a222-a79b-4c4b-8e77-16b11545b1fe/pageserver-4-golden-signals?orgId=1&var-datasource=HUNg6jvVk&var-group_by=neon_region&var-getpage_latency_percentiles=0.99&var-getpage_latency_percentiles=0.999&var-instance=All&var-neon_region=eu-west-1&var-basebackup_latency_percentiles=0.99&var-basebackup_latency_percentiles=0.999&from=1724757443875&to=1725277133428)
* => pageserver page cache records [no more InMemoryLayer accesses](https://neonprod.grafana.net/d/fe7f056c-3ee1-49ef-a08d-e66055099396/pageserver-page-cache?orgId=1&from=1724156014000&to=1725270088000&var-datasource=HUNg6jvVk&var-adhoc=neon_region%7C%3D%7Ceu-west-1&var-hit_rate_drill_task_kind=&var-hit_rate_drill_content_kind=InMemoryLayer) (see screenshot below)
* no measurable impact on overall page cache access or miss rate (expected)
* `WalReceiverConnectionHandler` and `MgmtRequest` and `InitialLogicalSizeCalculation` benefitted but they're all low traffic


![Image](https://github.com/user-attachments/assets/7af6b6da-698f-46b4-90e0-60756549792f)




![Image](https://github.com/user-attachments/assets/269b9328-fd08-40a1-b697-03aa1eb7d7d7)

**Comment by problame** [comment]
production rollout => no more InMemoryLayer pages in PS PageCache ([dashboard](https://neonprod.grafana.net/d/fe7f056c-3ee1-49ef-a08d-e66055099396/pageserver-page-cache?orgId=1&from=1724928564667&to=1725531801877&var-datasource=ZNX49CDVz&var-hit_rate_drill_task_kind=Attach&var-hit_rate_drill_content_kind=InMemoryLayer))


![Image](https://github.com/user-attachments/assets/e8153b23-81d6-49e5-ad42-4235cf23a7a1)

No significant impact on overall PS PageCache performance due to the small role that InMemoryLayer plays generally in terms of access rate.

The improvements in PS PageCache performance are due to #8184  which rolled out to `ap-southeast-*` this week.

See this thread for details: https://neondb.slack.com/archives/C033RQ5SPDH/p1725530975830579
