### ISSUE TITLE
Epic: storage controller: AZ-aware scheduling

### ISSUE THREAD

**Issue by VladLazar** [neondatabase/neon#8264]
The storage controller does not take pageserver availability zone into account when scheduling tenants.

Ideally, the following scheduling constraints would be followed:
* Secondaries in a different AZ to attached locations. Avoids downtime in the event that an entire AZ goes down.
* Attached locations in an AZ that's consistent over time (modulo when we're doing a restart or failure) so that computes can be scheduled there. The control plane infers the AZ on which the compute should be scheduled
from the compute notification it receives from the storage controller. Keeping the AZ consistent avoids cross AZ traffic between compute and pageserver.
* If there are enough pageservers in one AZ, try to put all the shards in a tenant in the same AZ so that a compute in that region gets AZ-local performance (again, modulo when we're doing a restart or failure)

```[tasklist]
### Tasks
- [ ] https://github.com/neondatabase/neon/issues/8848
- [ ] https://github.com/neondatabase/cloud/issues/15413
- [ ] https://github.com/neondatabase/neon/issues/8969
- [ ] https://github.com/neondatabase/neon/pull/9946
- [ ] https://github.com/neondatabase/neon/pull/9947
- [ ] https://github.com/neondatabase/neon/pull/9953
- [ ] Schedule secondaries in a different AZ than attached locations
- [ ] Schedule attached locations into the same (home) AZ if there are enough pageservers there.
- [ ] In chaos tests, confirm that once idle the system converges on putting all the shards in their home AZs
- [ ] During tenant creation, pick home AZ based on AZ-wide utilization
- [ ] Rolling out: make sure most shards have a preferred AZ set
```

**Comment by jcsp** [comment]
Thinking a bit about this:
- AZ affinity gives each shard a true "primary" and "secondary" location.  We can use those in the scheduler instead of attached/secondary counts which fluctuate depending on what's going on.
- For optimization, we will need to handle shards having dual secondaries: when we want to smoothly relocate the primary, we will need to create another secondary in the home AZ, while leaving also a secondary in a remote AZ in case of failures.
- It probably makes sense to just always schedule all the shards of a sharded tenant in the home AZ, without trying to do any special casing for the mini-region case -- in such regions if one AZ's pageserver becomes overloaded, it just becomes time to expand the total pageserver count.  This is preferable to degrading the performance of a large tenant by scattering its shards across regions.

**Comment by VladLazar** [comment]
> AZ affinity gives each shard a true "primary" and "secondary" location. We can use those in the scheduler instead of attached/secondary counts which fluctuate depending on what's going on.

I don't really get what you mean here. AZ affinity gives you a preferred AZ. Do you mean that "primary = anywhere in the preferred AZ" and "secondary = anywhere not in the preferred AZ"?

> It probably makes sense to just always schedule all the shards of a sharded tenant in the home AZ, without trying to do any special casing for the mini-region case -- in such regions if one AZ's pageserver becomes overloaded, it just becomes time to expand the total pageserver count. This is preferable to degrading the performance of a large tenant by scattering its shards across regions.

Yeah, I agree with this. Primary should stay in the preferred AZ at all times apart from the unexpected failover case.

We should also think about the control plane and compute part of the stack. Currently, cplane tries to schedule in the same AZ as the `node_id` in `tenant_shards` table. This works okay for new tenant shards, but not great for existing ones. Since computes can be really long lived, perhaps preferred AZ should flow down from cplane (e.g. at start-up storcon calls into cplane for current compute AZ of each tenant shard).

**Comment by jcsp** [comment]
>I don't really get what you mean here. AZ affinity gives you a preferred AZ. Do you mean that "primary = anywhere in the preferred AZ" and "secondary = anywhere not in the preferred AZ"?

Right.

> Currently, cplane tries to schedule in the same AZ as the node_id in tenant_shards table. This works okay for new tenant shards, but not great for existing ones.

Yes, let's track that separately in https://github.com/neondatabase/cloud/issues/17159 & use this ticket for the controller end of things
