### ISSUE TITLE
Epic: storage controller: more graceful node removal

### ISSUE THREAD

**Issue by jcsp** [neondatabase/neon#8333]
The basic node removal API in https://github.com/neondatabase/neon/pull/8226 has some caveats:

## Tasks
- [ ] We should add a separate node draining command, mostly the same as what we do during pageserver restarts, and make it part of an overall two-step routine for decommissioning a node: first drain it gracefully, then use the delete command.  The delete command will always remain usable without the graceful drain, in case something is wrong and we need to push through  with the removal anyway.
- [ ] Once we have a separate command for draining the node, the `node remove` command should refuse to run by default if there is anything remaining on the node, and require a `--force` option to proceed anyway.
- [x] We should have some kind of tombstone for removed nodes (maybe just keep the DB row with a deleted flag but drop them from memory?) so that a node doesn't re-add itself if it restarts (example: a flaky node which is restarting and we can't reach it by SSH to stop the pageserver). 

## Follow-ups
- [ ] Hold the node exclusive lock for the entire duration of the Service::re-attach to sequence things properly.
- [ ] Update docs

**Comment by jcsp** [comment]
UX notes:
- How do I know I'm done?  That it's fully drained?  (e.g. how should it show up in CLI, admin console)
- Must retain the ability to do a "fast delete" without draining, in case drain wedges.
- "Undelete" path could be something other than removing a tombstone, e.g. we could re-run ansible provision on a node to give it a new ID etc.
