### ISSUE TITLE
Epic: Azure blob storage storage medium term tasks

### ISSUE THREAD

**Issue by arpad-m** [neondatabase/neon#8412]
This is a follow-up issue of #5567 which was about production-ready Azure blob storage support. The Azure blob storage is working well now, so this issue serves for the more medium to long term, lower priority tasks needed for maintenance and support.

```[tasklist]
### Tasks
- [ ] https://github.com/neondatabase/neon/issues/7547
- [ ] https://github.com/neondatabase/neon/issues/7546
- [ ] https://github.com/neondatabase/cloud/issues/12627
- [ ] https://github.com/neondatabase/neon/issues/7931
```
