### ISSUE TITLE
pageserver: 2x ingest performance

### ISSUE THREAD

**Issue by jcsp** [neondatabase/neon#8452]
Ingest performance can be improved a lot compared to where it is today.  This ticket has an initial achievable goal of doubling the measured ingest performance in MB/s as measured by test_bulk_insert.

The bottleneck is currently pageserver CPU/memory:
- We issue a huge number of calls to `TimelineWriter::put`, one for each delta.  In a typical WAL stream that means 10MB/s is 100,000 calls per second.
- `InMemoryLayerInner::index` is a btree map of Key to modifications of that key.  It grows huge, and also grows large because the keys are at least 18 bytes each.  When profiling, a significant fraction of runtime is spent in btreemap::entry (and Key::cmp).
- We repeatedly call Timeline::get during ingest to check the size of relations (in case they need extending), even though we're the only thing that can modify that size, so we can trust our own latest value.

```[tasklist]
### Tasks
- [ ] https://github.com/neondatabase/neon/pull/7409
- [ ] https://github.com/neondatabase/neon/pull/8683
- [ ] Change `TimelineWriter::put_batch` to avoid calling into put separately for each key: hold locks across the whole operation.  Also replace InMemoryLayer::put_value with a batched variant to avoid repeatedly locking the inner layer.
- [ ] #7418
- [ ] A more efficient implementation of `InMemoryLayerInner::index`: this might be as simple as adding a layer of indirection, where we store a HashMap of RelTags, and for each RelTag we store a BTreeMap of `u32` (blkno).
- [ ] Cache latest relation sizes in DatadirModification so that we read the sizes at most one per batch.
```

The branch where I spent a few hours investigating is https://github.com/neondatabase/neon/commits/jcsp/faster-ingest-2/.  This branch achieved a ~25% throughput improvement.  I anticipate that the next biggest thing to do is the index efficiency improvement.

**This is not an exhaustive list of ways to improve performance**.  Other stuff that will help but probably isn't necessary for an initial jump in performance:
- Make DataDirModification build its own serialized vector that can be dumped straight into an ephemeral layer, rather than our current multi-hop behavior of first storing Value in a map, then later serializing.
- Pipelining I/O in ephemeral layer's buffered writer, so that we don't block waiting for the last buffer to finish writing before we start on the next.
- Reading relation sizes even more rarely by maintain some state about latest relation sizes between batches.

**Comment by jcsp** [comment]
This ticket is redundant now that https://github.com/neondatabase/neon/issues/9329 is well underway.
