### ISSUE TITLE
Epic: safekeepers dynamic membership change (Phase 2)

### ISSUE THREAD

**Issue by koivunej** [neondatabase/neon#8614]
Phase 1 enabled runtime changes to walproposer configuration, and a semi-manual routine involving pullign timeline data between safekeepers (https://github.com/neondatabase/neon/issues/4782)

In this phase, we will implement joint consensus for the safekeeper

### Tasks
- [x] https://github.com/neondatabase/neon/pull/8455
- [x] https://github.com/neondatabase/neon/issues/8699 1-2w
- [x] https://github.com/neondatabase/neon/issues/8698
- [x] https://github.com/neondatabase/neon/issues/9981
- [x] https://github.com/neondatabase/neon/issues/9011 1-2w
- [x] https://github.com/neondatabase/cloud/issues/24511
- [x] https://github.com/neondatabase/neon/issues/9965
- [x] https://github.com/neondatabase/neon/issues/10851
- [x] https://github.com/neondatabase/neon/pull/11197
- [ ] https://github.com/neondatabase/neon/issues/11670
- [ ] https://github.com/neondatabase/neon/issues/11669
- [ ] --- Milestone: in neon_local, use storage controller management of timelines by default
- [ ] storage controller procedure to drive migration from old set to new set (includes API+CLI to evacuate SK) 1-2w
- [ ] --- Milestone: demonstrate (neon_local) full migration process with running compute (python tests) 1w
- [ ] Infrastructure to make storcon/SK bits work within the event simulator (i.e. not use a real network, or impl generic read/write traits and wire them into in-memory stuff) 1-2w
- [ ] Event simulator tests for changes (the primary tests for covering all the new code paths) 1w
- [x] https://github.com/neondatabase/neon/issues/10718
- [ ] cplane parts: https://github.com/neondatabase/cloud/issues/16796
- [ ] --- Milestone: demonstrate migration in staging including control plane parts, on selected timelines with SK generations enabled in their computes.
- [ ] Migrate all staging tenants' timelines into storage controller, enable SK generations for all computes in staging (1w)
- [ ] Add background migration chaos for SK timelinesn in storage controller + enable in staging (1w)
- [ ] --- Milestone: drill for SK node failure response, recovering using new APIs
- [ ] Migrate all prod tenants' timelines into storage controller
- [ ] Await compute restarts to pick up generation enablement: TODO coordinate with compute team on dates
- [ ] --- Milestone: demonstrate migration on prod
- [ ] https://github.com/neondatabase/neon/issues/10967
- [ ] fix ImportPgdata timeline creation path
- [ ] Ensure that branch reset works, fix missing data on sks for timelines on which rw ep never started
