### ISSUE TITLE
Make safekeepers registered in storage controller (deploy scripts)

### ISSUE THREAD

**Issue by koivunej** [neondatabase/neon#8698]
```[tasklist]
### Tasks
- [ ] https://github.com/neondatabase/neon/pull/8879
- [ ] https://github.com/neondatabase/infra/pull/1914
- [x] deploy: post safekeepers to storcon as well (except preview env)
```
