### ISSUE TITLE
Epic: compute performance observability

### ISSUE THREAD

**Issue by jcsp** [neondatabase/neon#8926]
## Motivation

Currently, it's hard to quickly attribute performance issues to a particular part of our I/O path (compute->safekeeper->pageserver).

We have a lot of metrics in the safekeeper and pageserver, but relative few in the compute.  The compute is closest to the user, and can give us a clearer picture of what performance the user is experiencing, as well as enabling us to measure end-to-end performance including network latency to the compute.

## DoD

- When we encounter a performance limit on the write or read path, we are able to say with confidence whether the bottleneck is on the compute or storage side
- When we see apparent slow getpage requests, we can distinguish between slowness inside the server, vs. slowness on the end-to-end path including network latency (by comparing server and client latencies)

## Tasks
```[tasklist]
- [ ] Prometheus metric for depth of queue of WAL being sent to safekeepers (i.e. measure how well safekeeper is keeping up.  We expect the safekeeper to service writes quickly, so this should always be low.  Spikes may indicates periods of unavailability)
- [ ] Prometheus metric for depth of queue of WAL not yet applied (i.e. measure how well pageserver is keeping up, when this metric hits the backpressure threshold we will throttle)
- [ ] Prometheus metric for time spent throttling due to WAL backpressure
```

## Other related tasks and Epics
-

**Comment by ololobus** [comment]
This week:

- [ ] Matthias: change extension views definition according to the new metrics in the #9116 + open PR with bumping the default version separately

**Comment by ololobus** [comment]
This week:

- [ ] @hlinnaka add new panels to https://neonprod.grafana.net/d/edc7unujh4uf4d/neon-autoscaling-per-vm-metrics or extend https://neonprod.grafana.net/d/cdv0fone2k1s0f/compute-replication-info-by-endpoint-id
- [ ] @hlinnaka had a look on the other items mentioned in the Epic
- [ ] @tristan957 finalize the backpressure PR

**Comment by tristan957** [comment]
backpressure PR: https://github.com/neondatabase/neon/pull/9176. Re-ran e2e flaky test failures. Ready for another review. Should be fairly straightforward.
