### ISSUE TITLE
Epic: sharded pageserver ingest

### ISSUE THREAD

**Issue by VladLazar** [neondatabase/neon#9329]
## Background

We currently we send all WAL to all pageserver shards, and each shard filters out the data that it needs,
in this epic we add a mechanism to filter the WAL on the safekeeper, so that each shard receives
only the data it needs.

RFC in https://github.com/neondatabase/neon/pull/8754.

```[tasklist]
### Sub-issues
- [ ] https://github.com/neondatabase/neon/issues/9328
- [ ] https://github.com/neondatabase/neon/issues/9335
- [ ] https://github.com/neondatabase/neon/issues/9336
- [ ] https://github.com/neondatabase/neon/issues/9337
- [ ] https://github.com/neondatabase/neon/issues/9338
- [ ] https://github.com/neondatabase/neon/issues/9339
- [ ] https://github.com/neondatabase/neon/issues/5543
- [ ] https://github.com/neondatabase/neon/issues/9569
```

```[tasklist]
### Nice to Haves
- [ ] https://github.com/neondatabase/neon/issues/7002
- [ ] https://github.com/neondatabase/neon/issues/5962
```

```[tasklist]
### Review follow-ups
- [ ] https://github.com/neondatabase/neon/issues/9491
- [ ] https://github.com/neondatabase/neon/issues/9823
- [ ] https://github.com/neondatabase/neon/issues/9824
```

**Comment by jcsp** [comment]
Can we reconcile this with https://github.com/neondatabase/neon/issues/6345?  (I don't mind replacing that issue, just want to avoid duplication)

**Comment by VladLazar** [comment]
Short pre winter holiday update.

* Sharded ingest is deployed in ap-southeast (https://github.com/neondatabase/neon/issues/9336)
* Fan-out code is functionally complete (https://github.com/neondatabase/neon/issues/9337)

Once we back:

* Continue deployment of sharded ingest to all other regions
* Tests and tweaks to the fan-out wal reader (e.g. use futures when not sharded to minimise task spawning)
* Separate roll-out of fan-out wal reader

**Comment by VladLazar** [comment]
As of `2025-04-22` we have:
* lifted WAL filtering to the safekeeper
* fanning out of WAL to different shards within the same safekeeper

We've punted on:
* cross-safekeeper coordination for WAL sending (https://github.com/neondatabase/neon/issues/9338)
* GRPC for SK to PS protocol (https://github.com/neondatabase/neon/issues/5543)
