### ISSUE TITLE
Epic: get page throughput improvements

### ISSUE THREAD

**Issue by VladLazar** [neondatabase/neon#9376]
Slack Channel: [#proj-pageserver-superscalar-page_service](https://neondb.slack.com/archives/C081MTB4BU4)

## Background

There's some fairly low-hanging fruit for improving get page tput on the pageserver:
* batch requests on the pageserver side
* IO parallelism on the read path
* configure computes to generate queue depth

@problame and @VladLazar  worked on this [during the Lisbon hackathon](https://github.com/neondatabase/neon/pull/9002)
and demonstrated 60k per sec get page tput. This epic is for productionizing and shipping that code (or some evolution of it).

### Big Rocks
- [ ] https://github.com/neondatabase/neon/pull/9002
- [x] https://github.com/neondatabase/neon/issues/9377
- [x] https://github.com/neondatabase/neon/issues/9378
