### ISSUE TITLE
pageserver: batch get page requests and serve them with one vectored get

### ISSUE THREAD

**Issue by VladLazar** [neondatabase/neon#9377]
We don't take advantage of queue depth generated by the compute
on the pageserver. We can process get page requests more efficiently
by batching them.

Hold get page requests for configurable maximum debounce timeout in order
to facilitate merging. Then process the entire batch via one get_vectored timeline operation.
By default, no merging takes place.

### Implementation
- [ ] https://github.com/neondatabase/neon/pull/9321
- [ ] https://github.com/neondatabase/neon/pull/9820
- [ ] https://github.com/neondatabase/neon/pull/9792
- [ ] https://github.com/neondatabase/neon/pull/9822
- [ ] https://github.com/neondatabase/neon/pull/9851
- [ ] https://github.com/neondatabase/neon/pull/9870
- [ ] https://github.com/neondatabase/neon/pull/9962
- [ ] https://github.com/neondatabase/neon/pull/10314
- [ ] https://github.com/neondatabase/neon/pull/10318
- [ ] https://github.com/neondatabase/neon/pull/10319
- [ ] https://github.com/neondatabase/neon/pull/10353
- [ ] https://github.com/neondatabase/neon/pull/10399
- [ ] https://github.com/neondatabase/neon/pull/10386
- [ ] https://github.com/neondatabase/neon/pull/10445
- [ ] https://github.com/neondatabase/neon/pull/10472
- [ ] https://github.com/neondatabase/neon/pull/10728
- [ ] https://github.com/neondatabase/neon/pull/10756
- [ ] https://github.com/neondatabase/neon/pull/10680

### TODOs
- [ ] https://github.com/neondatabase/neon/issues/9850
- [ ] https://github.com/neondatabase/neon/issues/9835
- [ ] https://github.com/neondatabase/neon/issues/9925
- [ ] https://github.com/neondatabase/neon/issues/10309
- [ ] https://github.com/neondatabase/neon/issues/10444
- [ ] https://github.com/neondatabase/cloud/issues/20620
- [x] https://github.com/neondatabase/neon/issues/10765
- [ ] https://github.com/neondatabase/neon/issues/9837

### Punted
- [ ] ~~small Retroactive RFC reuse write-ups in PRs, they're quite good~~
  - not doing because server-side batching will be obsoleted by [proj communicator] (https://github.com/neondatabase/company_projects/issues/352)
- [ ] https://github.com/neondatabase/neon/issues/10431
- [x] https://github.com/neondatabase/cloud/issues/24299
- [x] https://github.com/neondatabase/neon/issues/9382

**Comment by problame** [comment]
Restarting rollout this week.

Internal status update details positive performance impact observed in prod

https://neondb.slack.com/archives/C081MTB4BU4/p1737368349063989
