### ISSUE TITLE
pageserver: support 1 million relations

### ISSUE THREAD

**Issue by jcsp** [neondatabase/neon#9516]
Postgres itself does not define a practical limit on relations per database: the hard limit is approximately one billion, but it is well known that the practical limit is much lower, and dependent on hardware+config:
- https://www.postgresql.org/docs/current/limits.html
- https://www.pgcon.org/2013/schedule/attachments/283_Billion_Tables_Project-PgCon2013.pdf

To pick an arbitrary but realistic goal, let's support+test 1 million tables.  This is realistic because:
- Something like an array of relation sizes is only single digit megabytes with a million tables (whereas with a billion tables, such structures would likely need to be disk-based rather than simple in-memory structures)
- If we the can create a few thousand tables per second, then a test that creates a million tables can run in minutes, not hours (i.e. within the envelope of what our CI supports)

A tiny initial step in this direction is https://github.com/neondatabase/neon/pull/9507, which adds a test that creates 8000 tables (not very many!) to reproduce a specific scaling bug in transaction aborts.  That test currently has a relatively long runtime (tens of seconds) because our code for tracking timeline metadata is still very inefficient.

The goal is to make it work "fast enough", in the sense that a database is usable and things don't time out, but not necessarily to implement every possible optimisation.  For example, logical size calculations will be expensive with 1 million relations (requiring many megabytes of reads from storage), and that is okay as long as the expense does not cause the system to fail from the user's point of view.

```[tasklist]
### Tasks
- [ ] Replace RelDir with a more scalable alternative, such as using a sparse keyspace a la aux files
- [ ] Instead of interleaving relation sizes with data, store them in their own region of the keyspace (or even combine them into the new storage for RelDir).
- [ ] Test creating and dropping 1 million relations with this more scalable store.  We should see that runtime is reasonable (minutes), and memory+disk space used is O(N) with table count (not O(N^2))
- [ ] Implement code for rewriting metadata to the new format on startup. This should run very early during startup so that no other parts of the code need to understand the old format: we can then maintain this for a long time.
- [ ] Automated tests that have a snapshot of an old-style tenant and use it to continuously check that our latest code can still load such a tenant (extend `test_historic_storage_formats`)
- [ ] A much broader test for high relation counts: ensure that compaction runtimes are as expected, that logical replication works as expected.  This will need writing in collaboration with the compute team to cover the appropriate gamut of postgres features.  If this encounters unforseen issues, then spin these off into other github issues: this Epic is for the storage support for high table counts.
```

**Comment by skyzh** [comment]
All functionality patches are either merged or ready for review (the last one: https://github.com/neondatabase/neon/pull/10980). We can flip the flag for staging soon and do more testing.

**Comment by skyzh** [comment]
Next step: investigate slowness on arm64, consider moving relation sizes keys (could be a separate task), plan for staging tests and how to do full migrations.

**Comment by skyzh** [comment]
Next step: ensures tests are resilient and enable it across staging. I plan to extend test_historic_storage_formats, and add compaction/logical size calculation tests on large relation counts. Likely done this/next week.

**Comment by skyzh** [comment]
We have feature flag support now and it can have conditions over the tenant remote size. We will gradually roll this out in the near future.

**Comment by skyzh** [comment]
Looking at the current implementation, I decided to rework this feature a little bit to ensure the rollout is smooth.

My previous RFC suggested we will stop writing to the v1 keyspace right after v2 gets enabled. This would help with perf but we cannot rollback it anymore if things go wrong.

The new plan is:

* First phase: write to v1+v2 and validate reads of v1+v2. This means that we might double the read/write latency of the relation create/delete requests. The double write and validation behavior will be controlled by a feature flag "reldir_mode = phase-1".
* Once we have rolled out double writes to all tenants and things work fine for a few days, we will stop writing to v1 and solely serve requests from the v2 keyspace.

The thing to rework is the write path. On the write path, I'll add a few lines of new code that: once we decide to start the transition of v1->v2 (double write enabled), we will read everything from the v1 keyspace and write them to the v2 keyspace, so that from that write LSN, reldir v1 will have exactly the same content as reldir v2 (versus the original plan was to only write to one of them and combine the read result of the two).
