### ISSUE TITLE
Epic: s3 synchronisation follow ups

### ISSUE THREAD

**Issue by stepashka** [neondatabase/neon#977]
This Epic is a collection of follow ups for the S3 integration that was implemented in #340 

Here and below, "remote storage" is a synonym of "s3": we implement the logic for s3, but keep in mind, that other types of storages are involved and may require support later, so the solutions should be generic enough.

no specific order is required for these:

- [ ] #1557
- [ ] #987
- [ ] #1558
- [ ] #1559
- [x] #1049
- [x] serialize and write remote timeline index to s3 periodically to mitigate potential `s3 list` issues (done via https://github.com/neondatabase/neon/issues/1493, see https://github.com/neondatabase/neon/compare/kb/remove-remote-storage-archiving?expand=1 branch for the details)
- [x] migrate to rusoto s3 client from rust-s3, to prepeare for a future `aws-sdk-rust` migration when it matures ("official" but immature crate, it has a similar api to rusoto, more beneficial for our streaming api in many ways). Rusoto was picked as the new library to use: [the PR]( https://github.com/zenithdb/zenith/pull/1483.) Also there's an alternative branch for [aws-sdk-s3](https://github.com/zenithdb/zenith/tree/kb/rusoto-s3).
- [ ] sort out issues with pageserver checkpoints diverging local state from the remote one: #971
- [x] #755 (intersects with @LizardWizzard  's migration work)
- [x] https://github.com/zenithdb/zenith/pull/1080 implement pageserver's s3 prefixes to accomodate multiple pageservers on an s3 bucket
- [x] some preparation for IT tests is needed: s3 parameters ergonomics, refactor pageserver CLI params (currently working on that in #871 )
- [ ] In pageserver recovery we may push whole timeline dir as a checkpoint not only the necessary data. See: https://github.com/zenithdb/zenith/blob/adb0b3dadaf5a4f099e13adeaf8291c2d4b94550/pageserver/src/remote_storage/storage_sync.rs#L725. Also this data may contain garbage as we do not have checksums right now, and we probably should avoid checking every file in timeline dir on startup. Only files which were created after disk consistent lsn. Or we should just remove possibly incorrect files and rebuild the delta from wal
- [x] ?? whatever else @LizardWizzard  finds needed and useful during his tenant migration work, bugs, consistency bugs and performance issues presumably
- [x] randomly allocated work would be needed on refactoring and general logging, metrics and tracing span placement around the s3 sync code to make it observable

...... Some time later: 
- [x] add a CLI tool to manage archives in the remote storage (to help with the debugging) https://github.com/zenithdb/zenith/pull/1203
- [ ] introduce GC support in s3 (defragmentation tasks) #999 
- [x] #1493
- [x] deal with branches properly: remove them from pageserver and sync logic entirely, using `ZTimelineId`'s instead, adjust pageserver's http api

**Comment by LizardWizzard** [comment]
Some open questions from #1163:

* How to match SLO on new compute start? Do we always keep timeline assigned to at least one pageserver or we can completely unload it. In that case cold start can take quite a long time especially for large timelines. IMO we should keep timeline on at least one pageserver
* Can we/should we interleave download with loading? I e download some index parts, and begin bootstrapping it before all the data is available locally. It might be quite hard to organize given our mix of sync/async parts of repository/remote storage sync.

**Comment by LizardWizzard** [comment]
This epic is quite old, and since new tasks continue to fall into the scope, we (@stepashka and I) decided to close this epic and create a new one and move relevant tasks to it. Further enhancement of s3 integration in pageserver happens in #1556.
