### ISSUE TITLE
Ship on-demand SLRU downloads

### ISSUE THREAD

**Issue by jcsp** [neondatabase/neon#9872]
Currently, we have a `lazy_slru_download` setting in TenantConf which is false by default.  When this is set to true, we omit SLRU pages from the basebackup, and postgres downloads them on-demand.  This has not been widely used and it is not known how robustly this works in practice.

```[tasklist]
### Tasks
- [ ] Performance: comparative benchmarking for a tenant which has large (~1GB) SLRUs: a workload that requires reading those SLRUs, then compare runtime between inlining SLRUs in the basebackup vs. downloading them on-demand.  Build on existing `test_lazy_startup` performance test?
- [ ] Testing: inspect tests in `test_ondemand_slru_download.py` and look for missing cases
- [ ] Rollout: create a strategy for managing risk when rolling this out.  Perhaps use posthog feature flags.
```
