### ISSUE TITLE
Epic: stabilize Postgres prefetch

### ISSUE THREAD

**Issue by ololobus** [neondatabase/neon#9893]
## Motivation

Konstantin and other people recently [discovered several prefetch problems](https://neondb.slack.com/archives/C04DGM6SMTM/p1732514545096869)

## DoD

There are no known prefetch problems. Existing issues fixed and covered with tests

## Tasks
```[tasklist]
- [x] Prefetch doesn't work in Postgres 17
- [x] PG17 Konstantin's take https://github.com/neondatabase/neon/pull/9865 (direct backport of <PG17 code)
- [x] PG17 Matthias' take https://github.com/neondatabase/neon/pull/9860 (new PG17 flow)
- [x] Write a test with huge seqscan and comapre perf in <=PG16 and PG17 (new prefetch) -> seems good by Konstantin's tests
- [ ] https://github.com/neondatabase/neon/issues/9866
- [ ] https://github.com/neondatabase/neon/pull/9847
- [ ] Index-only-scan inconsistencies (??? hard to reproduce) -> upstream issues
- [ ] https://github.com/neondatabase/neon/issues/9961
- [x] Set io_combine_limit=1 for PG 17
```

## Other related tasks and Epics
- https://github.com/neondatabase/cloud/issues/12088

**Comment by ololobus** [comment]
This week:

- [ ] @knizhnik benchmark Matthias' PG17 prefetch against PG16 implementation https://github.com/neondatabase/neon/pull/9860
- [ ] @knizhnik merge https://github.com/neondatabase/neon/pull/9847
- [ ] @knizhnik address comments in https://github.com/neondatabase/neon/pull/9867, @MMeent review

**Comment by ololobus** [comment]
This week:

- [ ] @knizhnik @MMeent get PG 17 PR merged https://github.com/neondatabase/neon/pull/9860
- [ ] @MMeent do another round of review for https://github.com/neondatabase/neon/pull/9867

**Comment by ololobus** [comment]
This week:

- [ ] @MMeent merge https://github.com/neondatabase/neon/pull/9860
- [ ] @MMeent do another round of review for https://github.com/neondatabase/neon/pull/9867
