### ISSUE TITLE
Epic: Postgres roles related issues

### ISSUE THREAD

**Issue by lubennikovaav** [neondatabase/neon#9894]
## Motivation

We have a number of issues that are related to the way we manage Postgres roles.
Collect them all in one Epic to have a better overview of the problems and solve them consistently.

See [Postgres Roles in Neon](https://docs.neon.build/compute/postgres_roles.html#postgres-roles-in-neon) section of the internal documentation for more details on the implementation details and big architectural decisions.

## TODO:
```[tasklist]
- [ ] Make  neon_superuser a member of the predefined postgres roles that we consider safe to expose.
- [ ] i.e. https://github.com/neondatabase/neon/issues/6204
- [ ] Give neon_superuser ADMIN on the predefined postgres roles that we consider safe to expose.
- [ ] i.e. https://github.com/neondatabase/neon/issues/9550
- [ ] Allow event triggers to neon_superuser (now they are restricted to superusers) https://github.com/neondatabase/neon/issues/7570
- [ ] neon_superuser cannot comment on objects owned by cloud_admin #14454 https://github.com/neondatabase/cloud/issues/14454
- [ ] Grant neon_superuser with ADMIN, so it was possible to re-grant it.
- [ ] Allow NOLOGIN roles to be created without a password.
- [ ] Generate a password for the user if it is not provided instead of throwing an error.
```

## Other related tasks and Epics

Some of the issues are necessary to unlock this task:
- https://github.com/neondatabase/cloud/issues/18440

**Comment by clarkbw** [comment]
If I could choose one to get done first it would be support for event triggers  https://github.com/neondatabase/neon/issues/7570
